force-app/main/default/objects/Cambios_OLI__c/Cambios_OLI__c.object-meta.xml
<CustomObject>
    <label>Cambios OLI</label>
    <nameField>
        <label>Cambios OLI Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cambios OLI</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Cambios_OLI__c/fields/Accion__c.field-meta.xml
<CustomField>
    <fullName>Accion__c</fullName>
    <label>Accion</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Cambios_OLI__c/fields/Fecha_de_Cambio__c.field-meta.xml
<CustomField>
    <fullName>Fecha_de_Cambio__c</fullName>
    <label>Fecha de Cambio</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Cambios_OLI__c/fields/Oportunidad_Referencia__c.field-meta.xml
<CustomField>
    <fullName>Oportunidad_Referencia__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Oportunidad Referencia</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Cambios OLI</relationshipLabel>
    <relationshipName>Cambios_OLI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cambios_OLI__c/fields/Producto_Referencia__c.field-meta.xml
<CustomField>
    <fullName>Producto_Referencia__c</fullName>
    <label>Producto Referencia</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Cambios_OLI__c/fields/Usuario__c.field-meta.xml
<CustomField>
    <fullName>Usuario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Cambios_OLI</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Cambios_OLI__c/fields/Valor_Actual__c.field-meta.xml
<CustomField>
    <fullName>Valor_Actual__c</fullName>
    <label>Valor Actual</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Cambios_OLI__c/fields/Valor_Anterior__c.field-meta.xml
<CustomField>
    <fullName>Valor_Anterior__c</fullName>
    <label>Valor Anterior</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Configuracion_USA__c/Configuracion_USA__c.object-meta.xml
<CustomObject>
    <label>Admin Setting</label>
    <nameField>
        <label>Admin Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admin Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuracion_USA__c/fields/RecordType_for_OppNro__c.field-meta.xml
<CustomField>
    <fullName>RecordType_for_OppNro__c</fullName>
    <label>RecordType for OppNro</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>Addendum to the Soybean Germplasm Aggrement.</description>
    <label>Schedule A</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Schedule A Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Licensee Account</description>
    <label>Licensee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contratos_de_Multiplicacion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24/2024</fullName>
            </value>
            <value>
                <fullName>23/2023</fullName>
            </value>
            <value>
                <fullName>22/2022</fullName>
            </value>
            <value>
                <fullName>21/2021</fullName>
            </value>
            <value>
                <fullName>20/2020</fullName>
            </value>
            <value>
                <fullName>19/2019</fullName>
            </value>
            <value>
                <fullName>18/2018</fullName>
            </value>
            <value>
                <fullName>17/2017</fullName>
            </value>
            <value>
                <fullName>16/2016</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_del_Contrato__c/Item_del_Contrato__c.object-meta.xml
<CustomObject>
    <description>Addendum Variety item</description>
    <label>Schedule A Variety</label>
    <nameField>
        <label>Schedule A Variety</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules A Variety</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_del_Contrato__c/fields/Contrato_de_Multiplicacion__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Multiplicacion__c</fullName>
    <description>Agreement related to</description>
    <inlineHelpText>Agreement related to</inlineHelpText>
    <label>Schedule A</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Schedules A Variety</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_del_Contrato__c/fields/Cultivar__c.field-meta.xml
<CustomField>
    <fullName>Cultivar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cultivar por el/los que se confecciona el contrato</description>
    <inlineHelpText>Cultivar por el/los que se confecciona el contrato</inlineHelpText>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Royalty</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Schedules A Variety</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item_del_Contrato__c/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <formula>Cultivar__r.Variedade__r.Name</formula>
    <label>Variety Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/AnexoI.recordType-meta.xml
<RecordType>
    <fullName>AnexoI</fullName>
    <active>true</active>
    <businessProcess>Portal Reports</businessProcess>
    <label>Appendix I</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Contrato_relacionado__c.field-meta.xml
<CustomField>
    <fullName>Contrato_relacionado__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contrato Relacionado</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variety Name</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/USAUtils.cls
public class USAUtils {

    public static Map<String,Id> cargarProfilesbyName() {
       
        Map<String,Id> rTypes = new Map<String,Id>();
        Schema.Describesobjectresult d = Profile.sObjectType.getDescribe();
        Map<String, Schema.Recordtypeinfo> rt = d.getRecordTypeInfosByName();
        
        for(String s : rt.keySet()) {
            rTypes.put(s, rt.get(s).getRecordTypeId());
        }       
        
        return rTypes;
    }
    
    public static Map<String,String> cargarRecordTypesOppbyDevName() {
       
        Map<String,String> rTypes = new Map<String,String>();
        for(RecordType rt : [SELECT Id,DeveloperName,Name FROM RecordType WHERE SobjectType='Opportunity']){         
            rTypes.put(rt.DeveloperName, rt.Name);
        }       
        
        return rTypes;
    }

    public static Map<String,Id> cargarRecordTypesOppbyName() {
       
        Map<String,Id> rTypes = new Map<String,Id>();
        Schema.Describesobjectresult d = Opportunity.sObjectType.getDescribe();
        Map<String, Schema.Recordtypeinfo> rt = d.getRecordTypeInfosByName();
        
        for(String s : rt.keySet()) {
            rTypes.put(s, rt.get(s).getRecordTypeId());
        }       
        
        return rTypes;
    }
    
    public static Map<Id, String> cargarRecordTypesOppbyId() {
       
        Map<Id, String> rTypes = new Map<Id, String>();
        Schema.Describesobjectresult d = Opportunity.sObjectType.getDescribe();
        Map<String, Schema.Recordtypeinfo> rt = d.getRecordTypeInfosByName();
        
        for(String s : rt.keySet()) {
            rTypes.put(rt.get(s).getRecordTypeId(),s);
        }       
        
        return rTypes;
    }
    
    public static Cambios_OLI__c cambiosOLI(String acc,String prod, String ant,String actual, String user, String OppId){
        Cambios_OLI__c cc = new Cambios_OLI__c(Accion__c=acc,Producto_Referencia__c=prod,Valor_Anterior__c=ant,Valor_Actual__c=actual);
        cc.Usuario__c = user;
        cc.Fecha_de_Cambio__c = system.now();
        cc.Oportunidad_Referencia__c = oppId;
        return cc;  
    }
    
    public USAUtils(ApexPages.StandardController controller){  
    }
    public USAUtils(){        
    }        
           
    public static boolean actualizarNroAutorizacionAnexos(Opportunity[] oppsNew)
    {       
        Map<Id, String> rt = cargarRecordTypesOppbyId();
        Integer maximo = 0; String camp = '';
        List<String> devIds = new List<String>();
        
        devIds.add('AnexoI');
        Configuracion_USA__c[] confs = aSiteUtils.queryResults1(Configuracion_USA__c.SObjectType, null, 'Id <> :v1', '');        
        if(confs.size() > 0)
            devIds = confs[0].RecordType_for_OppNro__c.split(',');
                                  
        for(Opportunity o1 : oppsNew)
            camp = o1.Safra__c;
            
        if(camp==null)
            return false;

        list<aggregateResult> aggResults = [SELECT MAX(Nro_autorizacion__c) nroMax FROM Opportunity
        where Nro_autorizacion__c <> null and Safra__c = :camp and
        RecordType.DeveloperName IN :devIds ];
        
        maximo = Integer.valueOf(aggResults[0].get('nroMax'));
        if(maximo==null) maximo = 0;
        
        System.debug('Max is: ' + aggResults[0].get('nroMax'));

        String n;
        for(Opportunity o : oppsNew){
            n = rt.get(o.RecordTypeId);
            if(n != null)
                if((n.contains('Report') || n.contains('App') || n == 'Exportacion' || n == 'Reembalaje') && o.Nro_autorizacion__c == null){
                    maximo++;
                    o.Nro_autorizacion__c = maximo;
                    o.Name = (maximo + 1) + '-' + EncodingUtil.convertToHex(crypto.generateAesKey(128)).substring(1,3).toLowerCase() + '/20' + camp.substring(5, 7);
                }               
        }
        return true;
    }
       
    public static boolean actualizarContratoItem(OpportunityLineItem[] oppItems)
    {
        //Probar si al actualizar masivamente OpportunityLineItems deja mal los setados los contratos. Hay que tener en cuenta la marca del contrato.
        Id accId; Id oppId;
        List<Id> pbeIds = new List<Id>();
        Map<String,String> OppAcc = New Map<String,String>();
        Map<String,String> pbeMap = new Map<String,String>();
        Map<String,String> conMap = new Map<String,String>();
        Set<Id> opps = New Set<Id>();
        Set<Id> accs = New Set<Id>();
        Set<String> safras = New Set<String>();
        
        try{
        
            for(OpportunityLineItem i : oppItems){
                opps.add(i.OpportunityId);
                pbeIds.add(i.PricebookEntryId);
            }
            
            for(PricebookEntry pbe : [Select Id, Product2.Variedade__c From PricebookEntry Where Id in :pbeIds]){
                pbeMap.put(String.ValueOf(pbe.Id), String.ValueOf(pbe.Product2.Variedade__c));    
            }
                        
            for(Opportunity op : [SELECT Id, AccountId, Safra__c FROM Opportunity WHERE Id IN :opps]){
                accs.add(op.AccountId);
                safras.add(op.Safra__c);
                if(!OppAcc.ContainsKey(String.ValueOf(op.Id))) OppAcc.put(String.ValueOf(op.Id), String.ValueOf(op.AccountId));
            }

            for(Item_del_Contrato__c itc : [SELECT Id, Contrato_de_Multiplicacion__c, Cultivar__r.Variedade__c, Contrato_de_Multiplicacion__r.Multiplicador__c, Contrato_de_Multiplicacion__r.Safra__c FROM Item_del_Contrato__c WHERE Contrato_de_Multiplicacion__r.Multiplicador__c IN :accs AND Contrato_de_Multiplicacion__r.Safra__c IN :safras]){
                if(!conMap.containsKey(String.ValueOf(itc.Contrato_de_Multiplicacion__r.Multiplicador__c)+String.ValueOf(itc.Contrato_de_Multiplicacion__r.Safra__c)+String.ValueOf(itc.Cultivar__r.Variedade__c)))
                    conMap.put(String.ValueOf(itc.Contrato_de_Multiplicacion__r.Multiplicador__c)+String.ValueOf(itc.Contrato_de_Multiplicacion__r.Safra__c)+String.ValueOf(itc.Cultivar__r.Variedade__c), String.ValueOf(itc.Contrato_de_Multiplicacion__c));
            }
            for(OpportunityLineItem i : oppItems){
                i.Contrato_relacionado__c = conMap.get(OppAcc.get(String.ValueOf(i.OpportunityId))+String.ValueOf(i.Safra__c)+pbeMap.get(String.ValueOf(i.PricebookEntryId)));
            }
        }
        catch(Exception e){
            return false;
        }
        
        return true;
        
    }
    
}