force-app/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de SiteUser</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteUser__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SiteUsers</relationshipLabel>
    <relationshipName>SiteUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteUserAccount__c/SiteUserAccount__c.object-meta.xml
<CustomObject>
    <label>SiteUserAccount</label>
    <nameField>
        <label>SiteUserAccount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUserAccounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SiteUserAccountBO.cls
public class SiteUserAccountBO {

    private static final SiteUserAccountBO instance = new SiteUserAccountBO();    
    private SiteUserAccountBO(){}
    
    public static SiteUserAccountBO getInstance() {
        return instance;
    }

    /*
    public void executeProcessingUser( List<SiteUserAccount__c> objToProcessing ) {
        List<Id> userIds = new List<Id>();
        List<SiteUser__c> users = new List<SiteUser__c>();
        
        Map<String,SiteUser__c > mapOppItem = new Map<String,SiteUser__c >();
        
        for( SiteUserAccount__c obj : objToProcessing ) {            
            userIds.add(obj.SiteUser__c);            
        }
        for(SiteUser__c su : [Select Id From SiteUser__c where Id in:userIds]){
            mapOppItem.put(su.Id, su);
        }
        
        for(SiteUserAccount__c s : objToProcessing){        
            if(mapOppItem.containsKey(s.SiteUser__c)){    
                mapOppItem.get(s.SiteUser__c).Account__c = s.Account__c;
            }
        }
                    
        update mapOppItem.values();
    } */
         
}