force-app/main/default/objects/Inventory_Status__c/Inventory_Status__c.object-meta.xml
<CustomObject>
    <label>Inventory Status</label>
    <nameField>
        <label>Inventory Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Status__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Inventory Status</relationshipLabel>
    <relationshipName>Inventory_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Inventory_Status__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Status__c</fullName>
    <label>Inventory Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Seed_Type__c.field-meta.xml
<CustomField>
    <fullName>Seed_Type__c</fullName>
    <label>Seed Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Parent Seed</fullName>
            </value>
            <value>
                <fullName>Test Seed</fullName>
            </value>
            <value>
                <fullName>Wholesale Seed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Centro_de_despacho__c.field-meta.xml
<CustomField>
    <fullName>Centro_de_despacho__c</fullName>
    <label>Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>E001 - B&amp;B - CHAMPAIGN</fullName>
            </value>
            <value>
                <fullName>E002 - B&amp;B - GIBSON CITY</fullName>
            </value>
            <value>
                <fullName>E003 - B&amp;B - JONESBORO</fullName>
            </value>
            <value>
                <fullName>E004 – B&amp;B - PRO AG EARLY</fullName>
            </value>
            <value>
                <fullName>E004 – B&amp;B - PRO AG LATE</fullName>
            </value>
            <value>
                <fullName>U001 - GDM - CHAMPAIGN</fullName>
            </value>
            <value>
                <fullName>U002 - GDM - GIBSON CITY</fullName>
            </value>
            <value>
                <fullName>U003 - GDM - JONESBORO</fullName>
            </value>
            <value>
                <fullName>U004 - GDM - PRO AG EARLY</fullName>
            </value>
            <value>
                <fullName>U004 - GDM - PRO AG LATE</fullName>
            </value>
            <value>
                <fullName>U005 - GDM - HUTCHINSON</fullName>
            </value>
            <value>
                <fullName>U006 - GDM - DES MOINES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Inventory_Status__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Status__c</fullName>
    <label>Inventory Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Centro_de_despacho__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEVE-DEVELOPMENT</fullName>
            </value>
            <value>
                <fullName>COME-COMERCIAL</fullName>
            </value>
            <value>
                <fullName>PROD-PRODUCTION</fullName>
            </value>
            <value>
                <fullName>RESE-RESEARCH</fullName>
            </value>
            <value>
                <fullName>ADM -ADMINISTRATION</fullName>
            </value>
            <value>
                <fullName>W001-CHAMPAIGN WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>W001-GDM - HUTCHINSON</fullName>
            </value>
            <value>
                <fullName>W001-GDM - DES MOINES</fullName>
            </value>
            <value>
                <fullName>W001-GIBSON CITY WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>W001-JONESBORO WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>W001-PRO AG WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>T001-KAUFFMAN</fullName>
            </value>
            <value>
                <fullName>T002-STRATTON SEED-AR</fullName>
            </value>
            <value>
                <fullName>T003-SGD</fullName>
            </value>
            <value>
                <fullName>T004-PLANTATION SEED</fullName>
            </value>
            <value>
                <fullName>T005-GENERATION FARMS</fullName>
            </value>
            <value>
                <fullName>T006-JMR FARMS</fullName>
            </value>
            <value>
                <fullName>T007-STRATTON - ANNISTON</fullName>
            </value>
            <value>
                <fullName>T001-PRO AG CHB (ARG)</fullName>
            </value>
            <value>
                <fullName>TC01-Shoffner Comercial</fullName>
            </value>
            <value>
                <fullName>TP01-Shoffner Production</fullName>
            </value>
            <value>
                <fullName>TC02-CRV Comercial</fullName>
            </value>
            <value>
                <fullName>TP02-CRV Production</fullName>
            </value>
            <value>
                <fullName>TC03-Burrus Seed Comercial</fullName>
            </value>
            <value>
                <fullName>TP03-Burrus Seed Production</fullName>
            </value>
            <value>
                <fullName>TC05-CPS Comercial</fullName>
            </value>
            <value>
                <fullName>TP05-CPS Production</fullName>
            </value>
            <value>
                <fullName>TC06-Remington Wal.Comercial</fullName>
            </value>
            <value>
                <fullName>TP06-Remington Wal.Production</fullName>
            </value>
            <value>
                <fullName>TC07-Stratton AR Comercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variety Name</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/Seed_Tracking__c.object-meta.xml
<CustomObject>
    <label>Seed Track</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Seed Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seed Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Seed_Tracking__c/fields/ETA_Customer__c.field-meta.xml
<CustomField>
    <fullName>ETA_Customer__c</fullName>
    <label>ETA Customer</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Opportunity_Product__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity Product</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Seed Tracks</relationshipLabel>
    <relationshipName>Seed_Tracks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Seed Tracks</relationshipLabel>
    <relationshipName>Seed_Tracks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Sale_Order__c.field-meta.xml
<CustomField>
    <fullName>Sale_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sale Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seed Tracks</relationshipLabel>
    <relationshipName>Seed_Tracks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Variety__c.field-meta.xml
<CustomField>
    <fullName>Variety__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variety</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Seed Tracks</relationshipLabel>
    <relationshipName>Seed_Tracks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <label>Variety</label>
    <nameField>
        <label>Variety Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Varieties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/relatedSeedTracksController.cls
public without sharing class relatedSeedTracksController {

    @AuraEnabled
    public static List<TrackWrapper> getRelatedSeedTracks (Id inventoryStatusId) {
        Inventory_Status__c targetStatus = [SELECT Id, Opportunity_Product__c,
                                                Opportunity_Product__r.Product2.Variedade__c, Opportunity_Product__r.Centro_de_despacho__c,
                                                Opportunity_Product__r.Opportunity.Marca__c, Opportunity_Product__r.Opportunity.Safra__c,
                                                Opportunity_Product__r.Opportunity.Pricebook2Id, Opportunity_Product__r.Opportunity.Seed_Type__c
                                                FROM Inventory_Status__c WHERE Id = :inventoryStatusId];
        
        String type;
        if(targetstatus.Opportunity_Product__r.Opportunity.Seed_Type__c == 'Parent Seed') {
            type = '%PARENT SEED%';
        }
        else if(targetstatus.Opportunity_Product__r.Opportunity.Seed_Type__c == 'Parent Seed') {
            type = '%TEST SEED%';
        }
        else if(targetstatus.Opportunity_Product__r.Opportunity.Seed_Type__c == 'Wholesale Seed') {
            type = '%WHOLESALE SEED%';
        }

        List<Seed_Tracking__c> tracks = [SELECT Id, Product__c, Sale_Order__r.Marca__c, Variety__r.Name,
                                                Sale_Order__r.Safra__c, Sale_Order__r.Pricebook2Id,
                                                Warehouse__c, Name, Sale_Order__r.Name, Sale_Order__c, Status__c,
                                                ETA_Customer__c
                                        FROM Seed_Tracking__c 
                                        WHERE Variety__c = :targetStatus.Opportunity_Product__r.Product2.Variedade__c 
                                        AND Warehouse__c = :targetStatus.Opportunity_Product__r.Centro_de_despacho__c
                                        AND Sale_Order__r.Marca__c = :targetStatus.Opportunity_Product__r.Opportunity.Marca__c
                                        AND Sale_Order__r.Safra__c = :targetStatus.Opportunity_Product__r.Opportunity.Safra__c
                                        AND Sale_Order__r.Pricebook2Id = :targetStatus.Opportunity_Product__r.Opportunity.Pricebook2Id
                                        AND Sale_Order__r.Type LIKE :type
                                        ];

        List<TrackWrapper> wrappers = new List<TrackWrapper>();
        for(Seed_Tracking__c st : tracks) {
            TrackWrapper wr = new TrackWrapper();
            wr.name = st.Name;
            wr.id = st.Id;
            wr.productName = st.Variety__r.Name;
            wr.brand = st.Sale_Order__r.Marca__c;
            wr.season = st.Sale_Order__r.Safra__c;
            wr.warehouse = st.Warehouse__c;
            wr.saleOrderId = st.Sale_Order__c;
            wr.saleOrderName = st.Sale_Order__r.Name;
            wr.status = st.Status__c;
            wr.customerETA = st.ETA_Customer__c;
            wrappers.add(wr);
        }
        return wrappers;
    }


    public class TrackWrapper {
        @AuraEnabled
        public String name;
        @AuraEnabled
        public String id;
        @AuraEnabled
        public String productName;
        @AuraEnabled
        public String brand;
        @AuraEnabled
        public String season;
        @AuraEnabled
        public String warehouse;
        @AuraEnabled
        public String saleOrderId;
        @AuraEnabled
        public String saleOrderName;
        @AuraEnabled
        public String status;
        @AuraEnabled
        public String customerETA;
    }
}