force-app/main/default/objects/Item_del_Contrato__c/Item_del_Contrato__c.object-meta.xml
<CustomObject>
    <description>Addendum Variety item</description>
    <label>Schedule A Variety</label>
    <nameField>
        <label>Schedule A Variety</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules A Variety</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_del_Contrato__c/fields/Exclusive__c.field-meta.xml
<CustomField>
    <fullName>Exclusive__c</fullName>
    <label>Exclusive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YES</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_del_Contrato__c/fields/Variety_Id__c.field-meta.xml
<CustomField>
    <fullName>Variety_Id__c</fullName>
    <formula>Cultivar__r.Variedade__r.Id_Largo__c</formula>
    <label>Variety Id</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <label>Variety</label>
    <nameField>
        <label>Variety Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Varieties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Variedad__c/fields/Exclusive_Variety__c.field-meta.xml
<CustomField>
    <fullName>Exclusive_Variety__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclusive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Variedad__c/fields/Variety_Id__c.field-meta.xml
<CustomField>
    <fullName>Variety_Id__c</fullName>
    <label>Variety Id</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ScheduleAVarietyTriggerUtils.cls
public class ScheduleAVarietyTriggerUtils {
	public static void updateExclusiveVariety(
		Map<Id, Item_del_Contrato__c> newSchedules,
		Map<Id, Item_del_Contrato__c> oldSchedules
	) {
		List<Variedad__c> varieties = new List<Variedad__c>();
		Set<Id> varietiesIds = new Set<Id>();
		Set<Id> productsIds = new Set<Id>();
		Map<String, Item_del_Contrato__c> scheduleByVariety = new Map<String, Item_del_Contrato__c>();
		for (Item_del_Contrato__c newSchedule : newSchedules.values()) {
			if (
				(oldSchedules != null &&
				oldSchedules.containsKey(newSchedule.Id) &&
				oldSchedules.get(newSchedule.Id).Exclusive__c != newSchedule.Exclusive__c) || oldSchedules == null
			) {
				varietiesIds.add(newSchedule.Variety_Id__c);
				scheduleByVariety.put(newSchedule.Variety_Id__c, newSchedule);
			}
		}
		for (Variedad__c var : [SELECT Id, Exclusive_Variety__c FROM Variedad__c WHERE Id IN :varietiesIds]) {
			Boolean isExclusive = scheduleByVariety.get(var.Id).Exclusive__c == 'YES' ? true : false;
			if (isExclusive != var.Exclusive_Variety__c) {
				var.Exclusive_Variety__c = isExclusive;
				varieties.add(var);
			}
		}
		if (varieties.size() > 0) {
			update varieties;
		}
	}
}