force-app/main/default/objects/Product_Price_Change__c/Product_Price_Change__c.object-meta.xml
<CustomObject>
    <description>This objects aims to update products prices through the Salesforce import functionality.</description>
    <label>Product Price Change</label>
    <nameField>
        <displayFormat>Product-{0000}</displayFormat>
        <label>Product Price Change Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Price Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Price_Change__c/fields/Modified_Date__c.field-meta.xml
<CustomField>
    <fullName>Modified_Date__c</fullName>
    <description>Date when the price was modified</description>
    <label>Modified Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product_Price_Change__c/fields/New_price__c.field-meta.xml
<CustomField>
    <fullName>New_price__c</fullName>
    <label>New Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Price_Change__c/fields/Old_Price__c.field-meta.xml
<CustomField>
    <fullName>Old_Price__c</fullName>
    <label>Old Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Price_Change__c/fields/Pricebook__c.field-meta.xml
<CustomField>
    <fullName>Pricebook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pricebook where the product will be modified</description>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Products Price Changes</relationshipLabel>
    <relationshipName>Products_Price_Changes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Price_Change__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Price Changes</relationshipLabel>
    <relationshipName>Products_Price_Changes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ProductPriceChangeTriggerUtils.cls
public class ProductPriceChangeTriggerUtils {
	public static void handlePriceChanges(List<Product_Price_Change__c> priceChanges) {
		Set<Id> productsIds = new Set<Id>();
		List<PricebookEntry> entriesToUpdate = new List<PricebookEntry>();
		Map<String, Product_Price_Change__c> priceChangeByKey = new Map<String, Product_Price_Change__c>();
		Map<Id, Map<Id, Decimal>> pricesByPricebookAndProduct = new Map<Id, Map<Id, Decimal>>();
		for (Product_Price_Change__c priceChange : priceChanges) {
			priceChange.Modified_Date__c = Date.today();
			if (!pricesByPricebookAndProduct.containsKey(priceChange.Pricebook__c)) {
				pricesByPricebookAndProduct.put(
					priceChange.Pricebook__c,
					new Map<Id, Decimal>{ priceChange.Product__c => priceChange.New_price__c }
				);
			}
			String key = '' + priceChange.Product__c + priceChange.Pricebook__c;
			priceChangeByKey.put(key, priceChange);
			pricesByPricebookAndProduct.get(priceChange.Pricebook__c).put(priceChange.Product__c, priceChange.New_price__c);
			productsIds.add(priceChange.Product__c);
		}
		for (PricebookEntry entry : [
			SELECT Id, Pricebook2Id, UnitPrice, Product2Id, UseStandardPrice
			FROM PricebookEntry
			WHERE Pricebook2Id IN :pricesByPricebookAndProduct.keySet() AND Product2Id IN :productsIds
		]) {
			if (
				pricesByPricebookAndProduct.containsKey(entry.Pricebook2Id) &&
				pricesByPricebookAndProduct.get(entry.Pricebook2Id).containsKey(entry.Product2Id)
			) {
				entry.UseStandardPrice = false;
				String key = '' + entry.Product2Id + entry.Pricebook2Id;
				Decimal newPrice = pricesByPricebookAndProduct.get(entry.Pricebook2Id).get(entry.Product2Id);
				Decimal oldPrice = entry.UnitPrice;
				if (newPrice != oldPrice) {
					entry.UnitPrice = newPrice;
					entriesToUpdate.add(entry);
				}
				priceChangeByKey.get(key).Old_Price__c = oldPrice;
			}
		}
		if (entriesToUpdate.size() > 0) {
			update entriesToUpdate;
		}
	}
}