force-app/main/default/objects/Plot_Location__c/Plot_Location__c.object-meta.xml
<CustomObject>
    <label>Plot Location</label>
    <nameField>
        <label>Plot Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plot Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot_Location__c/fields/Plot_Location_Region__c.field-meta.xml
<CustomField>
    <fullName>Plot_Location_Region__c</fullName>
    <formula>Location__r.County__r.Ag_District__r.Macroregion__r.Name</formula>
    <label>Plot Location Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plot_Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>This will impact the locations that &quot;Commercial Accounts&quot; can view. Hidden = No. Public = Yes.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SiteNotification__c/SiteNotification__c.object-meta.xml
<CustomObject>
    <label>SiteNotification</label>
    <nameField>
        <label>SiteNotification Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteNotifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteNotification__c/fields/Brand_GDM__c.field-meta.xml
<CustomField>
    <fullName>Brand_GDM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Brand GDM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteNotification__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bean Blog Post</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>GDM Explore Harvest Visit Cancel</fullName>
            </value>
            <value>
                <fullName>GDM Explore Invitation Answer</fullName>
            </value>
            <value>
                <fullName>GDM Explore Invitation Cancelled</fullName>
            </value>
            <value>
                <fullName>GDM Explore Invitation Created</fullName>
            </value>
            <value>
                <fullName>GDM Explore Invitation Rescheduled</fullName>
            </value>
            <value>
                <fullName>GDM Explore New User Approval Request</fullName>
            </value>
            <value>
                <fullName>GDM Explore Note Sharing</fullName>
            </value>
            <value>
                <fullName>GDM Explore Visit</fullName>
            </value>
            <value>
                <fullName>GDM Explore Visit Canceled Harvest</fullName>
            </value>
            <value>
                <fullName>GDM Explore Visit Irrigation Off</fullName>
            </value>
            <value>
                <fullName>GDM Explore Visit Irrigation On</fullName>
            </value>
            <value>
                <fullName>GDM Explore Visit Reminder</fullName>
            </value>
            <value>
                <fullName>Plot Location Harvest</fullName>
            </value>
            <value>
                <fullName>Plot Location Irrigation</fullName>
            </value>
            <value>
                <fullName>Product Information</fullName>
            </value>
            <value>
                <fullName>Product Recommendation</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SiteNotification__c/fields/Plot_Location__c.field-meta.xml
<CustomField>
    <fullName>Plot_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot Location</label>
    <referenceTo>Plot_Location__c</referenceTo>
    <relationshipLabel>SiteNotifications</relationshipLabel>
    <relationshipName>SiteNotifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteNotification__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>SiteNotifications</relationshipLabel>
    <relationshipName>SiteNotifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteNotificationRecipient__c/SiteNotificationRecipient__c.object-meta.xml
<CustomObject>
    <label>SiteNotificationRecipient</label>
    <nameField>
        <displayFormat>NR{00000000}</displayFormat>
        <label>Recipient Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SiteNotificationRecipients</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteNotificationRecipient__c/fields/SiteNotification__c.field-meta.xml
<CustomField>
    <fullName>SiteNotification__c</fullName>
    <label>SiteNotification</label>
    <referenceTo>SiteNotification__c</referenceTo>
    <relationshipLabel>SiteNotificationRecipients</relationshipLabel>
    <relationshipName>SiteNotificationRecipients</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SiteNotificationRecipient__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>SiteNotificationRecipients</relationshipLabel>
    <relationshipName>SiteNotificationRecipients</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteNotificationRecipient__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unread</fullName>
            </value>
            <value>
                <fullName>Read</fullName>
            </value>
            <value>
                <fullName>Seen</fullName>
            </value>
            <value>
                <fullName>Dismissed</fullName>
            </value>
            <value>
                <fullName>Unseen</fullName>
                <default>true</default>
                <label>Unseen</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de SiteUser</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteUser__c/fields/Admin__c.field-meta.xml
<CustomField>
    <fullName>Admin__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Admin</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Brand_GDM__c.field-meta.xml
<CustomField>
    <fullName>Brand_GDM__c</fullName>
    <defaultValue>true</defaultValue>
    <label>View Brand GDM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/New_Siteuser_Request_Approver__c.field-meta.xml
<CustomField>
    <fullName>New_Siteuser_Request_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>New Siteuser Request Approver</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>SiteUsers</relationshipLabel>
    <relationshipName>SiteUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Notification_Blog_Post_Regions__c.field-meta.xml
<CustomField>
    <fullName>Notification_Blog_Post_Regions__c</fullName>
    <label>Notification - Blog Post Regions</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>East Coast</fullName>
            </value>
            <value>
                <fullName>Mid South</fullName>
            </value>
            <value>
                <fullName>Southern Cornbelt</fullName>
            </value>
            <value>
                <fullName>West</fullName>
            </value>
            <value>
                <fullName>Northern Cornbelt</fullName>
            </value>
            <value>
                <fullName>Mindakca</fullName>
            </value>
            <value>
                <fullName>Central Cornbelt</fullName>
            </value>
            <value>
                <fullName>Eastern Cornbelt</fullName>
            </value>
            <value>
                <fullName>Great Lakes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Notification_Invitation_Response__c.field-meta.xml
<CustomField>
    <fullName>Notification_Invitation_Response__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Notification - Invitation Response</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Notification_Visit__c.field-meta.xml
<CustomField>
    <fullName>Notification_Visit__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Notification - Visit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Notification_Visit_Cancellation__c.field-meta.xml
<CustomField>
    <fullName>Notification_Visit_Cancellation__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Notification - Visit Cancellation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Notification_Visit_Invitation__c.field-meta.xml
<CustomField>
    <fullName>Notification_Visit_Invitation__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Notification - Visit Invitation</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Notification_Visit_Reminder__c.field-meta.xml
<CustomField>
    <fullName>Notification_Visit_Reminder__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Notification - Visit Reminder</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SiteNotificationBO.cls
public class SiteNotificationBO {

    private static final SiteNotificationBO instance = new SiteNotificationBO();    
    private SiteNotificationBO(){}
    
    public static SiteNotificationBO getInstance() {
        return instance;
    }
    
    public void executePushingNotification(List<SiteNotification__c> objToProcessing) {
            
        List<SiteNotificationRecipient__c> recs = new List<SiteNotificationRecipient__c>();
        List<SiteUser__c> users = new List<SiteUser__c>();
                
        for(SiteNotification__c n : objToProcessing )
        {
            if(n.Category__c == 'Bean Blog Post')
                users = queryUsersBeanBlog(n);
            else if(n.Category__c == 'GDM Explore Visit Reminder')
                users = queryUsersVisitInvitationReminder(n);     
            else if(n.Category__c == 'GDM Explore Invitation Created')
                users = queryUsersInvitation(n);
            else if(n.Category__c == 'GDM Explore Invitation Answer')
                users = queryUsersInvitation(n);
            else if(n.Category__c == 'GDM Explore Visit Canceled Harvest')
                users = queryUsersVisits(n); 
            else if(n.Category__c == 'GDM Explore New User Approval Request')
                users = queryUsersRequestApproval(n);

            for(SiteUser__c u : users){
                SiteNotificationRecipient__c r = new SiteNotificationRecipient__c();
                r.SiteNotification__c = n.Id;
                r.SiteUser__c = u.Id;
                r.Status__c = 'Unseen';
                recs.add(r);
            }
        }    
        insert recs;    
    }
    
    public List<SiteUser__c> queryUsersBeanBlog( SiteNotification__c n) {
        String fn1; String filters=''; String region = '';

        
        // user status 
        //filters = 'and Status__c = \'Approved\'' + filters;
        
        //user brand accesses
        fn1 = 'Brand_GDM__c = true ' + 'and Status__c = \'Approved\''; 
    
        // user blog notifications ON per Region
        if(n.Plot_Location__c!=null && n.Topic__c != 'PRODUCTION'){    
            region = n.Plot_Location__r.Plot_Location_Region__c;        
            if(region!='')
                fn1 = fn1 + ' and Notification_Blog_Post_Regions__c includes (\'' + region + '\')';
        }
        
        System.debug('JERE:::NOTIF ' + fn1);        
        
        List<SiteUser__c> users = Database.query(aSiteUtils.queryFromSObject(SiteUser__c.SObjectType,null) + ' where ' + fn1 + ' Order By Name');
        return users;
    }
    
    public List<SiteUser__c> queryUsersRequestApproval( SiteNotification__c n) {
        String fn1; String filters=''; String region = '';
        
        // approver user id 
        filters = 'Id = \'' + n.SiteUser__r.New_Siteuser_Request_Approver__c + '\'';
        
        fn1 = filters;
        
        System.debug('JERE:::' + fn1);        
        
        List<SiteUser__c> users = Database.query(aSiteUtils.queryFromSObject(SiteUser__c.SObjectType,null) + ' where ' + fn1 + ' Order By Name');
        return users;        
    }
    
    public List<SiteUser__c> queryUsersVisitInvitationReminder( SiteNotification__c n) {
        String fn1; String filters=''; String region = '';
        
        // user status 
        filters = 'Status__c = \'Approved\' and Id = \'' + n.SiteUser__c + '\'';
        
        //user blog notifications ON
        fn1 = filters + ' and Notification_Visit_Reminder__c = true';
        
        System.debug('JERE:::' + fn1);        
        
        List<SiteUser__c> users = Database.query(aSiteUtils.queryFromSObject(SiteUser__c.SObjectType,null) + ' where ' + fn1 + ' Order By Name');
        return users;        
    }
 
    public List<SiteUser__c> queryUsersVisits( SiteNotification__c n) {
        String fn1; String filters=''; String region = '';
        
        // user status 
        filters = 'Status__c = \'Approved\' and Id = \'' + n.SiteUser__c + '\'';
        
        //user blog notifications ON
        if(n.Category__c=='GDM Explore Visit Canceled Harvest')
            fn1 = filters + ' and Notification_Visit_Cancellation__c = true';
            
        //else if(n.Category__c=='GDM Explore Invitation Answer')
        //    fn1 = filters + ' and Notification_Invitation_Response__c = true';
            
        System.debug('JERE:::' + fn1);        
        
        List<SiteUser__c> users = Database.query(aSiteUtils.queryFromSObject(SiteUser__c.SObjectType,null) + ' where ' + fn1 + ' Order By Name');
        return users;        
    }
       
    public List<SiteUser__c> queryUsersInvitation( SiteNotification__c n) {
        String fn1; String filters=''; String region = '';
        
        // user status 
        filters = 'Status__c = \'Approved\' and Id = \'' + n.SiteUser__c + '\'';
        
        //user blog notifications ON
        if(n.Category__c=='GDM Explore Invitation Created')
            fn1 = filters + ' and Notification_Visit_Invitation__c = true';
        else if(n.Category__c=='GDM Explore Invitation Answer')
            fn1 = filters + ' and Notification_Invitation_Response__c = true';
        
        System.debug('JERE:::' + fn1);        
        
        List<SiteUser__c> users = Database.query(aSiteUtils.queryFromSObject(SiteUser__c.SObjectType,null) + ' where ' + fn1 + ' Order By Name');
        return users;        
    }
    
    public List<SiteUser__c> queryUsersHarvest( SiteNotification__c n) {
        String fn1; String filters=''; String region = '';
        
        // user status 
        filters = 'Status__c = \'Approved\'';
        
        //user blog notifications ON
        fn1 = filters + ' and Admin__c = true and Notification_Visit__c = true';
        
        System.debug('JERE:::' + fn1);        
        
        List<SiteUser__c> users = Database.query(aSiteUtils.queryFromSObject(SiteUser__c.SObjectType,null) + ' where ' + fn1 + ' Order By Name');
        return users;        
    }
    
}