force-app/main/default/objects/Pricebook2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PARENT SEED</fullName>
            </value>
            <value>
                <fullName>WHOLESALE SEED</fullName>
            </value>
            <value>
                <fullName>TRADEMARK</fullName>
            </value>
            <value>
                <fullName>PORTAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product_Price_Change__c/Product_Price_Change__c.object-meta.xml
<CustomObject>
    <description>This objects aims to update products prices through the Salesforce import functionality.</description>
    <label>Product Price Change</label>
    <nameField>
        <displayFormat>Product-{0000}</displayFormat>
        <label>Product Price Change Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Products Price Changes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Product_Price_Change__c/fields/New_price__c.field-meta.xml
<CustomField>
    <fullName>New_price__c</fullName>
    <label>New Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product_Price_Change__c/fields/Pricebook__c.field-meta.xml
<CustomField>
    <fullName>Pricebook__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Pricebook where the product will be modified</description>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Products Price Changes</relationshipLabel>
    <relationshipName>Products_Price_Changes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product_Price_Change__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products Price Changes</relationshipLabel>
    <relationshipName>Products_Price_Changes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <label>Variety</label>
    <nameField>
        <label>Variety Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Varieties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/ProductPriceChangeTriggerTest.cls
@isTest
private class ProductPriceChangeTriggerTest {
	@TestSetup
	static void makeData() {
		Variedad__c variety = Build.aVariedad().withName('Variety').build();
		insert variety;
		List<Product2> products = new List<Product2>();

		Pricebook2 pricebook = Build.aPricebook2().withBrand('GDM').withName('Pricebook GDM').withIsActive(true).build();
		pricebook.Type__c = 'PARENT SEED';
		insert pricebook;
		Pricebook2 pricebookWholesale = Build.aPricebook2()
			.withBrand('GDM')
			.withName('DONMARIO - WHOLESALE PriceList')
			.withIsActive(true)
			.build();
		pricebookWholesale.Type__c = 'WHOLESALE SEED';
		insert pricebookWholesale;
		List<PricebookEntry> entries = new List<PricebookEntry>();
		for (Integer i = 0; i < 10; i++) {
			Product2 aProduct = Build.aProduct2()
				.withName('Product ' + i)
				.withIsActive(true)
				.withVariedade(variety)
				.withUNIDADE('BAG 140K')
				.build();
			products.add(aProduct);
		}
		insert products;
		for (Product2 theProd : products) {
			PricebookEntry pbeOneStndr = Build.aPricebookEntry()
				.withIsActive(true)
				.withPricebook2Id(Test.getStandardPricebookId())
				.withProduct2Id(theProd)
				.withUnitPrice(1)
				.build();
			entries.add(pbeOneStndr);
			PricebookEntry pbeOneGdm = Build.aPricebookEntry()
				.withIsActive(true)
				.withPricebook2Id(pricebook)
				.withProduct2Id(theProd)
				.withUnitPrice(1)
				.build();
			entries.add(pbeOneGdm);
			PricebookEntry pbWholesale = Build.aPricebookEntry()
				.withIsActive(true)
				.withPricebook2Id(pricebookWholesale)
				.withProduct2Id(theProd)
				.withUnitPrice(1)
				.build();
			entries.add(pbWholesale);
		}
		insert entries;
	}

	@isTest
	public static void testChangePriceShouldModifyPriceobookEntry() {
		Id wholesaleId = [SELECT Id FROM Pricebook2 WHERE Type__c = 'WHOLESALE SEED' LIMIT 1].Id;
		Id parentId = [SELECT Id FROM Pricebook2 WHERE Type__c = 'PARENT SEED' LIMIT 1].Id;
		List<Product_Price_Change__c> pricesChanges = new List<Product_Price_Change__c>();
		for (Product2 aProduct : [SELECT Id FROM Product2]) {
			pricesChanges.add(
				new Product_Price_Change__c(Product__c = aProduct.Id, Pricebook__c = wholesaleId, New_Price__c = 3)
			);
		}
          Test.startTest();
          insert pricesChanges;
          Test.stopTest();

          for(PricebookEntry entry : [SELECT Id, UnitPrice FROM PricebookEntry WHERE Pricebook2Id =: parentId]){
               System.assertEquals(1, entry.UnitPrice);
          }

          for(PricebookEntry entryModified : [SELECT Id, UnitPrice FROM PricebookEntry WHERE Pricebook2Id =: wholesaleId]){
               System.assertEquals(3, entryModified.UnitPrice);
          }

	}
}