force-app/main/default/objects/Explore_Plot_Cell__c/Explore_Plot_Cell__c.object-meta.xml
<CustomObject>
    <label>Explore Plot Cell</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Explore Plot Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Explore Plot Cells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Explore_Plot_Cell__c/fields/Explore_Plot__c.field-meta.xml
<CustomField>
    <fullName>Explore_Plot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Plot Location</description>
    <label>Explore Plot</label>
    <referenceTo>Plot_Location__c</referenceTo>
    <relationshipLabel>Explore Plot Cells</relationshipLabel>
    <relationshipName>Explore_Plot_Cells</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Explore_Plot_Cell__c/fields/Variety__c.field-meta.xml
<CustomField>
    <fullName>Variety__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Product</description>
    <label>Variety</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Explore Plot Cells</relationshipLabel>
    <relationshipName>Explore_Plot_Cells</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Explore_Plot_Note_Score__c/Explore_Plot_Note_Score__c.object-meta.xml
<CustomObject>
    <label>Explore Plot Note Score</label>
    <nameField>
        <label>Explore Plot Note Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Explore Plot Note Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Explore_Plot_Note_Score__c/fields/Explore_Rating__c.field-meta.xml
<CustomField>
    <fullName>Explore_Rating__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Explore Rating</label>
    <referenceTo>Explore_Rating__c</referenceTo>
    <relationshipLabel>Explore Plot Note Scores</relationshipLabel>
    <relationshipName>Explore_Plot_Note_Scores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Explore_Plot_Note_Score__c/fields/Plot_Note__c.field-meta.xml
<CustomField>
    <fullName>Plot_Note__c</fullName>
    <label>Plot Note</label>
    <referenceTo>Plot_Saved_Soy__c</referenceTo>
    <relationshipLabel>Explore Plot Note Scores</relationshipLabel>
    <relationshipName>Explore_Plot_Note_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Explore_Plot_Note_Score__c/fields/Score_Value__c.field-meta.xml
<CustomField>
    <fullName>Score_Value__c</fullName>
    <label>Score Value</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Explore_Rating__c/Explore_Rating__c.object-meta.xml
<CustomObject>
    <description>Explore Ratings will be the ratings that are used within GDM Explore. This object allows us to build customized ratings, related to a Ratings Scale, and assign who is able to see each Customized Rating within GDM Explore.</description>
    <label>Explore Rating</label>
    <nameField>
        <label>Explore Rating Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Explore Ratings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Plot_Note__c/Mass_Plot_Note__c.object-meta.xml
<CustomObject>
    <label>Mass Plot Note</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Mass Plot Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Plot Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Plot_Note__c/fields/Explore_Rating__c.field-meta.xml
<CustomField>
    <fullName>Explore_Rating__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Explore Rating</label>
    <referenceTo>Explore_Rating__c</referenceTo>
    <relationshipLabel>Mass Plot Notes</relationshipLabel>
    <relationshipName>Mass_Plot_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mass_Plot_Note__c/fields/Plot_Location__c.field-meta.xml
<CustomField>
    <fullName>Plot_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot Location</label>
    <referenceTo>Plot_Location__c</referenceTo>
    <relationshipLabel>Mass Plot Notes</relationshipLabel>
    <relationshipName>Mass_Plot_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mass_Plot_Note__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>Mass Plot Notes</relationshipLabel>
    <relationshipName>Mass_Plot_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mass_Plot_Note__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plot_Location__c/Plot_Location__c.object-meta.xml
<CustomObject>
    <label>Plot Location</label>
    <nameField>
        <label>Plot Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plot Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot_Saved_Soy__c/Plot_Saved_Soy__c.object-meta.xml
<CustomObject>
    <label>Plot Note</label>
    <nameField>
        <displayFormat>SS{0000000}</displayFormat>
        <label>Plot Note Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plot Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot_Saved_Soy__c/fields/Created_Date__c.field-meta.xml
<CustomField>
    <fullName>Created_Date__c</fullName>
    <label>In App Created Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Plot_Saved_Soy__c/fields/Mass_Plot_Note__c.field-meta.xml
<CustomField>
    <fullName>Mass_Plot_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mass Plot Note</label>
    <referenceTo>Mass_Plot_Note__c</referenceTo>
    <relationshipLabel>Plot Notes</relationshipLabel>
    <relationshipName>Plot_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plot_Saved_Soy__c/fields/Plot_Cell__c.field-meta.xml
<CustomField>
    <fullName>Plot_Cell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot Cell</label>
    <referenceTo>Explore_Plot_Cell__c</referenceTo>
    <relationshipLabel>Plot Notes</relationshipLabel>
    <relationshipName>Plot_Saved_Soys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plot_Saved_Soy__c/fields/Plot_Location__c.field-meta.xml
<CustomField>
    <fullName>Plot_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot Location</label>
    <referenceTo>Plot_Location__c</referenceTo>
    <relationshipName>Plot_Saved_Soys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plot_Saved_Soy__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipName>Plot_Saved_Soys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plot_Saved_Soy__c/fields/Variety__c.field-meta.xml
<CustomField>
    <fullName>Variety__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variety</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipName>Plot_Saved_Soys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de SiteUser</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/PlotNoteExecutionBO.cls
public class PlotNoteExecutionBO {

    private static final PlotNoteExecutionBO instance = new PlotNoteExecutionBO();    
    private PlotNoteExecutionBO(){}
    
    public static PlotNoteExecutionBO getInstance() {
        return instance;
    }
    
    public void executeStartNoteMassUpdate(List<Explore_Plot_Note_Score__c> objToProcessing) {
        
        List<Explore_Plot_Note_Score__c> scores = new List<Explore_Plot_Note_Score__c>();
    
        for(Explore_Plot_Note_Score__c score : objToProcessing )   //Detect a note with FILL not N/A
        {   
            if(score.Explore_Rating__r.Name=='FILL' && score.Score_Value__c!='N/A'){

                Plot_Saved_soy__c note = score.Plot_Note__r; 
                Explore_Plot_Cell__c cell = note.Plot_Cell__r; 
                Plot_location__c loc = cell.Explore_Plot__r;
                SiteUser__c user = note.SiteUser__r;
                scores = [Select Id, Explore_Rating__r.Name, Explore_Rating__c From Explore_Plot_Note_Score__c where Id != :score.Id and Plot_Note__c = :note.Id];
    
                List<Mass_Plot_Note__c> masses = new List<Mass_Plot_Note__c>();
                
                for(Explore_Plot_Note_Score__c s : scores){
                    if(s.Explore_Rating__r.Name=='FILL')
                        continue;
                    Mass_Plot_Note__c mass = new Mass_Plot_Note__c();
                    mass.Date__c = score.Date__c;
                    mass.Explore_Rating__c = s.Explore_Rating__c;
                    mass.Plot_Location__c = loc.Id;
                    mass.SiteUser__c = user.Id;
                    mass.Value__c = score.Score_Value__c;
                    //masses.add(mass);
                    insert mass;    
                }
                //insert masses;
            }            
        }
    }
    
    public void executeNoteMassUpdate(List<Mass_Plot_Note__c> objToProcessing) {
            
        List<Explore_Plot_Cell__c> emptyCells = new List<Explore_Plot_Cell__c>();
        List<Explore_Plot_Cell__c> allCells = new List<Explore_Plot_Cell__c>();
        List<Id> noteCellsId = new List<Id>();        
        List<Plot_Saved_Soy__c> notes = new List<Plot_Saved_Soy__c>();
        List<Explore_Plot_Note_Score__c> scores = new List<Explore_Plot_Note_Score__c>();
                
        for(Mass_Plot_Note__c n : objToProcessing )
        {           
            
            noteCellsId = queryNoteCells(n);
            System.debug('JERE:::' + noteCellsId);
            
            emptyCells = queryEmptyCells(n, noteCellsId);
            System.debug('JERE:::' + emptyCells.size());
            
            for(Explore_Plot_Cell__c c : emptyCells){
                Plot_Saved_Soy__c note = new Plot_Saved_Soy__c();
                note.Plot_location__c = n.Plot_Location__c;
                note.SiteUser__c = n.SiteUser__c;
                note.Created_date__c = n.Date__c;
                note.Plot_Cell__c = c.Id;
                note.Mass_Plot_Note__c = n.Id;                    
                note.Active__c = true;            
                note.Type__c = 'NOTE';                
                note.Variety__c = c.Variety__c;
                notes.add(note);    
            }
            
            insert notes;
            
            for(Plot_Saved_Soy__c note : notes){    
                Explore_Plot_Note_Score__c score = new Explore_Plot_Note_Score__c();
                score.Explore_Rating__c = n.Explore_Rating__c;
                score.Plot_Note__c = note.Id;
                score.Score_Value__c = n.value__c;
                scores.add(score);            
            }
           
            insert scores;
            
        }    
   
    }
 
    public List<Explore_Plot_Cell__c> queryEmptyCells( Mass_Plot_Note__c n, List<Id> ids) {        
        
        List<Explore_Plot_Cell__c> cels;        
        cels = [Select Id, Name, Variety__c from Explore_Plot_Cell__c Where Explore_Plot__c = :n.Plot_location__c and Id NOT in :ids]; 

        return cels;
    }
    
    public List<Id> queryNoteCells( Mass_Plot_Note__c n) {        
        
        List<id> listaToTrue = new List<id>();

        for(Explore_Plot_Note_Score__c e : [Select Id, Name, Plot_Note__r.Plot_Cell__c from Explore_Plot_Note_Score__c where
            Plot_Note__r.SiteUser__c = :n.SiteUser__c and Score_value__c != 'N/A' and Explore_Rating__c = :n.Explore_Rating__c and Plot_Note__r.Plot_Location__c = :n.Plot_location__c and Date__c = :n.Date__c]){
            
            listaToTrue.add(e.Plot_Note__r.Plot_Cell__c);
        } 

        return listaToTrue;
    }
    
}