force-app/main/default/objects/Account/fields/CodigoSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoSAP__c</fullName>
    <label>Account Sap Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/Automatization_of_Sales_Regionalization__c.field-meta.xml
<CustomField>
    <fullName>Automatization_of_Sales_Regionalization__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox will enable the location to the Automatization of Sales Regionalization process</description>
    <label>Automatization of Sales Regionalization</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Branch Name)</relationshipLabel>
    <relationshipName>Opportunities_Branchs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Condicion_de_Pago__c.field-meta.xml
<CustomField>
    <fullName>Condicion_de_Pago__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZC05 Net 30 days from shipping date</fullName>
                <default>true</default>
                <label>Net 30 days from shipping date</label>
            </value>
            <value>
                <fullName>ZC04 Net 20 days from shipping date</fullName>
                <label>Net 20 days from shipping date</label>
            </value>
            <value>
                <fullName>ZC05 - S4 test Condition</fullName>
                <label>S4 test Condition</label>
            </value>
            <value>
                <fullName>ZC00 Due Upon Receipt</fullName>
                <label>Due Upon Receipt</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ship To)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZO13 - Export Order</fullName>
            </value>
            <value>
                <fullName>ZO14 – Local Order</fullName>
                <default>true</default>
                <label>ZO14 – Local Order - Seeds</label>
            </value>
            <value>
                <fullName>ZO15 - Local Order</fullName>
                <label>ZO15 - Local Order - Royalty</label>
            </value>
            <value>
                <fullName>Customer Goal</fullName>
            </value>
            <value>
                <fullName>Budget</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Sale.recordType-meta.xml
<RecordType>
    <fullName>Sale</fullName>
    <active>true</active>
    <businessProcess>Invoice</businessProcess>
    <label>Sale</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Centro_de_despacho__c.field-meta.xml
<CustomField>
    <fullName>Centro_de_despacho__c</fullName>
    <label>Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>E001 - B&amp;B - CHAMPAIGN</fullName>
            </value>
            <value>
                <fullName>E002 - B&amp;B - GIBSON CITY</fullName>
            </value>
            <value>
                <fullName>E003 - B&amp;B - JONESBORO</fullName>
            </value>
            <value>
                <fullName>E004 – B&amp;B - PRO AG EARLY</fullName>
            </value>
            <value>
                <fullName>E004 – B&amp;B - PRO AG LATE</fullName>
            </value>
            <value>
                <fullName>U001 - GDM - CHAMPAIGN</fullName>
            </value>
            <value>
                <fullName>U002 - GDM - GIBSON CITY</fullName>
            </value>
            <value>
                <fullName>U003 - GDM - JONESBORO</fullName>
            </value>
            <value>
                <fullName>U004 - GDM - PRO AG EARLY</fullName>
            </value>
            <value>
                <fullName>U004 - GDM - PRO AG LATE</fullName>
            </value>
            <value>
                <fullName>U005 - GDM - HUTCHINSON</fullName>
            </value>
            <value>
                <fullName>U006 - GDM - DES MOINES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Pallet_Charge__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Charge__c</fullName>
    <label>Pallet Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Variedades que pueden incluirse en el contrato de multiplicacion</description>
    <label>Variety Name DO NOT USE</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variety Name</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Localization__c/Sales_Localization__c.object-meta.xml
<CustomObject>
    <label>Sales Localization</label>
    <nameField>
        <displayFormat>L{000000}</displayFormat>
        <label>Sales Localization Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Localizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Localization__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Sales Localizations</relationshipLabel>
    <relationshipName>Sales_Localizations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Volume_Estimation__c/Sales_Volume_Estimation__c.object-meta.xml
<CustomObject>
    <label>Sales Volume Estimation</label>
    <nameField>
        <displayFormat>VE{000000}</displayFormat>
        <label>Sales Volume Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Sales Volume Estimations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Sales_Volume_Estimation__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Sales Volume Estimations</relationshipLabel>
    <relationshipName>Sales_Volume_Estimations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Sales_Volume_Estimation__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <defaultValue>&quot;21/2021&quot;</defaultValue>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <label>Variety</label>
    <nameField>
        <label>Variety Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Varieties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Variedad__c/fields/Season__c.field-meta.xml
<CustomField>
    <fullName>Season__c</fullName>
    <label>Exclusivity Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/salesRegionalizationControllerTest.cls
/**
 * @description       : Test class for the salesRegionalizationComponentController
 * @author            : Santiago Muñoz
 * @group             : 
 * @last modified on  : 04-25-2023
 * @last modified by  : Santiago Muñoz
**/
@IsTest
public with sharing class salesRegionalizationControllerTest {
    static Opportunity opp;

    static {
        List<Location__c> lList = new List<Location__c>();

        lList.add(new Location__c(Name = 'A Localization 1',Automatization_of_Sales_Regionalization__c = true));
        lList.add(new Location__c(Name = 'A Localization 2',Automatization_of_Sales_Regionalization__c = false));

        insert lList;

        Variedad__c aVariety = new Variedad__c();
        aVariety.Name = 'Test Var';
        insert aVariety;

        Account account = new Account();
        account.Name = 'AGENTE';
        account.CodigoSAP__c = '12456554';
        insert account;

        Account account2 = new Account();
        account2.Name = 'AGENTE2';
        account2.CodigoSAP__c = '124565543';
        insert account2;
        
        Product2 produto002           = new Product2();
        produto002.Name               = 'ROYALTY';
        produto002.ProductCode        = '40026418';
        produto002.isActive           = true; 
        produto002.Variedade__c = aVariety.Id;
        insert produto002;

        Product2 produto_2           = new Product2();

        produto_2.Name               = 'SEED';
        produto_2.ProductCode        = '40026418';
        produto_2.isActive           = true;
        produto_2.Variedade__c = aVariety.Id;

        insert produto_2;

        Pricebook2 price1                 = new Pricebook2();
        price1.Name                       = 'Teste';
        price1.Description                = 'Teste';
        price1.IsActive                   = true;

        insert price1;

        PricebookEntry priceBookEntry1 = new PricebookEntry();
        priceBookEntry1.Pricebook2Id = Test.getStandardPricebookId();
        priceBookEntry1.Product2Id = produto_2.id;
        priceBookEntry1.UseStandardPrice = false;
        priceBookEntry1.IsActive = true;
        priceBookEntry1.UnitPrice = 100.00;

        insert priceBookEntry1;

        opp = new Opportunity();
        opp.RecordTypeID = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sale').getRecordTypeId();
        opp.Safra__c = '23/2023';    
        opp.AccountId = account.Id;
        opp.Ship_To__c = account.Id;
        opp.Branch_name__c = account2.Id; 
        opp.Name   = 'UnitTest';
        opp.Tipo__c = 'ZPLO - Local Order';
        opp.StageName  = 'Edition'; 
        opp.CloseDate = System.today()+60;
        opp.Condicion_de_Pago__c = 'ZC05 Net 30 days from shipping date';
        opp.Type = 'Z17 - PARENT SEED';
        opp.Pricebook2Id = Test.getStandardPricebookId();

        insert opp;

        OpportunityLineItem oppli1 = new OpportunityLineItem();
        oppli1.OpportunityId = opp.id;
        oppli1.PricebookEntryId = priceBookEntry1.id;
        oppli1.UnitPrice = 1;
        oppli1.Quantity = 40;
        oppli1.Pallet_Charge__c = 10;
        oppli1.Centro_de_Despacho__c = 'UD01';

        insert oppli1;

        
        insert new Sales_Volume_Estimation__c(Account__c = account.Id, Season__c = '23/2023');
    }

    @IsTest
    public static void getLocalizationsTest() {
        List<Location__c> lList = new List<Location__c>();

        Test.startTest();
        lList = salesRegionalizationComponentController.getLocations();
        Test.stopTest();

        System.assertEquals(1, lList.size(), 'Only one location should have been retrieved');
    }

    @IsTest
    public static void getDataTest() {
        List<salesRegionalizationComponentController.SalesLocalizationWrapper> wList = new List<salesRegionalizationComponentController.SalesLocalizationWrapper>();


        Test.startTest();
        wList = salesRegionalizationComponentController.getSalesVolumeDetailData(opp.id);
        Test.stopTest();

        System.assertEquals(1, wList.size(), 'Only one wrapper should have been retrieved');
        System.assertEquals(1, wList[0].sLocalizationList.size(), 'Only one Localization should have been created');
    }

    
    @IsTest
    public static void getVolumeDataTest() {
        List<salesRegionalizationComponentController.SalesLocalizationWrapper> wList = new List<salesRegionalizationComponentController.SalesLocalizationWrapper>();

        Sales_Volume_Estimation__c sve = [SELECT Id FROM Sales_Volume_Estimation__c LIMIT 1];

        //Creates the base data to cover the test
        salesRegionalizationComponentController.getSalesVolumeDetailData(opp.id);

        Test.startTest();
        wList = salesRegionalizationComponentController.getRecordSalesVolumeDetailData(sve.id);
        Test.stopTest();

        System.assertEquals(1, wList.size(), 'Only one wrapper should have been retrieved');
        System.assertEquals(1, wList[0].sLocalizationList.size(), 'Only one Localization should have been created');
    }
    @IsTest
    public static void saveDataTest() {
        List<salesRegionalizationComponentController.SalesLocalizationWrapper> wList = new List<salesRegionalizationComponentController.SalesLocalizationWrapper>();

        wList = salesRegionalizationComponentController.getSalesVolumeDetailData(opp.id);
        wList[0].sLocalizationList[0].Percentage__c = 100;

        Test.startTest();
        String result = salesRegionalizationComponentController.saveSalesRegionalizationData(wList);
        Test.stopTest();

        Sales_Localization__c sl = [SELECT Id, Percentage__c FROM Sales_Localization__c WHERE Id = :wList[0].sLocalizationList[0].Id];

        System.assertEquals('SUCCESS', result, 'Wrong result string');
        System.assertEquals(100, sl.Percentage__c, 'Percentage should be 100%');
    }
}