force-app/main/default/objects/Account/fields/CodigoSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoSAP__c</fullName>
    <label>Account Sap Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Grupo_de_Cuentas__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Cuentas__c</fullName>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>US01 - Domestic Customers</fullName>
            </value>
            <value>
                <fullName>US02 - Foreing Customers</fullName>
                <label>US02 - Foreign Customers</label>
            </value>
            <value>
                <fullName>US03 - Ship To</fullName>
            </value>
            <value>
                <fullName>US04 - Branches</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nome_fantasia__c.field-meta.xml
<CustomField>
    <fullName>Nome_fantasia__c</fullName>
    <label>Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>Addendum to the Soybean Germplasm Aggrement.</description>
    <label>Schedule A</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Schedule A Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Licensee Account</description>
    <label>Licensee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contratos_de_Multiplicacion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24/2024</fullName>
            </value>
            <value>
                <fullName>23/2023</fullName>
            </value>
            <value>
                <fullName>22/2022</fullName>
            </value>
            <value>
                <fullName>21/2021</fullName>
            </value>
            <value>
                <fullName>20/2020</fullName>
            </value>
            <value>
                <fullName>19/2019</fullName>
            </value>
            <value>
                <fullName>18/2018</fullName>
            </value>
            <value>
                <fullName>17/2017</fullName>
            </value>
            <value>
                <fullName>16/2016</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GDM</fullName>
                <default>true</default>
                <label>GDM</label>
            </value>
            <value>
                <fullName>B&amp;B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/AnexoI.recordType-meta.xml
<RecordType>
    <fullName>AnexoI</fullName>
    <active>true</active>
    <businessProcess>Portal Reports</businessProcess>
    <label>Appendix I</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Production_Report.recordType-meta.xml
<RecordType>
    <fullName>Production_Report</fullName>
    <active>true</active>
    <businessProcess>Portal Reports</businessProcess>
    <label>Production Report</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Sales_Report.recordType-meta.xml
<RecordType>
    <fullName>Sales_Report</fullName>
    <active>true</active>
    <businessProcess>Portal Reports</businessProcess>
    <label>Sales Report</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Area__c.field-meta.xml
<CustomField>
    <fullName>Area__c</fullName>
    <label>Area Author. (Acres)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Area_Plantada__c.field-meta.xml
<CustomField>
    <fullName>Area_Plantada__c</fullName>
    <inlineHelpText>Unit: Acres</inlineHelpText>
    <label>Production Acres</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Licensee_Variety_Name__c.field-meta.xml
<CustomField>
    <fullName>Licensee_Variety_Name__c</fullName>
    <label>Licensee Variety ID</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Prev_Parent__c.field-meta.xml
<CustomField>
    <fullName>Prev_Parent__c</fullName>
    <label>Prev Parent Seed</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Prev_Supply__c.field-meta.xml
<CustomField>
    <fullName>Prev_Supply__c</fullName>
    <label>Prev Supply</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Sales_Report_Type__c.field-meta.xml
<CustomField>
    <fullName>Sales_Report_Type__c</fullName>
    <label>Item Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Forecast</fullName>
            </value>
            <value>
                <fullName>Sale</fullName>
            </value>
            <value>
                <fullName>Production</fullName>
            </value>
            <value>
                <fullName>Production Update 1</fullName>
            </value>
            <value>
                <fullName>Production Update 2</fullName>
            </value>
            <value>
                <fullName>Production Update 3</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Semente_beneficiada__c.field-meta.xml
<CustomField>
    <fullName>Semente_beneficiada__c</fullName>
    <description>Unit: 140 k Seeds Bag Production/Conditioning Reports</description>
    <inlineHelpText>Unit: 140 k Seeds Bag Production/Conditioning Reports</inlineHelpText>
    <label>Conditioned 140K Units (Supply)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Semente_comercializada__c.field-meta.xml
<CustomField>
    <fullName>Semente_comercializada__c</fullName>
    <label>Commercial Sales</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Semente_uso_propio__c.field-meta.xml
<CustomField>
    <fullName>Semente_uso_propio__c</fullName>
    <description>Units Used for Production (Parent Seeds)</description>
    <inlineHelpText>Units Used for Production (Parent Seeds)</inlineHelpText>
    <label>Units Used for Production</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Variedades que pueden incluirse en el contrato de multiplicacion</description>
    <label>Variety Name DO NOT USE</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BAG 140K</fullName>
            </value>
            <value>
                <fullName>BAG 40(140K)</fullName>
            </value>
            <value>
                <fullName>LB</fullName>
            </value>
            <value>
                <fullName>BAGS BY LBS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variety Name</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de SiteUser</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteUser__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SiteUsers</relationshipLabel>
    <relationshipName>SiteUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Cadastro_pela_primeira_vez__c.field-meta.xml
<CustomField>
    <fullName>Cadastro_pela_primeira_vez__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has login before</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUserAccount__c/SiteUserAccount__c.object-meta.xml
<CustomObject>
    <label>SiteUserAccount</label>
    <nameField>
        <label>SiteUserAccount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUserAccounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteUserSession__c/SiteUserSession__c.object-meta.xml
<CustomObject>
    <label>SiteUserSession</label>
    <nameField>
        <displayFormat>S{00000000}</displayFormat>
        <label>SiteUserSession Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SiteUserSessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteUserSession__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SiteUserSession__c/fields/Production_Season__c.field-meta.xml
<CustomField>
    <fullName>Production_Season__c</fullName>
    <label>Production Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SiteUserSession__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <label>Variety</label>
    <nameField>
        <label>Variety Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Varieties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/aSiteUSAControllerTest.cls
/**
 * Clase test de todos los controllers del sitio portal, USA especifico
 *  Jere 22.06.02 Complete unit tests
 */
@isTest
global with sharing class aSiteUSAControllerTest {
    
    @IsTest (SeeAllData=false)
    global static void testAuthManager () {        
        Account acc = new Account(Site='www.fff.com',AccountNumber='1243',Grupo_de_cuentas__c='US01 - Domestic Customers',Name='JERE', Nome_Fantasia__c = 'JRERE', CodigoSAP__c='451254'); insert acc;
        SiteUser__c su = new SiteUser__c(Email__c='jere@dm.com', Password__c='123'); insert su;
        SiteUserAccount__c suacc = new SiteUserAccount__c(SiteUser__c=su.Id,Account__c=acc.Id, Active__c=true); insert suacc;
        SiteUserSession__c susess = new SiteUserSession__c(Marca__c='GDM', Safra__c='18/2018',SiteUser__c=su.Id); insert susess;

        aSiteAuthManager.RefreshUserSession(susess.Id);
        
    }
    
    @IsTest (SeeAllData=false)
    global static void testContractController () {
        Account acc = new Account(Site='www.fff.com',AccountNumber='1243',Grupo_de_cuentas__c='US01 - Domestic Customers',Name='JERE', Nome_Fantasia__c = 'JRERE', CodigoSAP__c='451254'); insert acc;
        SiteUser__c su = new SiteUser__c(Email__c='jere@dm.com', Password__c='123'); insert su;
        SiteUserAccount__c suacc = new SiteUserAccount__c(SiteUser__c=su.Id,Account__c=acc.Id, Active__c=true); insert suacc;
        SiteUserSession__c susess = new SiteUserSession__c(Marca__c='GDM', Safra__c='18/2018',SiteUser__c=su.Id); insert susess;
        Contrato__c cont = new Contrato__c(Multiplicador__c=acc.Id, Safra__c='18/2018',Sociedad__c='GDM'); insert cont;
        
        aSiteContractController controller = new aSiteContractController();
        controller.validate();

        PageReference pageRef = Page.aSiteContracts;
        pageRef.getParameters().put('token',susess.Id);
        Test.setCurrentPageReference(pageRef);
        controller.validate();
        controller.getContracts();
        controller.setActiveContract();
        controller.getUser();
        controller.getAccount();
}

    @IsTest (SeeAllData=false)
    global static void testProfileController () {
        Account acc = new Account(Site='www.fff.com',AccountNumber='1243',Grupo_de_cuentas__c='US01 - Domestic Customers',Name='JERE', Nome_Fantasia__c = 'JRERE', CodigoSAP__c='451254'); insert acc;
        SiteUser__c su = new SiteUser__c(Email__c='jere@dm.com', Password__c='123'); insert su;
        SiteUserAccount__c suacc = new SiteUserAccount__c(SiteUser__c=su.Id,Account__c=acc.Id, Active__c=true); insert suacc;
        SiteUserSession__c susess = new SiteUserSession__c(Marca__c='GDM', Safra__c='18/2018',SiteUser__c=su.Id); insert susess;

        aSiteProfileController controller = new aSiteProfileController();
        controller.validate();

        PageReference pageRef = Page.aSiteProfile;
        pageRef.getParameters().put('token',susess.Id);
        Test.setCurrentPageReference(pageRef);
        controller.validate();

        controller.getAccounts();
        controller.accSelect=suacc.Id;
        controller.setActiveAccount();
        controller.getUser();
        
        controller.getAccounts();
        controller.editProfile();
        controller.editPassword();
        controller.editCancel();
        controller.saveProfile();
    }

    @IsTest (SeeAllData=false)
    global static void testPasswordController () {
        aSiteForgotPassController controller = new aSiteForgotPassController();
        controller.forgotPassword();

        Account acc = new Account(Site='www.fff.com',AccountNumber='1243',Grupo_de_cuentas__c='US01 - Domestic Customers',Name='JERE', Nome_Fantasia__c = 'JRERE', CodigoSAP__c='451254'); insert acc;
        SiteUser__c su = new SiteUser__c(Email__c='jere@dm.com', Password__c='123456'); insert su;
        SiteUserAccount__c suacc = new SiteUserAccount__c(SiteUser__c=su.Id,Account__c=acc.Id, Active__c=true); insert suacc;
        SiteUserSession__c susess = new SiteUserSession__c(Marca__c='GDM', Safra__c='18/2018',SiteUser__c=su.Id); insert susess;
        
        controller.username = 'test@salesforce.com';
        controller.forgotPassword();
        

        PageReference pageRef = new PageReference('/aSiteChangePass');
        pageRef.getParameters().put('token',susess.Id);
        Test.setCurrentPageReference(pageRef);
        
        aSiteChangePassController controller1 = new aSiteChangePassController();
        controller1.validate();
        controller1.ChangePassword();
        controller1.oldpassword = '123456';
        controller1.ChangePassword();
        controller1.newpassword = '123';
        controller1.ChangePassword();
        controller1.verifynewpassword = '123';
        controller1.ChangePassword();
    }
    
    @IsTest (SeeAllData=false)
    global static void testLoginController () {
        aSiteLoginController controller = new aSiteLoginController ();
        System.assertEquals(controller.login(),null);
        controller.username = 'test@salesforce.com';
        System.assertEquals(controller.login(),null);
        controller.password = '123456';                
        System.assertEquals(controller.login(),null);

        Account acc = new Account(Site='www.fff.com',AccountNumber='1243',Grupo_de_cuentas__c='US01 - Domestic Customers',Name='JERE', Nome_Fantasia__c = 'JRERE', CodigoSAP__c='451254'); insert acc;
        SiteUser__c su = new SiteUser__c(Email__c='test@salesforce.com', Password__c='123456'); insert su;
        SiteUserAccount__c suacc = new SiteUserAccount__c(SiteUser__c=su.Id,Account__c=acc.Id, Active__c=true); insert suacc;
        
        controller.login();
        su.Cadastro_pela_primeira_vez__c = true; update su;
        controller.login();
        
        controller.forwardToResetPassword();
        controller.forwardToLogin();
        
        controller.closeSession();
    }
   
    @IsTest (SeeAllData=false)
    global static void testSalesController () {
		
        aSiteSalesReportController controller = new aSiteSalesReportController ();
        controller.validate();
        
        Map<String,Id> rTypes = Opp_Utils.cargarRecordTypesOportunidades();
        Map<String,String> rTypesD = USAUtils.cargarRecordTypesOppbyDevName();
        
        Account acc = new Account(Site='www.fff.com',AccountNumber='1243',Grupo_de_cuentas__c='US01 - Domestic Customers',Name='JERE', Nome_Fantasia__c = 'JRERE', CodigoSAP__c='451254'); insert acc;
        SiteUser__c su = new SiteUser__c(Email__c='jere@dm.com', Password__c='123'); insert su;
        SiteUserAccount__c suacc = new SiteUserAccount__c(SiteUser__c=su.Id,Account__c=acc.Id, Active__c=true); insert suacc;
        SiteUserSession__c susess = new SiteUserSession__c(Marca__c='GDM', Safra__c='20/2020',SiteUser__c=su.Id); insert susess;
        
        PageReference pageRef = new PageReference('/aSiteSalesReport');
        pageRef.getParameters().put('token',susess.Id);      
        pageRef.getParameters().put('t','fi');
        Test.setCurrentPageReference(pageRef);        
        
        controller = new aSiteSalesReportController ();
        controller.validate();                
        System.assertEquals(controller.validate(),null);
        
        Opportunity opp3 = new Opportunity(RecordTypeId=rTypes.get(rTypesD.get('Sales_Report')),AccountId=acc.Id,Name='NEW',Safra__c='20/2020',Marca__c='GDM', CloseDate=system.today(),Stagename='Editable'); insert opp3;
        controller.getSalesReport();
        controller.recId = 'aa';
        controller.setActiveOpp();
        controller.getSalesReport();
                
        controller.getUser();
        System.assertEquals(controller.getAccount().Name,'JERE');
        controller.getFields();
                
        controller.gotoNew();
        Categoria__c cat = new Categoria__c(Name='BASIC'); insert cat;
        Variedad__c var = new Variedad__c(Name='USG'); insert var;
        Product2 p1 = new Product2(Name='3810', Variedade__c=var.Id,Categ__c=cat.Id,Family='Royalty x Basica'); insert p1;
        Pricebook2 pb2 = new Pricebook2(Name='Portal Pricelist',isActive=true); insert pb2;
        
        PricebookEntry pStd_aux = new PricebookEntry(pricebook2Id=Test.getStandardPricebookId(), Product2Id=p1.id, UnitPrice=0, isActive=true, useStandardPrice=false); insert pStd_aux;
        PricebookEntry pbe = new PricebookEntry(Product2Id=p1.Id,UnitPrice=2,Pricebook2Id=pb2.Id,isActive=true); insert pbe;

        Opportunity opp1 = new Opportunity(RecordTypeId=rTypes.get(rTypesD.get('AnexoI')),AccountId=acc.Id,Name='NEW',Safra__c='20/2020',Marca__c='GDM', CloseDate=system.today(),Stagename='Approved'); insert opp1;
        OpportunityLineItem opp1Item = new OpportunityLineItem(Sales_Report_Type__c='Forecast',Area__c=100,Categoria__c=cat.Id,PricebookEntryId=pbe.Id,OpportunityId=opp1.Id,UnitPrice=1,Quantity=1); insert opp1Item;


        controller.saveSalesReport();

      
        controller.saveSalesReport();
                
        pageRef.getParameters().put('e',opp1.Id);
        Test.setCurrentPageReference(pageRef);        

        controller.validate();                
        System.assertEquals(controller.validate(),null);
        controller.gotoEdit();
       

        controller.EditCancel();               
        controller.saveSalesReport();
        controller.submitSalesReport();
        
        aAppManager.getCategorias();
        aAppManager.getEstados();
        aAppManager.getLinkDataAnalytics();
        
        pageRef.getParameters().put('t','up1');
        Test.setCurrentPageReference(pageRef);        
        
        controller = new aSiteSalesReportController ();
        controller.validate();                
        controller.getRepItemsSale();
        
        pageRef.getParameters().put('t','up2');
        Test.setCurrentPageReference(pageRef);        
        
        controller = new aSiteSalesReportController ();
        controller.validate();                
        controller.getRepItemsSale();
        
        pageRef.getParameters().put('t','up3');
        Test.setCurrentPageReference(pageRef);        
        
        controller = new aSiteSalesReportController ();
        controller.validate();                
        controller.getRepItemsSale();
        
    }    
    
    @IsTest (SeeAllData=false)
    global static void testFinalSalesController () {
		
        aSiteSalesReportController controller = new aSiteSalesReportController ();
        controller.validate();
        
        Map<String,Id> rTypes = Opp_Utils.cargarRecordTypesOportunidades();
        Map<String,String> rTypesD = USAUtils.cargarRecordTypesOppbyDevName();
        
        Account acc = new Account(Site='www.fff.com',AccountNumber='1243',Grupo_de_cuentas__c='US01 - Domestic Customers',Name='JERE', Nome_Fantasia__c = 'JRERE', CodigoSAP__c='451254'); insert acc;
        SiteUser__c su = new SiteUser__c(Email__c='jere@dm.com', Password__c='123'); insert su;
        SiteUserAccount__c suacc = new SiteUserAccount__c(SiteUser__c=su.Id,Account__c=acc.Id, Active__c=true); insert suacc;
        SiteUserSession__c susess = new SiteUserSession__c(Marca__c='GDM', Safra__c='20/2020',SiteUser__c=su.Id); insert susess;
        
        PageReference pageRef = new PageReference('/aSiteSalesReport');
        pageRef.getParameters().put('token',susess.Id);      
        pageRef.getParameters().put('t','fi');
        Test.setCurrentPageReference(pageRef);        
        
        controller = new aSiteSalesReportController ();
        controller.validate();                
        System.assertEquals(controller.validate(),null);
        
        Opportunity opp3 = new Opportunity(RecordTypeId=rTypes.get(rTypesD.get('Sales_Report')),Type='Final Sales Report',AccountId=acc.Id,Name='NEW',Safra__c='20/2020',Marca__c='GDM', CloseDate=system.today(),Stagename='Editable'); insert opp3;
        controller.getSalesReport();
        controller.recId = 'aa';
        controller.setActiveOpp();
        controller.getSalesReport();
                
        controller.getUser();
        System.assertEquals(controller.getAccount().Name,'JERE');        
                
        controller.gotoNew();
        
        Categoria__c cat = new Categoria__c(Name='BASIC'); insert cat;
        Variedad__c var = new Variedad__c(Name='USG'); insert var;
        Product2 p1 = new Product2(Name='3810', Variedade__c=var.Id,Categ__c=cat.Id,Family='Royalty x Basica'); insert p1;
        Pricebook2 pb2 = new Pricebook2(Name='Portal Pricelist',isActive=true); insert pb2;
        
        PricebookEntry pStd_aux = new PricebookEntry(pricebook2Id=Test.getStandardPricebookId(), Product2Id=p1.id, UnitPrice=0, isActive=true, useStandardPrice=false); insert pStd_aux;
        PricebookEntry pbe = new PricebookEntry(Product2Id=p1.Id,UnitPrice=2,Pricebook2Id=pb2.Id,isActive=true); insert pbe;

        Opportunity opp1 = new Opportunity(RecordTypeId=rTypes.get(rTypesD.get('AnexoI')),AccountId=acc.Id,Name='NEW',Safra__c='20/2020',Marca__c='GDM', CloseDate=system.today(),Stagename='Approved'); insert opp1;
        OpportunityLineItem opp1Item = new OpportunityLineItem(Sales_Report_Type__c='Forecast',Area__c=100,Categoria__c=cat.Id,PricebookEntryId=pbe.Id,OpportunityId=opp1.Id,UnitPrice=1,Quantity=1); insert opp1Item;
        
        OpportunityLineItem opp3Item = new OpportunityLineItem(Semente_comercializada__c=100,Categoria__c=cat.Id,PricebookEntryId=pbe.Id,OpportunityId=opp3.Id,UnitPrice=1,Quantity=1); insert opp3Item;
        
        opp3.StageName = 'Approved';
        update opp3;
       
    }
        
    @IsTest (SeeAllData=false)
    global static void testProductionController () {
        
        aSiteProductionReportController controller = new aSiteProductionReportController ();
        controller.validate();
        
        Map<String,Id> rTypes = Opp_Utils.cargarRecordTypesOportunidades();
        Map<String,String> rTypesD = USAUtils.cargarRecordTypesOppbyDevName();
        
        Account acc = new Account(Site='www.fff.com',AccountNumber='1243',Grupo_de_cuentas__c='US01 - Domestic Customers',Name='JERE', Nome_Fantasia__c = 'JRERE', CodigoSAP__c='451254'); insert acc;
        SiteUser__c su = new SiteUser__c(Email__c='jere@dm.com', Password__c='123'); insert su;
        SiteUserAccount__c suacc = new SiteUserAccount__c(SiteUser__c=su.Id,Account__c=acc.Id, Active__c=true); insert suacc;
        SiteUserSession__c susess = new SiteUserSession__c(Marca__c='GDM', Safra__c='18/2018',SiteUser__c=su.Id); insert susess;
        
        PageReference pageRef = new PageReference('/aSiteProductionReport');
        pageRef.getParameters().put('token',susess.Id);      
        pageRef.getParameters().put('t','fi');
        Test.setCurrentPageReference(pageRef);        
        
        controller.validate();                
        System.assertEquals(controller.validate(),null);
        
        Opportunity opp3 = new Opportunity(RecordTypeId=rTypes.get(rTypesD.get('Production_Report')),AccountId=acc.Id,Name='NEW',Safra__c='18/2018',Marca__c='GDM', CloseDate=system.today(),Stagename='Editable'); insert opp3;
        controller.getProductionReport();
        controller.recId = 'aa';
        controller.setActiveOpp();
        controller.getProductionReport();
                
        controller.getUser();
        System.assertEquals(controller.getAccount().Name,'JERE');
        controller.getFields();
                
        controller.gotoNew();       
        
        
        Categoria__c cat = new Categoria__c(Name='BASIC'); insert cat;
        Variedad__c var = new Variedad__c(Name='USG'); insert var;
        Product2 p1 = new Product2(Name='3810', Variedade__c=var.Id,Categ__c=cat.Id,Family='Royalty x Basica'); insert p1;
        Pricebook2 pb2 = new Pricebook2(Name='Portal Pricelist',isActive=true); insert pb2;
        
        PricebookEntry pStd_aux = new PricebookEntry(pricebook2Id=Test.getStandardPricebookId(), Product2Id=p1.id, UnitPrice=0, isActive=true, useStandardPrice=false); insert pStd_aux;
        PricebookEntry pbe = new PricebookEntry(Product2Id=p1.Id,UnitPrice=2,Pricebook2Id=pb2.Id,isActive=true); insert pbe;

        Opportunity opp1 = new Opportunity(RecordTypeId=rTypes.get(rTypesD.get('AnexoI')),AccountId=acc.Id,Name='NEW',Safra__c='18/2018',Marca__c='GDM', CloseDate=system.today(),Stagename='Approved'); insert opp1;
        OpportunityLineItem opp1Item = new OpportunityLineItem(Sales_Report_Type__c='Production',Semente_uso_propio__c=200, Area_Plantada__c=10, Licensee_Variety_Name__c='JERE',Area__c=100,Prev_Parent__c=10,Prev_supply__c=100,Categoria__c=cat.Id,PricebookEntryId=pbe.Id,OpportunityId=opp1.Id,UnitPrice=1,Quantity=1); insert opp1Item;
      
        aSiteUtils.myOppRepItem[] lista = controller.tmpAppItems;

        controller.saveReport();
       
        lista = controller.tmpAppItems;


        controller.saveReport();
                
        pageRef.getParameters().put('e',opp1.Id);
        Test.setCurrentPageReference(pageRef);        

        controller.validate();                
        System.assertEquals(controller.validate(),null);
        controller.gotoEdit();
        

        controller.EditCancel();               
        controller.saveReport();
        controller.submitReport();
        
        pageRef.getParameters().put('t','fi');
        Test.setCurrentPageReference(pageRef);        
        controller = new aSiteProductionReportController ();
        controller.validate();
        
        pageRef.getParameters().put('t','up1');
        Test.setCurrentPageReference(pageRef);        
        controller = new aSiteProductionReportController ();
        controller.validate();
        
        controller.getRepItemsUpdate(); 
       
        
    }

    @IsTest (SeeAllData=false)
    global static void testProductionController2 () {

        aSiteProductionReportController controller = new aSiteProductionReportController ();
        
        
        Map<String,Id> rTypes = Opp_Utils.cargarRecordTypesOportunidades();
        Map<String,String> rTypesD = USAUtils.cargarRecordTypesOppbyDevName();
        
        Account acc = new Account(Site='www.fff.com',AccountNumber='1243',Grupo_de_cuentas__c='US01 - Domestic Customers',Name='JERE', Nome_Fantasia__c = 'JRERE', CodigoSAP__c='451254'); insert acc;
        SiteUser__c su = new SiteUser__c(Email__c='jere@dm.com', Password__c='123'); insert su;
        SiteUserAccount__c suacc = new SiteUserAccount__c(SiteUser__c=su.Id,Account__c=acc.Id, Active__c=true); insert suacc;
        SiteUserSession__c susess = new SiteUserSession__c(Marca__c='GDM', production_season__c='18/2018',Safra__c='18/2018',SiteUser__c=su.Id); insert susess;
        
        PageReference pageRef = new PageReference('/aSiteProductionReport');
        pageRef.getParameters().put('token',susess.Id);      
        pageRef.getParameters().put('t','fi');
        Test.setCurrentPageReference(pageRef);        
        
        //controller.validate();                
        //System.assertEquals(controller.validate(),null);
        
        Opportunity opp3 = new Opportunity(RecordTypeId=rTypes.get(rTypesD.get('Production_Report')),AccountId=acc.Id,Name='NEW',Safra__c='18/2018',Marca__c='GDM', CloseDate=system.today(),Stagename='Editable'); insert opp3;
        controller.getProductionReport();
        controller.recId = 'aa';
        controller.setActiveOpp();
        controller.getProductionReport();
        
        Categoria__c cat = new Categoria__c(Name='BASIC'); insert cat;
        Variedad__c var = new Variedad__c(Name='USG'); insert var;
        Product2 p1 = new Product2(Name='3810', Variedade__c=var.Id,Categ__c=cat.Id,Family='Royalty x Basica'); insert p1;
        Pricebook2 pb2 = new Pricebook2(Name='Portal Pricelist',isActive=true); insert pb2;
        
        PricebookEntry pStd_aux = new PricebookEntry(pricebook2Id=Test.getStandardPricebookId(), Product2Id=p1.id, UnitPrice=0, isActive=true, useStandardPrice=false); insert pStd_aux;
        PricebookEntry pbe = new PricebookEntry(Product2Id=p1.Id,UnitPrice=2,Pricebook2Id=pb2.Id,isActive=true); insert pbe;

        Opportunity opp1 = new Opportunity(RecordTypeId=rTypes.get(rTypesD.get('AnexoI')),AccountId=acc.Id,Name='NEW',Safra__c='18/2018',Marca__c='GDM', CloseDate=system.today(),Stagename='Approved'); insert opp1;
        OpportunityLineItem opp1Item = new OpportunityLineItem(Sales_Report_Type__c='Production',Area__c=100,Categoria__c=cat.Id,PricebookEntryId=pbe.Id,OpportunityId=opp1.Id,UnitPrice=1,Quantity=1); insert opp1Item;
      
        aSiteUtils.myOppRepItem[] lista = controller.tmpAppItems;

        controller.saveReport();
      
        Opportunity opp2 = new Opportunity(RecordTypeId=rTypes.get(rTypesD.get('Production_Report')),AccountId=acc.Id,Name='NEW',Safra__c='18/2018',Marca__c='GDM', type='Production Update 1', CloseDate=system.today(),Stagename='Approved'); insert opp2;
        OpportunityLineItem opp2Item = new OpportunityLineItem(Sales_Report_Type__c='Production',Area__c=100,Categoria__c=cat.Id,PricebookEntryId=pbe.Id,OpportunityId=opp2.Id,UnitPrice=1,Quantity=1); insert opp2Item;
        
        pageRef.getParameters().put('t','up2');
        Test.setCurrentPageReference(pageRef);        
        controller = new aSiteProductionReportController ();
        controller.validate();
      
        controller.showConditioned();
        
        pageRef.getParameters().put('t','up3');
        Test.setCurrentPageReference(pageRef);        
        controller = new aSiteProductionReportController ();
        controller.validate();
        
        pageRef.getParameters().put('t','up4');
        Test.setCurrentPageReference(pageRef);        
        controller = new aSiteProductionReportController ();
        controller.validate();
        
        pageRef.getParameters().put('t','up5');
        Test.setCurrentPageReference(pageRef);        
        controller = new aSiteProductionReportController ();
        controller.validate();
      
    }
    
     @IsTest (SeeAllData=false)
    global static void testFinalProductionController () {
        
        aSiteProductionReportController controller = new aSiteProductionReportController ();
        controller.validate();
        
        Map<String,Id> rTypes = Opp_Utils.cargarRecordTypesOportunidades();
        Map<String,String> rTypesD = USAUtils.cargarRecordTypesOppbyDevName();
        
        Account acc = new Account(Site='www.fff.com',AccountNumber='1243',Grupo_de_cuentas__c='US01 - Domestic Customers',Name='JERE', Nome_Fantasia__c = 'JRERE', CodigoSAP__c='451254'); insert acc;
        SiteUser__c su = new SiteUser__c(Email__c='jere@dm.com', Password__c='123'); insert su;
        SiteUserAccount__c suacc = new SiteUserAccount__c(SiteUser__c=su.Id,Account__c=acc.Id, Active__c=true); insert suacc;
        SiteUserSession__c susess = new SiteUserSession__c(Marca__c='GDM', production_season__c='20/2020', Safra__c='18/2018',SiteUser__c=su.Id); insert susess;
        
        PageReference pageRef = new PageReference('/aSiteProductionReport');
        pageRef.getParameters().put('token',susess.Id);      
        pageRef.getParameters().put('t','fi');
        Test.setCurrentPageReference(pageRef);        
        
        controller.validate();                
        System.assertEquals(controller.validate(),null);
        
        Opportunity opp3 = new Opportunity(RecordTypeId=rTypes.get(rTypesD.get('Production_Report')),type='Final Production Report',AccountId=acc.Id,Name='NEW',Safra__c='20/2020',Marca__c='DONMARIO',CloseDate=system.today(),Stagename='Editable'); insert opp3;
        controller.getProductionReport();
        controller.recId = 'aa';
        controller.setActiveOpp();
        controller.getProductionReport();
                
        controller.getUser();
        System.assertEquals(controller.getAccount().Name,'JERE');
        controller.getFields();
                
        controller.gotoNew();       
        
        Categoria__c cat = new Categoria__c(Name='BASIC'); insert cat;
        Variedad__c var = new Variedad__c(Name='USG'); insert var;
        Product2 p1 = new Product2(Name='3810', Variedade__c=var.Id,Categ__c=cat.Id,Family='Seed',Unidade__c='BAG 140K'); insert p1;
        Pricebook2 pb2 = new Pricebook2(Name='DONMARIO - WHOLESALE PriceList',isActive=true); insert pb2;
        
        PricebookEntry pStd_aux = new PricebookEntry(pricebook2Id=Test.getStandardPricebookId(), Product2Id=p1.id, UnitPrice=0, isActive=true, useStandardPrice=false); insert pStd_aux;
        PricebookEntry pbe = new PricebookEntry(Product2Id=p1.Id,UnitPrice=2,Pricebook2Id=pb2.Id,isActive=true); insert pbe;

        //Opportunity opp1 = new Opportunity(RecordTypeId=rTypes.get(rTypesD.get('AnexoI')),AccountId=acc.Id,Name='NEW',Safra__c='20/2020',Marca__c='DONMARIO', CloseDate=system.today(),Stagename='Approved'); insert opp1;
        OpportunityLineItem opp1Item = new OpportunityLineItem(Sales_Report_Type__c='Production',Semente_beneficiada__c=10,Area__c=100,Categoria__c=cat.Id,PricebookEntryId=pbe.Id,OpportunityId=opp3.Id,UnitPrice=1,Quantity=1); insert opp1Item;
      
        aSiteUtils.myOppRepItem[] lista = controller.tmpAppItems;

        controller.saveReport();
       
        lista = controller.tmpAppItems;
		
        controller.saveReport();
                
        //pageRef.getParameters().put('e',opp1.Id);
        //Test.setCurrentPageReference(pageRef);        

        controller.validate();                
        System.assertEquals(controller.validate(),null);
        controller.gotoEdit();

        controller.EditCancel();               
        controller.saveReport();
        controller.submitReport();
        
        opp3.StageName = 'Sent'; update opp3;
        
        pageRef.getParameters().put('t','fi');
        Test.setCurrentPageReference(pageRef);        
        controller = new aSiteProductionReportController ();
        controller.validate();
        
        controller.getRepItemsUpdate();
                    
        pageRef.getParameters().put('t','up2');
        Test.setCurrentPageReference(pageRef);        
        controller = new aSiteProductionReportController ();
        controller.validate();
      
        controller.showConditioned();
        
    }

}