force-app/main/default/objects/Account/fields/CodigoSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoSAP__c</fullName>
    <label>Account Sap Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status_Integration__c.field-meta.xml
<CustomField>
    <fullName>Status_Integration__c</fullName>
    <label>Status Integration</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Queue__c/Queue__c.object-meta.xml
<CustomObject>
    <label>Queue</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AccountBO.cls
public with sharing class AccountBO {
    
    private static final AccountBO instance = new AccountBO();
    private AccountBO() {}
     
    public static AccountBO getInstance() {
        return instance;
    }

    public void newIntegration(List<Account> accountList, Map<Id, Account> oldAccMap) {
      List<Queue__c> queueToInsert = new List<Queue__c>();
      List<String> accountIds = new List<String>();

      for(Account account : accountList) {
            if((account.CodigoSAP__c == null || account.CodigoSAP__c == '') && account.Status_integration__c == 'Insert Mode' && account.Status_integration__c != oldAccMap.get(account.Id).Status_integration__c){
                accountIds.add(account.Id);
            }
            else if((account.CodigoSAP__c != null || account.CodigoSAP__c != '') && (oldAccMap.get(account.Id).CodigoSAP__c != null || oldAccMap.get(account.Id).CodigoSAP__c != '') && (oldAccMap.get(account.Id).CodigoSAP__c != account.CodigoSAP__c) && account.Status_integration__c == 'Insert Mode'){
                account.addError('This account has already been created in SAP.');
            }
      }

      
      for(Account account : AccountDAO.getInstance().getAccountsById(accountIds)) {
          	System.debug('SANTIAGO - INTENTO DE SYNCRONIZACION CON SAP ' + account.Name);
            String jsonResult = AccountIntegrationBO.outboundRequest(account);

            queueToInsert.add(QueueBO.getInstance().sObjectQueue(account.Id, QueueEventNames.ACCOUNT_SALESFORCE_TO_SAP.name(), jsonResult, false) 
            );
      }
        
      insert queueToInsert;
    }
}