force-app/main/default/objects/Account/fields/CodigoSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoSAP__c</fullName>
    <label>Account Sap Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>Addendum to the Soybean Germplasm Aggrement.</description>
    <label>Schedule A</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Schedule A Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/fields/Multiplicador__c.field-meta.xml
<CustomField>
    <fullName>Multiplicador__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Licensee Account</description>
    <label>Licensee</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Contratos_de_Multiplicacion</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>24/2024</fullName>
            </value>
            <value>
                <fullName>23/2023</fullName>
            </value>
            <value>
                <fullName>22/2022</fullName>
            </value>
            <value>
                <fullName>21/2021</fullName>
            </value>
            <value>
                <fullName>20/2020</fullName>
            </value>
            <value>
                <fullName>19/2019</fullName>
            </value>
            <value>
                <fullName>18/2018</fullName>
            </value>
            <value>
                <fullName>17/2017</fullName>
            </value>
            <value>
                <fullName>16/2016</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GDM</fullName>
                <default>true</default>
                <label>GDM</label>
            </value>
            <value>
                <fullName>B&amp;B</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Tipo_de_cambio__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_cambio__c</fullName>
    <label>Tipo de câmbio</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Contrato__c/fields/Tipo_de_Cota_o__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Cota_o__c</fullName>
    <label>Tipo de Cotação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DOLAR</fullName>
            </value>
            <value>
                <fullName>SOJA</fullName>
            </value>
            <value>
                <fullName>FATURAMENTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contrato__c/recordTypes/Parent_Seed_Schedule_A.recordType-meta.xml
<RecordType>
    <fullName>Parent_Seed_Schedule_A</fullName>
    <active>true</active>
    <label>Parent Seed Schedule A</label>
</RecordType>

force-app/main/default/objects/Item_del_Contrato__c/Item_del_Contrato__c.object-meta.xml
<CustomObject>
    <description>Addendum Variety item</description>
    <label>Schedule A Variety</label>
    <nameField>
        <label>Schedule A Variety</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules A Variety</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_del_Contrato__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates category of the licensee product</description>
    <inlineHelpText>Indicates category of the licensee product</inlineHelpText>
    <label>Category</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipName>Items_del_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item_del_Contrato__c/fields/Contrato_de_Multiplicacion__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Multiplicacion__c</fullName>
    <description>Agreement related to</description>
    <inlineHelpText>Agreement related to</inlineHelpText>
    <label>Schedule A</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Schedules A Variety</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item_del_Contrato__c/fields/Cultivar__c.field-meta.xml
<CustomField>
    <fullName>Cultivar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cultivar por el/los que se confecciona el contrato</description>
    <inlineHelpText>Cultivar por el/los que se confecciona el contrato</inlineHelpText>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Royalty</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Schedules A Variety</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item_del_Contrato__c/fields/Quantidade__c.field-meta.xml
<CustomField>
    <fullName>Quantidade__c</fullName>
    <description>Indica la cantidad por la que se cerró el aditivo</description>
    <label>Quantidade</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item_del_Contrato__c/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <formula>Cultivar__r.Variedade__r.Name</formula>
    <label>Variety Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variety Name</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <label>Variety</label>
    <nameField>
        <label>Variety Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Varieties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/itemsContratoMultControllerTest.cls
@isTest
private class itemsContratoMultControllerTest {

    static testMethod void myUnitTest() {
    
    Map<String,Id> rt = New Map<String, Id>();
    for(RecordType reTy : [Select Id, Name From RecordType])
        rt.put(reTy.Name, reTy.Id);

    Account cuenta = new Account(Name='ACME', CodigoSAP__c='6000000000'); insert cuenta;
    Categoria__c cat = new Categoria__c(Name='Basic'); insert cat;
    Variedad__c var = new Variedad__c(Name='TRUMP 1'); insert var;
    Product2 prd = new Product2(Name='SOJAETA',Categ__c=cat.Id,Variedade__c=var.Id,isActive=true,Family='Royalty'); insert prd;
      
    Contrato__c c = new Contrato__c(Multiplicador__c=cuenta.Id,Sociedad__c='GDM', RecordTypeId = rt.get('Parent Seed Schedule A'), Safra__c = '18/2018');
    insert c;
    c.Tipo_de_Cota_o__c = 'DOLAR';
    update c;
    
    Item_del_Contrato__c ic = new Item_del_Contrato__c(Cultivar__c=prd.Id, Contrato_de_Multiplicacion__c = c.Id); insert ic;
            
    PageReference pageRef = Page.Items_Contrato_Multiplicacion;
    pageRef.getParameters().put('Id',c.Id);
    pageRef.getParameters().put('nombre',c.Name);
    pageRef.getParameters().put('sociedad',c.Sociedad__c);

    Test.setCurrentPageReference(pageRef);

    itemsContratoMultController i = New itemsContratoMultController();
    i.init();      
        
        /*
    Item_del_Contrato__c ic = new Item_del_Contrato__c(Cultivar__c=pbe.Product2Id, Contrato_de_Multiplicacion__c = c.Id);
        insert ic;
        Contrato__c adi = new Contrato__c(Multiplicador__c=cuenta.Id,Sociedad__c='BRMX', RecordTypeId = rt.get('Aditivo BRMX'), Tipo_de_Cota_o__c = 'DOLAR', Tipo_de_cambio__c = 1.45, Safra__c = '18/19');
        insert adi;
        Item_del_Contrato__c iadi = new Item_del_Contrato__c(Cultivar__c=pbe.Product2Id, Contrato_de_Multiplicacion__c = adi.Id, Quantidade__c = 10, Categoria__c = cat.Id);
        insert iadi;
        Item_del_Contrato__c iadi2 = new Item_del_Contrato__c(Cultivar__c=pbe.Product2Id, Contrato_de_Multiplicacion__c = adi.Id, Quantidade__c = 10, Categoria__c = cat.Id);
    
        PageReference pageRef = Page.Items_Contrato_Multiplicacion;
        pageRef.getParameters().put('Id',c.Id);
        pageRef.getParameters().put('nombre',c.Name);
        pageRef.getParameters().put('sociedad',c.Sociedad__c);
        
        Test.setCurrentPageReference(pageRef);

        //itemsContratoMultController i = New itemsContratoMultController(new ApexPages.StandardController(c.Id));
        itemsContratoMultController i = New itemsContratoMultController();
        i.init();      
        */
        Id a;
        String b;
        
        i.seteditItem(a);
        i.seteliminarItem(a);
        i.setidContrato(a);
        i.setsaveEditItem(a);
        i.setrecTypeContrato('Parent_Seed_Schedule_A');
        i.getrecTypeContrato();
        i.setMensaje('Probando');
        i.getMensaje();
        i.getProductosBasica();
        
        i.getprodsBasica();        
       
        a = i.geteditItem();  
        a = i.geteliminarItem();
        a = i.getidContrato();
        a = i.getsaveEditItem();
        i.setnombreContrato(b);
        
        b = prd.Id;
        i.setidContrato (c.Id);
        pageRef.getParameters().put('save_edit_item',c.Id);
        
        i.setnuevoBasica(b);
        i.addItem();
        
        i.seteditBasica(b);
        i.setsociedadContrato(b);
        b = i.getnombreContrato();
        b = i.getnuevoBasica();
        b = i.geteditBasica();
        b = i.getsociedadContrato();
        
        pageRef.getParameters().put('edit_item', ic.Id);       
        i.editarItem();
        i.cancelEditarItem();
        i.eliminarItem();                
                
        i.saveEditItem();
        i.volver();
            
    }
}