force-app/main/default/objects/Account/fields/CodigoSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoSAP__c</fullName>
    <label>Account Sap Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuracion_USA__c/Configuracion_USA__c.object-meta.xml
<CustomObject>
    <label>Admin Setting</label>
    <nameField>
        <label>Admin Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admin Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuracion_USA__c/fields/link_intra_dm__c.field-meta.xml
<CustomField>
    <fullName>link_intra_dm__c</fullName>
    <label>Link Sap Des</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuracion_USA__c/fields/RecordType_for_OppNro__c.field-meta.xml
<CustomField>
    <fullName>RecordType_for_OppNro__c</fullName>
    <label>RecordType for OppNro</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/General_Settings__c.object-meta.xml
<CustomObject>
    <description>Object to set settings globally. This should only be enabled for Administrators</description>
    <label>General Settings</label>
    <nameField>
        <label>General Settings</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/General_Settings__c/fields/Don_Mario__c.field-meta.xml
<CustomField>
    <fullName>Don_Mario__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Don Mario Licensing responsable</description>
    <label>Don Mario</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/GDM_Licensing__c.field-meta.xml
<CustomField>
    <fullName>GDM_Licensing__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>GDM Licensing Responsable</description>
    <label>GDM Licensing</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/General_Settings__c/fields/Virtue__c.field-meta.xml
<CustomField>
    <fullName>Virtue__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Virtue licensing responsable</description>
    <label>Virtue</label>
    <referenceTo>User</referenceTo>
    <relationshipName>General_Settings1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Branch Name)</relationshipLabel>
    <relationshipName>Opportunities_Branchs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Condicion_de_Pago__c.field-meta.xml
<CustomField>
    <fullName>Condicion_de_Pago__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZC05 Net 30 days from shipping date</fullName>
                <default>true</default>
                <label>Net 30 days from shipping date</label>
            </value>
            <value>
                <fullName>ZC04 Net 20 days from shipping date</fullName>
                <label>Net 20 days from shipping date</label>
            </value>
            <value>
                <fullName>ZC05 - S4 test Condition</fullName>
                <label>S4 test Condition</label>
            </value>
            <value>
                <fullName>ZC00 Due Upon Receipt</fullName>
                <label>Due Upon Receipt</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Incoterm_1__c.field-meta.xml
<CustomField>
    <fullName>Incoterm_1__c</fullName>
    <label>Incoterm</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DED - Deliver to ship-to address</fullName>
                <default>true</default>
                <label>DED - Deliver to ship-to address</label>
            </value>
            <value>
                <fullName>DEP - Pick Up</fullName>
            </value>
            <value>
                <fullName>CFR - Cost and Freight</fullName>
            </value>
            <value>
                <fullName>CIF - Cost Insurance and Freight</fullName>
            </value>
            <value>
                <fullName>CIP - Carriage and Insurance Paid (To)</fullName>
            </value>
            <value>
                <fullName>CPT - Carriage Paid To</fullName>
            </value>
            <value>
                <fullName>DAP - Delivered At Place</fullName>
            </value>
            <value>
                <fullName>DAT - Delivered At Terminal</fullName>
            </value>
            <value>
                <fullName>DDP - Delivered Duty Paid</fullName>
            </value>
            <value>
                <fullName>DIB - Deliver</fullName>
            </value>
            <value>
                <fullName>EXW - Ex Works</fullName>
            </value>
            <value>
                <fullName>FAS - Free Alongside Ship</fullName>
            </value>
            <value>
                <fullName>FCA - Free Carrier</fullName>
            </value>
            <value>
                <fullName>FOB - Free On Board</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Incoterm_2__c.field-meta.xml
<CustomField>
    <fullName>Incoterm_2__c</fullName>
    <label>Incoterm 2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MARION</fullName>
            </value>
            <value>
                <fullName>NEWPORT</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Nro_Pedido_SAP__c.field-meta.xml
<CustomField>
    <fullName>Nro_Pedido_SAP__c</fullName>
    <externalId>true</externalId>
    <label>SAP Order Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ship To)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZO13 - Export Order</fullName>
            </value>
            <value>
                <fullName>ZO14 – Local Order</fullName>
                <default>true</default>
                <label>ZO14 – Local Order - Seeds</label>
            </value>
            <value>
                <fullName>ZO15 - Local Order</fullName>
                <label>ZO15 - Local Order - Royalty</label>
            </value>
            <value>
                <fullName>Customer Goal</fullName>
            </value>
            <value>
                <fullName>Budget</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Production_Report.recordType-meta.xml
<RecordType>
    <fullName>Production_Report</fullName>
    <active>true</active>
    <businessProcess>Portal Reports</businessProcess>
    <label>Production Report</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Sale.recordType-meta.xml
<RecordType>
    <fullName>Sale</fullName>
    <active>true</active>
    <businessProcess>Invoice</businessProcess>
    <label>Sale</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Sales_Report.recordType-meta.xml
<RecordType>
    <fullName>Sales_Report</fullName>
    <active>true</active>
    <businessProcess>Portal Reports</businessProcess>
    <label>Sales Report</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Centro_de_despacho__c.field-meta.xml
<CustomField>
    <fullName>Centro_de_despacho__c</fullName>
    <label>Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>E001 - B&amp;B - CHAMPAIGN</fullName>
            </value>
            <value>
                <fullName>E002 - B&amp;B - GIBSON CITY</fullName>
            </value>
            <value>
                <fullName>E003 - B&amp;B - JONESBORO</fullName>
            </value>
            <value>
                <fullName>E004 – B&amp;B - PRO AG EARLY</fullName>
            </value>
            <value>
                <fullName>E004 – B&amp;B - PRO AG LATE</fullName>
            </value>
            <value>
                <fullName>U001 - GDM - CHAMPAIGN</fullName>
            </value>
            <value>
                <fullName>U002 - GDM - GIBSON CITY</fullName>
            </value>
            <value>
                <fullName>U003 - GDM - JONESBORO</fullName>
            </value>
            <value>
                <fullName>U004 - GDM - PRO AG EARLY</fullName>
            </value>
            <value>
                <fullName>U004 - GDM - PRO AG LATE</fullName>
            </value>
            <value>
                <fullName>U005 - GDM - HUTCHINSON</fullName>
            </value>
            <value>
                <fullName>U006 - GDM - DES MOINES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Pallet_Charge__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Charge__c</fullName>
    <label>Pallet Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Shipping_Costs__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Costs__c</fullName>
    <label>Shipping Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BAG 140K</fullName>
            </value>
            <value>
                <fullName>BAG 40(140K)</fullName>
            </value>
            <value>
                <fullName>LB</fullName>
            </value>
            <value>
                <fullName>BAGS BY LBS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Queue__c/Queue__c.object-meta.xml
<CustomObject>
    <label>Queue</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Queue__c/fields/Payload__c.field-meta.xml
<CustomField>
    <fullName>Payload__c</fullName>
    <label>Payload</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Queue__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>RecordId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/OpportunityVtaIntegrationBOTest.cls
@isTest
private class OpportunityVtaIntegrationBOTest {
  
    @isTest static void test_method_one() {
     
    Configuracion_USA__c co = new Configuracion_USA__c(FC_mandante_SAP__c='200',RecordType_for_OppNro__c='Sales_Report,Production_Report',link_intra_dm__c='', Link_Sap_Prod__c='', Link_Sap_QA__c='');
    insert co;
   
	//SELECT Id, GDM_Licensing__c, Virtue__c, Don_Mario__c 
    General_Settings__c gs = new General_Settings__c();
    insert gs;
    
    Account account = new Account();
    account.Name = 'AGENTE';
    account.CodigoSAP__c = '12456554';
    insert account;

    Account account2 = new Account();
    account2.Name = 'AGENTE2';
    account2.CodigoSAP__c = '124565543';
    insert account2;
    
    Product2 produto002           = new Product2();
    produto002.Name               = 'ROYALTY';
    produto002.ProductCode        = '40026418';
    produto002.isActive           = true; 
    insert produto002;

    Product2 produto_2           = new Product2();

    produto_2.Name               = 'SEED';
    produto_2.ProductCode        = '40026418';
    produto_2.isActive           = true;

    insert produto_2;

    Pricebook2 price1                 = new Pricebook2();
    price1.Name                       = 'Teste';
    price1.Description                = 'Teste';
    price1.IsActive                   = true;

    insert price1;

//    Pricebook2 pb = [SELECT Id FROM Pricebook2 WHERE Name = 'GDM - PriceList'];

    PricebookEntry priceBookEntry1 = new PricebookEntry();
    priceBookEntry1.Pricebook2Id = Test.getStandardPricebookId();
//    priceBookEntry1.Pricebook2Id = pb.Id;    
    priceBookEntry1.Product2Id = produto_2.id;
    priceBookEntry1.UseStandardPrice = false;
    priceBookEntry1.IsActive = true;
    priceBookEntry1.UnitPrice = 100.00;

    insert priceBookEntry1;

    Opportunity opp = new Opportunity();
    opp.RecordTypeID = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sale').getRecordTypeId();
    opp.Safra__c = '19/2019';    
    opp.AccountId = account.Id;
    opp.Ship_To__c = account.Id;
    opp.Branch_name__c = account2.Id; 
    opp.Name   = 'UnitTest';
    opp.Tipo__c = 'ZPLO - Local Order';
    opp.StageName  = 'Edition'; 
    opp.CloseDate = System.today()+60;
    opp.Condicion_de_Pago__c = 'ZC05 Net 30 days from shipping date';
    opp.Type = 'Z17 - PARENT SEED';
    opp.Pricebook2Id = Test.getStandardPricebookId();

    insert opp;

    OpportunityLineItem oppli1 = new OpportunityLineItem();
    oppli1.OpportunityId = opp.id;
    oppli1.PricebookEntryId = priceBookEntry1.id;
    oppli1.UnitPrice = 1;
    oppli1.Quantity = 40;
    oppli1.Pallet_Charge__c = 10;
    oppli1.Centro_de_Despacho__c = 'UD01';

    insert oppli1;

    update opp;

    List<Queue__c> queueToInsert = new List<Queue__c>();
    for( Opportunity opportunity : OpportunityDAO.getInstance().getOpportunityByListId( new List<String>{ opp.Id } ) ) {
        String jsonResult;
        if(opportunity.Nro_pedido_SAP__c == null || opportunity.Nro_pedido_SAP__c == ''){
            jsonResult = OpportunityVtaIntegrationBO.outboundRequest( opportunity );
            queueToInsert.add( QueueBO.getInstance().sObjectQueue( opportunity.Id, 'OPPORTUNITY_SALESFORCE_TO_SAP', jsonResult, false ) );
        }
    }

    insert queueToInsert;

    Queue__c result = [SELECT Id, EventName__c, RecordId__c, Payload__c FROM Queue__c WHERE Id = :queueToInsert[0].Id];
 
    OpportunityVtaIntegrationBO.executeQueue(result.Id, result.RecordId__c, result.EventName__c, result.Payload__c, 1);  

  }

  @isTest static void test_method_two() {
   
    Configuracion_USA__c co = new Configuracion_USA__c(RecordType_for_OppNro__c='Sales_Report,Production_Report',link_intra_dm__c='', Link_Sap_Prod__c='', Link_Sap_QA__c='');
    insert co;
    General_Settings__c gs = new General_Settings__c();
    insert gs;
      
    Account account = new Account(Name='123412');
    account.CodigoSAP__c = '12456554';
    insert account;

    Product2 produto01           = new Product2();
    produto01.Name               = 'SS M8808 IPRO COM P1';
    produto01.ProductCode        = '40026418';
    produto01.Unidade__c         = 'LB';
    produto01.isActive           = true; 

    insert produto01;

    Product2 produto02           = new Product2();

    produto02.Name               = 'M 8808 IPRO P1 B5M';
    produto02.ProductCode        = '40026418';
    produto02.isActive           = true;

    insert produto02;

    Pricebook2 price1                 = new Pricebook2();
    price1.Name                       = 'Teste';
    price1.Description                = 'Teste';
    price1.IsActive                   = true;

    insert price1;

    PricebookEntry priceBookEntry1 = new PricebookEntry();
    priceBookEntry1.Pricebook2Id = Test.getStandardPricebookId();
    priceBookEntry1.Product2Id = produto02.id;
    priceBookEntry1.UseStandardPrice = false;
    priceBookEntry1.IsActive = true;
    priceBookEntry1.UnitPrice = 100.00;

    insert priceBookEntry1; 
           
    PricebookEntry priceBookEntry2 = new PricebookEntry();
    priceBookEntry2.Pricebook2Id = Test.getStandardPricebookId();
    priceBookEntry2.Product2Id = produto01.id;
    priceBookEntry2.UseStandardPrice = false;
    priceBookEntry2.IsActive = true;
    priceBookEntry2.UnitPrice = 1.434;

    insert priceBookEntry2;    

    Opportunity opp = new Opportunity();
    opp.RecordTypeID = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sale').getRecordTypeId();
    opp.Safra__c = '19/2019';    
    opp.AccountId = account.Id;
    opp.Ship_To__c = account.Id; 
    opp.Name   = 'UnitTest';
    opp.Tipo__c = 'ZPLO - Local Order';
    opp.Incoterm_1__c = 'FOB - FREE ON BOARD';
    opp.Incoterm_2__c = 'MARION';
    opp.StageName  = 'Pending Approval'; 
    opp.CloseDate = System.today()+60;
    opp.Condicion_de_Pago__c = 'ZC05 Net 30 days from shipping date';
    opp.Type = 'Z17 - PARENT SEED';
    opp.Pricebook2Id = Test.getStandardPricebookId();
    insert opp;

    OpportunityLineItem oppli1 = new OpportunityLineItem();
    oppli1.OpportunityId = opp.id;
    oppli1.PricebookEntryId = priceBookEntry1.id;
    oppli1.UnitPrice = 1;
    oppli1.Quantity = 40;
    oppli1.Shipping_Costs__c = 21;
    oppli1.Pallet_Charge__c = 6;
    oppli1.Centro_de_Despacho__c = 'UD01';
    
    insert oppli1;

    OpportunityLineItem oppli2 = new OpportunityLineItem();
    oppli2.OpportunityId = opp.id;
    oppli2.PricebookEntryId = priceBookEntry2.id;
    oppli2.UnitPrice = 1;
    oppli2.Quantity = 480;
    oppli2.Shipping_Costs__c = 1;
    oppli2.Centro_de_Despacho__c = 'UD01';
    
    insert oppli2;
    
    opp.StageName  = 'Approved'; 
    update opp;

    List<Queue__c> queueToInsert = new List<Queue__c>();
    for( Opportunity opportunity : OpportunityDAO.getInstance().getOpportunityByListId( new List<String>{ opp.Id } ) ) {
        String jsonResult;
        if(opportunity.Nro_Pedido_SAP__c == null || opportunity.Nro_Pedido_SAP__c == ''){
            jsonResult = OpportunityVtaIntegrationBO.outboundRequest( opportunity );
            queueToInsert.add( QueueBO.getInstance().sObjectQueue( opportunity.Id, 'OPPORTUNITY_SALESFORCE_TO_SAP', jsonResult, false ) );
      }
    }

    insert queueToInsert;

    Queue__c result = [SELECT Id, EventName__c, RecordId__c, Payload__c FROM Queue__c WHERE Id = :queueToInsert[0].Id]; 
    OpportunityVtaIntegrationBO.executeQueue(result.Id, result.RecordId__c, result.EventName__c, result.Payload__c,110);  

    //ejecutar una modificacion por rejection
    List<Queue__c> queueToReject = new List<Queue__c>();
    for(Opportunity opportunity : OpportunityDAO.getInstance().getOpportunityByListId( new List<String>{ opp.Id } ) ) {
        String jsonResult;
        jsonResult = OpportunityVtaIntegrationBO.outboundRequestRej( opportunity );
        queueToReject.add( QueueBO.getInstance().sObjectQueue( opportunity.Id, 'OPPORTUNITY_REJ_SALESFORCE_TO_SAP', jsonResult, false ) );
    }

    insert queueToReject;
    Queue__c result2 = [SELECT Id, EventName__c, RecordId__c, Payload__c FROM Queue__c WHERE Id = :queueToReject[0].Id];
    OpportunityVtaIntegrationBO.executeQueue(result2.Id, result2.RecordId__c, result2.EventName__c, result2.Payload__c,110);  
    
  }

  
}