force-app/main/default/objects/Account/fields/CodigoSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoSAP__c</fullName>
    <label>Account Sap Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Grupo_de_Cuentas__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Cuentas__c</fullName>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>US01 - Domestic Customers</fullName>
            </value>
            <value>
                <fullName>US02 - Foreing Customers</fullName>
                <label>US02 - Foreign Customers</label>
            </value>
            <value>
                <fullName>US03 - Ship To</fullName>
            </value>
            <value>
                <fullName>US04 - Branches</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nome_fantasia__c.field-meta.xml
<CustomField>
    <fullName>Nome_fantasia__c</fullName>
    <label>Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Reports</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Production_Report.recordType-meta.xml
<RecordType>
    <fullName>Production_Report</fullName>
    <active>true</active>
    <businessProcess>Portal Reports</businessProcess>
    <label>Production Report</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Sales_Report.recordType-meta.xml
<RecordType>
    <fullName>Sales_Report</fullName>
    <active>true</active>
    <businessProcess>Portal Reports</businessProcess>
    <label>Sales Report</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Semente_bruta__c.field-meta.xml
<CustomField>
    <fullName>Semente_bruta__c</fullName>
    <inlineHelpText>Unit: Bushels - Final Production Report</inlineHelpText>
    <label>Production Bushels</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de SiteUser</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteUser__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SiteUsers</relationshipLabel>
    <relationshipName>SiteUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteUserAccount__c/SiteUserAccount__c.object-meta.xml
<CustomObject>
    <label>SiteUserAccount</label>
    <nameField>
        <label>SiteUserAccount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUserAccounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteUserSession__c/SiteUserSession__c.object-meta.xml
<CustomObject>
    <label>SiteUserSession</label>
    <nameField>
        <displayFormat>S{00000000}</displayFormat>
        <label>SiteUserSession Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SiteUserSessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteUserSession__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SiteUserSession__c/fields/Production_Season__c.field-meta.xml
<CustomField>
    <fullName>Production_Season__c</fullName>
    <label>Production Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SiteUserSession__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/aSiteHomeHeaderControllerTest.cls
/**
 * Clase test de todos los controllers del sitio portal, USA especifico
 * Jere 22.06.02 Complete unit tests
 */
@isTest
global with sharing class aSiteHomeHeaderControllerTest {

    @IsTest(SeeAllData=false)
    global static void testHomeController () {
        Account acc = new Account(Site='www.fff.com',AccountNumber='1243',Grupo_de_cuentas__c='US01 - Domestic Customers',Name='JERE', Nome_Fantasia__c = 'JRERE', CodigoSAP__c='451254'); insert acc;
        SiteUser__c su = new SiteUser__c(Email__c='jere@dm.com', Password__c='123'); insert su;
        SiteUserAccount__c suacc = new SiteUserAccount__c(SiteUser__c=su.Id,Account__c=acc.Id, Active__c=true); insert suacc;
        SiteUserSession__c susess = new SiteUserSession__c(Marca__c='GDM',Production_season__c='20/2020', Sales_season__c='20/2020', Safra__c='20/2020',SiteUser__c=su.Id); insert susess;

        aSiteHomeController controller = new aSiteHomeController();
        controller.validate();
                        
        PageReference pageRef = Page.aSiteHome;
        pageRef.getParameters().put('token',susess.Id);      
        Test.setCurrentPageReference(pageRef);

        controller.validate();
        controller.getUser();
                
        //controller.getHomeMessage();
        
        Map<String,Id> rTypes = Opp_Utils.cargarRecordTypesOportunidades();
        Map<String,String> rTypesD = USAUtils.cargarRecordTypesOppbyDevName();
        String type = 'Production Update 2';
        Opportunity opp = new Opportunity(RecordTypeId=rTypes.get(rTypesD.get('Production_Report')),AccountId=acc.Id,Name='NEW',Safra__c='20/2020',Marca__c='GDM',CloseDate=system.today(),Stagename='Editable',Type=type); insert opp;
        
        Product2 p1 = new Product2(Name='DM3810'); insert p1;
        Pricebook2 pb = new Pricebook2(Name='Portal PriceList',isActive=true); insert pb;
        PricebookEntry pStd_aux = new PricebookEntry(pricebook2Id=Test.getStandardPricebookId(), Product2Id=p1.id, UnitPrice=0, isActive=true, useStandardPrice=false); insert pStd_aux;
        PricebookEntry pbe = new PricebookEntry(Product2Id=p1.Id,UnitPrice=2,Pricebook2Id=pb.Id,isActive=true); insert pbe;
        OpportunityLineItem oli = new OpportunityLineItem (OpportunityId=opp.Id,Quantity=1000,Semente_bruta__c=10000,UnitPrice=32,PricebookEntryId=pbe.Id); insert oli;
        
        controller.getTotalProduction();
        controller.getDiffProduction();
        controller.getDiffSold();
        controller.getTotalSold();
        controller.getDiffFore();
        controller.getTotalForecast();
            
        controller.gotoProdReport();
        controller.gotoProdUpdate3Report();
        controller.gotoProdUpdateAugReport();
        controller.gotoProdUpdateDecReport();
        controller.gotoProd2();
        controller.gotoProd1();
        
        controller.gotoSalesForeUpdate1Report();
        controller.gotoSales2();
        controller.gotoSales3();
        controller.gotoSalesUpdate3Report();
        controller.gotoSales4();
        controller.gotoSalesReport();
        
    }
    
    @IsTest(SeeAllData=false)
    global static void testHomeHeaderController () {
        Account acc = new Account(Site='www.fff.com',AccountNumber='1243',Grupo_de_cuentas__c='US01 - Domestic Customers',Name='JERE', Nome_Fantasia__c = 'JRERE', CodigoSAP__c='451254'); insert acc;
        SiteUser__c su = new SiteUser__c(Email__c='jere@dm.com', Password__c='123'); insert su;
        SiteUserAccount__c suacc = new SiteUserAccount__c(SiteUser__c=su.Id,Account__c=acc.Id, Active__c=true); insert suacc;
        SiteUserSession__c susess = new SiteUserSession__c(Marca__c='GDM', Safra__c='16/2016',SiteUser__c=su.Id); insert susess;

        aSiteHomeController controller0 = new aSiteHomeController();
        controller0.validate();
                        
        PageReference pageRef = Page.aSiteHome;
        pageRef.getParameters().put('token',susess.Id);      
        Test.setCurrentPageReference(pageRef);

        controller0.validate();
        controller0.getUser();

        pageRef = new PageReference('/aSiteAppendix2');
        pageRef.getParameters().put('token',susess.Id);      
        Test.setCurrentPageReference(pageRef);

        aSiteHeaderController controller = new aSiteHeaderController();
        controller.getUser();
        controller.gotoDashboard();
        controller.getBrand();
            
        controller.gotoProfile();
        controller.gotoAppend1();
        controller.gotoContract();
        
        controller.gotoUploadFile();
        controller.gotoDataAnalytics();
        controller.gotoSeedTracking();
            
        controller.closeSession();
        controller.gotoUploadFile();
                
    }
        
    @IsTest(SeeAllData=false)
    global static void testHeaderProdReportController () {
        Account acc = new Account(Site='www.fff.com',AccountNumber='1243',Grupo_de_cuentas__c='US01 - Domestic Customers',Name='JERE', Nome_Fantasia__c = 'JRERE', CodigoSAP__c='451254'); insert acc;
        SiteUser__c su = new SiteUser__c(Email__c='jere@dm.com', Password__c='123'); insert su;
        SiteUserAccount__c suacc = new SiteUserAccount__c(SiteUser__c=su.Id,Account__c=acc.Id, Active__c=true); insert suacc;
        SiteUserSession__c susess = new SiteUserSession__c(Marca__c='GDM', Safra__c='16/2016',Production_season__c='20/2020',SiteUser__c=su.Id); insert susess;

        PageReference pageRef = Page.aSiteHome;
        pageRef = new PageReference('/aSiteAppendix2');
        pageRef.getParameters().put('token',susess.Id);      
        Test.setCurrentPageReference(pageRef);

        aSiteHeaderController controller = new aSiteHeaderController();
        controller.gotoProdFinalReport();
            
        controller.gotoProd5Report();
        controller.gotoProd4Report();            
        controller.gotoProd3Report();
        controller.gotoProd2Report();
        controller.gotoProd1Report();
        
        Map<String,Id> rTypes = Opp_Utils.cargarRecordTypesOportunidades();
        Map<String,String> rTypesD = USAUtils.cargarRecordTypesOppbyDevName();
        String type = 'Production Update 1';
        Opportunity opp = new Opportunity(RecordTypeId=rTypes.get(rTypesD.get('Production_Report')),AccountId=acc.Id,Name='NEW',Safra__c='20/2020',Marca__c='GDM',CloseDate=system.today(),Stagename='Editable',Type=type); insert opp;
        controller.gotoProd1Report();
        
        opp.type = 'Production Update 2'; update opp;
        controller.gotoProd2Report();
        
        opp.type = 'Production Update 3'; update opp;
        controller.gotoProd3Report();

        controller.closeSession();
        controller.gotoUploadFile();
                
    }
    
    @IsTest(SeeAllData=false)
    global static void testHeaderSalesReportController () {
        Account acc = new Account(Site='www.fff.com',AccountNumber='1243',Grupo_de_cuentas__c='US01 - Domestic Customers',Name='JERE', Nome_Fantasia__c = 'JRERE', CodigoSAP__c='451254'); insert acc;
        SiteUser__c su = new SiteUser__c(Email__c='jere@dm.com', Password__c='123'); insert su;
        SiteUserAccount__c suacc = new SiteUserAccount__c(SiteUser__c=su.Id,Account__c=acc.Id, Active__c=true); insert suacc;
        SiteUserSession__c susess = new SiteUserSession__c(Marca__c='GDM', Safra__c='20/2020',SiteUser__c=su.Id,Sales_Season__c='20/2020'); insert susess;

        PageReference pageRef = Page.aSiteHome;
        pageRef = new PageReference('/aSiteAppendix2');
        pageRef.getParameters().put('token',susess.Id);      
        Test.setCurrentPageReference(pageRef);

        aSiteHeaderController controller = new aSiteHeaderController();
        controller.gotoSalesReport();
            
        controller.gotoSalesUpdate4Report();
        controller.gotoSalesUpdate3Report();
        controller.gotoSalesForeUpdate2Report();
        controller.gotoSalesForeUpdate1Report();


        Map<String,Id> rTypes = Opp_Utils.cargarRecordTypesOportunidades();
        Map<String,String> rTypesD = USAUtils.cargarRecordTypesOppbyDevName();
        String type = 'Sales Forecast Update 1';
        Opportunity opp = new Opportunity(RecordTypeId=rTypes.get(rTypesD.get('Sales_Report')),AccountId=acc.Id,Name='NEW',Safra__c='20/2020',Marca__c='GDM',CloseDate=system.today(),Stagename='Editable',Type=type); insert opp;
        controller.gotoSalesForeUpdate1Report();
        
        opp.type = 'Sales Forecast Update 2';
        update opp;
        controller.gotoSalesForeUpdate2Report();
        
        opp.type = 'Sales Forecast Update 3';
        update opp;
        controller.gotoSalesUpdate3Report();
                
        opp.type = 'Sales Forecast Update 4';
        update opp;
        controller.gotoSalesUpdate3Report();

        opp.type = 'Final Sales Report';
        update opp;
        controller.gotoSalesReport();
            
        controller.closeSession();
        controller.gotoUploadFile();
                
    }
    
}