force-app/main/default/objects/Account/fields/CodigoSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoSAP__c</fullName>
    <label>Account Sap Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_CO__c/Centro_de_CO__c.object-meta.xml
<CustomObject>
    <label>Centro de CO</label>
    <nameField>
        <label>CO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros de CO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Centro_de_CO_Item__c/Centro_de_CO_Item__c.object-meta.xml
<CustomObject>
    <label>Centro de CO Item</label>
    <nameField>
        <label>Nombre de Centro de CO</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centro de CO Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Centro_de_CO_Item__c/fields/Centro_de_CO__c.field-meta.xml
<CustomField>
    <fullName>Centro_de_CO__c</fullName>
    <label>Centro de CO</label>
    <referenceTo>Centro_de_CO__c</referenceTo>
    <relationshipLabel>Centro de CO Items</relationshipLabel>
    <relationshipName>Centro_de_CO_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact of Sale</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades (Contact of Sale)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Branch Name)</relationshipLabel>
    <relationshipName>Opportunities_Branchs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_of_Shipping__c.field-meta.xml
<CustomField>
    <fullName>Contact_of_Shipping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact of Shipping</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Ship_To__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact of Shipping)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/docRel__c.field-meta.xml
<CustomField>
    <fullName>docRel__c</fullName>
    <label>docRel</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ship To)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Centro_de_despacho__c.field-meta.xml
<CustomField>
    <fullName>Centro_de_despacho__c</fullName>
    <label>Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>E001 - B&amp;B - CHAMPAIGN</fullName>
            </value>
            <value>
                <fullName>E002 - B&amp;B - GIBSON CITY</fullName>
            </value>
            <value>
                <fullName>E003 - B&amp;B - JONESBORO</fullName>
            </value>
            <value>
                <fullName>E004 – B&amp;B - PRO AG EARLY</fullName>
            </value>
            <value>
                <fullName>E004 – B&amp;B - PRO AG LATE</fullName>
            </value>
            <value>
                <fullName>U001 - GDM - CHAMPAIGN</fullName>
            </value>
            <value>
                <fullName>U002 - GDM - GIBSON CITY</fullName>
            </value>
            <value>
                <fullName>U003 - GDM - JONESBORO</fullName>
            </value>
            <value>
                <fullName>U004 - GDM - PRO AG EARLY</fullName>
            </value>
            <value>
                <fullName>U004 - GDM - PRO AG LATE</fullName>
            </value>
            <value>
                <fullName>U005 - GDM - HUTCHINSON</fullName>
            </value>
            <value>
                <fullName>U006 - GDM - DES MOINES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/CostOrder__c.field-meta.xml
<CustomField>
    <fullName>CostOrder__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CostOrder</label>
    <referenceTo>Centro_de_CO_Item__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DocRel__c.field-meta.xml
<CustomField>
    <fullName>DocRel__c</fullName>
    <label>DocRel</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Freight_Charge__c.field-meta.xml
<CustomField>
    <fullName>Freight_Charge__c</fullName>
    <label>Freight Charge</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Billable</fullName>
            </value>
            <value>
                <fullName>Non Billable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Motivo_de_Rechazo__c.field-meta.xml
<CustomField>
    <fullName>Motivo_de_Rechazo__c</fullName>
    <label>Rejection Reason</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Pallet_Charge__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Charge__c</fullName>
    <label>Pallet Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Shipping_Costs__c.field-meta.xml
<CustomField>
    <fullName>Shipping_Costs__c</fullName>
    <label>Shipping Costs</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Waiting_Sync_To_Delete__c.field-meta.xml
<CustomField>
    <fullName>Waiting_Sync_To_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Waiting Sync To Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Centro_de_despacho__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEVE-DEVELOPMENT</fullName>
            </value>
            <value>
                <fullName>COME-COMERCIAL</fullName>
            </value>
            <value>
                <fullName>PROD-PRODUCTION</fullName>
            </value>
            <value>
                <fullName>RESE-RESEARCH</fullName>
            </value>
            <value>
                <fullName>ADM -ADMINISTRATION</fullName>
            </value>
            <value>
                <fullName>W001-CHAMPAIGN WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>W001-GDM - HUTCHINSON</fullName>
            </value>
            <value>
                <fullName>W001-GDM - DES MOINES</fullName>
            </value>
            <value>
                <fullName>W001-GIBSON CITY WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>W001-JONESBORO WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>W001-PRO AG WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>T001-KAUFFMAN</fullName>
            </value>
            <value>
                <fullName>T002-STRATTON SEED-AR</fullName>
            </value>
            <value>
                <fullName>T003-SGD</fullName>
            </value>
            <value>
                <fullName>T004-PLANTATION SEED</fullName>
            </value>
            <value>
                <fullName>T005-GENERATION FARMS</fullName>
            </value>
            <value>
                <fullName>T006-JMR FARMS</fullName>
            </value>
            <value>
                <fullName>T007-STRATTON - ANNISTON</fullName>
            </value>
            <value>
                <fullName>T001-PRO AG CHB (ARG)</fullName>
            </value>
            <value>
                <fullName>TC01-Shoffner Comercial</fullName>
            </value>
            <value>
                <fullName>TP01-Shoffner Production</fullName>
            </value>
            <value>
                <fullName>TC02-CRV Comercial</fullName>
            </value>
            <value>
                <fullName>TP02-CRV Production</fullName>
            </value>
            <value>
                <fullName>TC03-Burrus Seed Comercial</fullName>
            </value>
            <value>
                <fullName>TP03-Burrus Seed Production</fullName>
            </value>
            <value>
                <fullName>TC05-CPS Comercial</fullName>
            </value>
            <value>
                <fullName>TP05-CPS Production</fullName>
            </value>
            <value>
                <fullName>TC06-Remington Wal.Comercial</fullName>
            </value>
            <value>
                <fullName>TP06-Remington Wal.Production</fullName>
            </value>
            <value>
                <fullName>TC07-Stratton AR Comercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Codigo_Material_SAP__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Material_SAP__c</fullName>
    <label>SAP Product ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BAG 140K</fullName>
            </value>
            <value>
                <fullName>BAG 40(140K)</fullName>
            </value>
            <value>
                <fullName>LB</fullName>
            </value>
            <value>
                <fullName>BAGS BY LBS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OpportunityDAO.cls
public class OpportunityDAO {
    private static OpportunityDAO instance = new OpportunityDAO();
    private OpportunityDAO() {
    }

    public static OpportunityDAO getInstance(){
        return instance;
    }

    Map<String, List<OpportunityLineItem>> mapOppLineItemCache = new Map<String, List<OpportunityLineItem>>();

    public List<OpportunityLineItem> getOppLineItemsByOppId(String idOpp){
        if(Test.isRunningTest() && mapOppLineItemCache.containsKey(idOpp)){
            return mapOppLineItemCache.get(idOpp);
        }
        List<OpportunityLineItem> lstOppLineItem = getOppLineItemsByListOppId(new List<String>{idOpp});
        mapOppLineItemCache.put(idOpp, lstOppLineItem);
        return lstOppLineItem;
    }

    public List<Opportunity> getOppInfoByListId(List<String> lstIdOpp){
        String queryPlus = 'RecordType.DeveloperName';
        return aSiteUtils.queryResults1(Opportunity.SObjectType, queryPlus ,'Id = :v1', lstIdOpp);

    }

    public List<OpportunityLineItem> getOppLineItemsByListOppId(List<String> lstIdOpp){
        String queryPlus = 'Opportunity.RecordType.DeveloperName, Opportunity.RecordTypeId, Product2.Name, Product2.Codigo_material_SAP__c, Product2.Unidade__c, Product2.ProductCode';
        return aSiteUtils.queryResults1(OpportunityLineItem.SObjectType, queryPlus ,'OpportunityId = :v1', lstIdOpp);
        
    }

    public List<Opportunity> getOpportunityByListId(List<String> idsOpps){
        String queryPlus = ' Contact_of_Shipping__r.Name, Attendance__r.Email, Attendance__r.Name, Ship_To__r.CodigoSAP__c,' +
            				' Account.Name, Branch_Name__r.CodigoSAP__c, Account.CodigoSAP__c, Owner.Name, Account.Phone,' +
            				' Owner.Sap_Sales_Office__c, Owner.Grupo_de_Vendedores__c, RecordType.DeveloperName, (SELECT Id,' +
            					' Name, Quantity, Product2Id, Product2.Name, Motivo_de_rechazo__c, DocRel__c, Waiting_Sync_To_Delete__c,' +
            					' Material__c, CostOrder__r.Centro_de_CO__c, CostOrder__c, Posicion_Relativa_Consign__c, Comments__c,' +
            					' Product2.ProductCode, Product2.Unidade__c, Product2.Codigo_material_SAP__c, ListPrice, UnitPrice, Product2.Family, Freight_Charge__c, ' +
            					' Shipping_Costs__c, Pallet_Charge__c, OpportunityId, TotalPrice, Warehouse__c, Centro_de_Despacho__c FROM OpportunityLineItems)';
        return aSiteUtils.queryResults1(Opportunity.SObjectType, queryPlus ,'Id = :v1', idsOpps);

    }
    
    public List<OpportunityLineItem> getOpportunityLineItemByListId(List<String> idsPrdOpp){
        String queryPlus = 'Opportunity.RecordType.DeveloperName, Opportunity.RecordTypeId, Product2.Name, Product2.Unidade__c, Product2.Codigo_material_SAP__c';
        return aSiteUtils.queryResults1(OpportunityLineItem.SObjectType, queryPlus ,'OpportunityId = :v1', idsPrdOpp);
        
    }    
}