force-app/main/default/objects/Account/fields/CodigoSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoSAP__c</fullName>
    <label>Account Sap Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuracion_USA__c/Configuracion_USA__c.object-meta.xml
<CustomObject>
    <label>Admin Setting</label>
    <nameField>
        <label>Admin Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admin Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Configuracion_USA__c/fields/link_intra_dm__c.field-meta.xml
<CustomField>
    <fullName>link_intra_dm__c</fullName>
    <label>Link Sap Des</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Configuracion_USA__c/fields/RecordType_for_OppNro__c.field-meta.xml
<CustomField>
    <fullName>RecordType_for_OppNro__c</fullName>
    <label>RecordType for OppNro</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Branch Name)</relationshipLabel>
    <relationshipName>Opportunities_Branchs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Condicion_de_Pago__c.field-meta.xml
<CustomField>
    <fullName>Condicion_de_Pago__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZC05 Net 30 days from shipping date</fullName>
                <default>true</default>
                <label>Net 30 days from shipping date</label>
            </value>
            <value>
                <fullName>ZC04 Net 20 days from shipping date</fullName>
                <label>Net 20 days from shipping date</label>
            </value>
            <value>
                <fullName>ZC05 - S4 test Condition</fullName>
                <label>S4 test Condition</label>
            </value>
            <value>
                <fullName>ZC00 Due Upon Receipt</fullName>
                <label>Due Upon Receipt</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Nro_Pedido_SAP__c.field-meta.xml
<CustomField>
    <fullName>Nro_Pedido_SAP__c</fullName>
    <externalId>true</externalId>
    <label>SAP Order Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ship To)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZO13 - Export Order</fullName>
            </value>
            <value>
                <fullName>ZO14 – Local Order</fullName>
                <default>true</default>
                <label>ZO14 – Local Order - Seeds</label>
            </value>
            <value>
                <fullName>ZO15 - Local Order</fullName>
                <label>ZO15 - Local Order - Royalty</label>
            </value>
            <value>
                <fullName>Customer Goal</fullName>
            </value>
            <value>
                <fullName>Budget</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Production_Report.recordType-meta.xml
<RecordType>
    <fullName>Production_Report</fullName>
    <active>true</active>
    <businessProcess>Portal Reports</businessProcess>
    <label>Production Report</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Sale.recordType-meta.xml
<RecordType>
    <fullName>Sale</fullName>
    <active>true</active>
    <businessProcess>Invoice</businessProcess>
    <label>Sale</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Sales_Report.recordType-meta.xml
<RecordType>
    <fullName>Sales_Report</fullName>
    <active>true</active>
    <businessProcess>Portal Reports</businessProcess>
    <label>Sales Report</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Centro_de_despacho__c.field-meta.xml
<CustomField>
    <fullName>Centro_de_despacho__c</fullName>
    <label>Plant</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>E001 - B&amp;B - CHAMPAIGN</fullName>
            </value>
            <value>
                <fullName>E002 - B&amp;B - GIBSON CITY</fullName>
            </value>
            <value>
                <fullName>E003 - B&amp;B - JONESBORO</fullName>
            </value>
            <value>
                <fullName>E004 – B&amp;B - PRO AG EARLY</fullName>
            </value>
            <value>
                <fullName>E004 – B&amp;B - PRO AG LATE</fullName>
            </value>
            <value>
                <fullName>U001 - GDM - CHAMPAIGN</fullName>
            </value>
            <value>
                <fullName>U002 - GDM - GIBSON CITY</fullName>
            </value>
            <value>
                <fullName>U003 - GDM - JONESBORO</fullName>
            </value>
            <value>
                <fullName>U004 - GDM - PRO AG EARLY</fullName>
            </value>
            <value>
                <fullName>U004 - GDM - PRO AG LATE</fullName>
            </value>
            <value>
                <fullName>U005 - GDM - HUTCHINSON</fullName>
            </value>
            <value>
                <fullName>U006 - GDM - DES MOINES</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Pallet_Charge__c.field-meta.xml
<CustomField>
    <fullName>Pallet_Charge__c</fullName>
    <label>Pallet Charge</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/sapCreditCheckStatusTest.cls
@isTest
private class sapCreditCheckStatusTest {
    @isTest static void test_method_one() {
        Test.startTest();
        
        Configuracion_USA__c co = new Configuracion_USA__c(FC_mandante_SAP__c='200',RecordType_for_OppNro__c='Sales_Report,Production_Report',link_intra_dm__c='', Link_Sap_Prod__c='', Link_Sap_QA__c='');
        insert co;
       
        Account account = new Account();
        account.Name = 'AGENTE';
        account.CodigoSAP__c = '12456554';
        insert account;    
        
        Product2 produto002           = new Product2();
        produto002.Name               = 'ROYALTY';
        produto002.ProductCode        = '40026418';
        produto002.isActive           = true; 
        insert produto002;
    
        Product2 produto_2           = new Product2();
        produto_2.Name               = 'SEED';
        produto_2.ProductCode        = '40026418';
        produto_2.isActive           = true;
        insert produto_2;
    
        Pricebook2 price1                 = new Pricebook2();
        price1.Name                       = 'Teste';
        price1.Description                = 'Teste';
        price1.IsActive                   = true;
    
        insert price1;
    
        PricebookEntry priceBookEntry1 = new PricebookEntry();
        priceBookEntry1.Pricebook2Id = Test.getStandardPricebookId();   
        priceBookEntry1.Product2Id = produto_2.id;
        priceBookEntry1.UseStandardPrice = false;
        priceBookEntry1.IsActive = true;
        priceBookEntry1.UnitPrice = 100.00;
    
        insert priceBookEntry1;
    
        Opportunity opp = new Opportunity();
        opp.RecordTypeID = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Sale').getRecordTypeId();
        opp.Safra__c = '19/2019';    
        opp.AccountId = account.Id;
        opp.Ship_To__c = account.Id;
        //opp.Branch_name__c = account2.Id; 
        opp.Name   = 'UnitTest';
        opp.Tipo__c = 'ZPLO - Local Order';
        opp.StageName  = 'Locked by Credit'; 
        opp.CloseDate = System.today()+60;
        opp.Condicion_de_Pago__c = 'ZC05 Net 30 days from shipping date';
        opp.Type = 'Z17 - PARENT SEED';
        opp.Nro_Pedido_SAP__c = '00004584525';
        opp.Pricebook2Id = Test.getStandardPricebookId();
    
        insert opp;
    
        OpportunityLineItem oppli1 = new OpportunityLineItem();
        oppli1.OpportunityId = opp.id;
        oppli1.PricebookEntryId = priceBookEntry1.id;
        oppli1.UnitPrice = 1;
        oppli1.Quantity = 40;
        oppli1.Pallet_Charge__c = 10;
        oppli1.Centro_de_Despacho__c = 'UD01';
    
        insert oppli1;
    
        update opp;
    
        sapCreditStatus_caller.consultarOpps();
        Test.stopTest();
    }
}