force-app/main/default/objects/Account/fields/CodigoSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoSAP__c</fullName>
    <label>Account Sap Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Grupo_de_Cuentas__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Cuentas__c</fullName>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>US01 - Domestic Customers</fullName>
            </value>
            <value>
                <fullName>US02 - Foreing Customers</fullName>
                <label>US02 - Foreign Customers</label>
            </value>
            <value>
                <fullName>US03 - Ship To</fullName>
            </value>
            <value>
                <fullName>US04 - Branches</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nome_fantasia__c.field-meta.xml
<CustomField>
    <fullName>Nome_fantasia__c</fullName>
    <label>Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPOS_Customer_Report__c/GPOS_Customer_Report__c.object-meta.xml
<CustomObject>
    <label>GPOS Customer Report</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GPOS Customer Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GPOS_Customer_Report__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GPOS Customer Reports</relationshipLabel>
    <relationshipName>GPOS_Customer_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de SiteUser</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteUser__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SiteUsers</relationshipLabel>
    <relationshipName>SiteUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteUserAccount__c/SiteUserAccount__c.object-meta.xml
<CustomObject>
    <label>SiteUserAccount</label>
    <nameField>
        <label>SiteUserAccount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUserAccounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteUserSession__c/SiteUserSession__c.object-meta.xml
<CustomObject>
    <label>SiteUserSession</label>
    <nameField>
        <displayFormat>S{00000000}</displayFormat>
        <label>SiteUserSession Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SiteUserSessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteUserSession__c/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SiteUserSession__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/classes/aSiteUploadFileControllerTest.cls
@isTest
public class aSiteUploadFileControllerTest {
    @isTest
    public static void aSiteUploadFileControllerTest() {
        aSiteUploadFileController controller = new aSiteUploadFileController();
        controller.csvFile.Title = 'Partner GPOS Template';
        controller.csvFile.VersionData = Blob.valueOf('1234');
        Account acc = new Account(Site='www.fff.com',AccountNumber='1243',Grupo_de_cuentas__c='US01 - Domestic Customers',Name='JERE', Nome_Fantasia__c = 'JRERE', CodigoSAP__c='451254'); insert acc;
        SiteUser__c su = new SiteUser__c(Email__c='jere@dm.com', Password__c='123456'); insert su;
        SiteUserAccount__c suacc = new SiteUserAccount__c(SiteUser__c=su.Id,Account__c=acc.Id, Active__c=true); insert suacc;
        SiteUserSession__c susess = new SiteUserSession__c(Marca__c='GDM', Safra__c='18/2018',SiteUser__c=su.Id); insert susess;
        PageReference pageRef = Page.aSiteUploadFile;
        pageRef.getParameters().put('token',susess.Id);      
        Test.setCurrentPageReference(pageRef);

        Test.startTest();
        controller.validate();
        controller.doUpload();
        Test.stopTest();

        List<GPOS_Customer_Report__c> reports = [SELECT Id, Name FROM GPOS_Customer_Report__c];
        System.assertEquals(1, reports.size(), 'There should be only 1 GPOS Report/File but there are ' + reports.size());
        System.assertNotEquals(controller.csvFile.Title, reports[0].Name, 'Name should have change');
        
    }
}