force-app/main/default/objects/Account/fields/CodigoSAP__c.field-meta.xml
<CustomField>
    <fullName>CodigoSAP__c</fullName>
    <label>Account Sap Number</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Grupo_de_Cuentas__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Cuentas__c</fullName>
    <label>Account Group</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>US01 - Domestic Customers</fullName>
            </value>
            <value>
                <fullName>US02 - Foreing Customers</fullName>
                <label>US02 - Foreign Customers</label>
            </value>
            <value>
                <fullName>US03 - Ship To</fullName>
            </value>
            <value>
                <fullName>US04 - Branches</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Nome_fantasia__c.field-meta.xml
<CustomField>
    <fullName>Nome_fantasia__c</fullName>
    <label>Company Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Credit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High Risk</fullName>
                <color>#FF0000</color>
                <label>Finance Warning - Review Account</label>
            </value>
            <value>
                <fullName>Ok</fullName>
                <default>true</default>
                <label>Satisfactory</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/General_Settings__c/General_Settings__c.object-meta.xml
<CustomObject>
    <description>Object to set settings globally. This should only be enabled for Administrators</description>
    <label>General Settings</label>
    <nameField>
        <label>General Settings</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>General Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Status__c/Inventory_Status__c.object-meta.xml
<CustomObject>
    <label>Inventory Status</label>
    <nameField>
        <label>Inventory Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Inventory Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Inventory_Status__c/fields/Internal_Status__c.field-meta.xml
<CustomField>
    <fullName>Internal_Status__c</fullName>
    <label>Internal Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Inventory_Status__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Status__c</fullName>
    <label>Inventory Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Sale.recordType-meta.xml
<RecordType>
    <fullName>Sale</fullName>
    <active>true</active>
    <businessProcess>Invoice</businessProcess>
    <label>Sale</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Customer_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Status__c</fullName>
    <label>Customer Status</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Internal_Status__c.field-meta.xml
<CustomField>
    <fullName>Internal_Status__c</fullName>
    <label>Internal Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>In field</fullName>
            </value>
            <value>
                <fullName>In warehouse</fullName>
            </value>
            <value>
                <fullName>In transit</fullName>
            </value>
            <value>
                <fullName>Delivered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Inventory_Status__c.field-meta.xml
<CustomField>
    <fullName>Inventory_Status__c</fullName>
    <label>Inventory Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Variedades que pueden incluirse en el contrato de multiplicacion</description>
    <label>Variety Name DO NOT USE</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variety Name</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/Seed_Tracking__c.object-meta.xml
<CustomObject>
    <label>Seed Track</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Seed Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seed Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Seed_Tracking__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Seed Tracks</relationshipLabel>
    <relationshipName>Seed_Tracks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Sale_Order__c.field-meta.xml
<CustomField>
    <fullName>Sale_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sale Order</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seed Tracks</relationshipLabel>
    <relationshipName>Seed_Tracks</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <label>Variety</label>
    <nameField>
        <label>Variety Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Varieties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SeedTrackingProcessTest.cls
@IsTest
public class SeedTrackingProcessTest {
	/*@isTest Not working on production
    public static void ApprovalProcessSetTest(){
        Account acc = new Account(Site='www.fff.com',AccountNumber='1243',Grupo_de_cuentas__c='US01 - Domestic Customers',Name='JERE', Nome_Fantasia__c = 'JRERE', CodigoSAP__c='451254'); insert acc;
        
        Categoria__c cat = new Categoria__c(Name='BASIC'); insert cat;
        Variedad__c var = new Variedad__c(Name='USG'); insert var;
        Product2 p1 = new Product2(Name='3810', Variedade__c=var.Id,Categ__c=cat.Id,Family='Royalty x Basica'); insert p1;
        Pricebook2 pb2 = new Pricebook2(Name='Portal Pricelist',isActive=true); insert pb2;
        
        PricebookEntry pStd_aux = new PricebookEntry(pricebook2Id=Test.getStandardPricebookId(), Product2Id=p1.id, UnitPrice=0, isActive=true, useStandardPrice=false); insert pStd_aux;
        PricebookEntry pbe = new PricebookEntry(Product2Id=p1.Id,UnitPrice=2,Pricebook2Id=pb2.Id,isActive=true); insert pbe;
        
        RecordType rt = [SELECT Id FROM RecordType WHERE Name = 'Stock per plant' and SobjectType = 'Opportunity'];

        Opportunity opp1 = new Opportunity(RecordTypeId=rt.Id,AccountId=acc.Id,Name='NEW',Safra__c='20/2020',Marca__c='GDM', CloseDate=system.today(),Stagename='Approved'); insert opp1;
        OpportunityLineItem opp1Item = new OpportunityLineItem(Categoria__c=cat.Id,PricebookEntryId=pbe.Id,OpportunityId=opp1.Id,UnitPrice=1,Quantity=1); insert opp1Item;

        List<Inventory_Status__c> invStatus = [SELECT Id FROM Inventory_Status__c];
        System.assertEquals(0, invStatus.size());

        Test.startTest();
        opp1Item.Internal_Status__c = 'Test Status';
        update opp1Item;
        Test.stopTest();

        invStatus = [SELECT Id FROM Inventory_Status__c];
        System.assertEquals(1, invStatus.size()); // This means there is a new approval process for this object
    }*/

	@isTest // Need this to deploy a trigger. Test is not working
	public static void InventoryStatusTriggerTest() {
		Inventory_Status__c is = new Inventory_Status__c();
		insert is;
	}

	@isTest
	public static void SeedTrackGeneralTest() {
		Account acc = new Account(
			Site = 'www.fff.com',
			AccountNumber = '1243',
			Grupo_de_cuentas__c = 'US01 - Domestic Customers',
			Name = 'JERE',
			Nome_Fantasia__c = 'JRERE',
			CodigoSAP__c = '451254'
		);
		insert acc;
		General_Settings__c gs = new General_Settings__c();
		insert gs;

		Categoria__c cat = new Categoria__c(Name = 'BASIC');
		insert cat;
		Variedad__c var = new Variedad__c(Name = 'USG');
		insert var;
		Product2 p1 = new Product2(Name = '3810', Variedade__c = var.Id, Categ__c = cat.Id, Family = 'Royalty x Basica');
		insert p1;
		Pricebook2 pb2 = new Pricebook2(Name = 'Portal Pricelist', isActive = true);
		insert pb2;

		PricebookEntry pStd_aux = new PricebookEntry(
			pricebook2Id = Test.getStandardPricebookId(),
			Product2Id = p1.id,
			UnitPrice = 0,
			isActive = true,
			useStandardPrice = false
		);
		insert pStd_aux;
		PricebookEntry pbe = new PricebookEntry(Product2Id = p1.Id, UnitPrice = 2, Pricebook2Id = pb2.Id, isActive = true);
		insert pbe;

		RecordType rtStock = [SELECT Id FROM RecordType WHERE Name = 'Stock per plant' AND SobjectType = 'Opportunity'];

		Opportunity opp1 = new Opportunity(
			RecordTypeId = rtStock.Id,
			AccountId = acc.Id,
			Name = 'NEW',
			Safra__c = '20/2020',
			Marca__c = 'GDM',
			CloseDate = system.today(),
			Stagename = 'Approved',
			Pricebook2Id = pb2.Id,
			Type = 'Z6 - ROYALTY'
		);
		insert opp1;
		OpportunityLineItem opp1Item = new OpportunityLineItem(
			PricebookEntryId = pbe.Id,
			OpportunityId = opp1.Id,
			UnitPrice = 1,
			Quantity = 1,
			Inventory_Status__c = 'Approved',
			Customer_Status__c = 'TestStatus'
		);
		insert opp1Item;

		RecordType rtSale = [SELECT Id FROM RecordType WHERE Name = 'Sale' AND SobjectType = 'Opportunity'];

		Opportunity opp2 = new Opportunity(
			RecordTypeId = rtSale.Id,
			AccountId = acc.Id,
			Name = 'NEW',
			Safra__c = '20/2020',
			Marca__c = 'GDM',
			CloseDate = system.today(),
			Stagename = 'Editable',
			Pricebook2Id = pb2.Id,
			Type = 'Z6 - ROYALTY'
		);
		insert opp2;
		OpportunityLineItem opp2Item = new OpportunityLineItem(
			PricebookEntryId = pbe.Id,
			OpportunityId = opp2.Id,
			UnitPrice = 1,
			Quantity = 1
		);
		insert opp2Item;

		List<Seed_Tracking__c> sTracks = [SELECT Id FROM Seed_Tracking__c];
		System.assertEquals(0, sTracks.size());

		Test.startTest();
		opp2.StageName = 'Approved';
		update opp2;
		Test.stopTest();

		sTracks = [SELECT Id, Status__c, Sale_Order__c, Product__c FROM Seed_Tracking__c];
		for (Seed_Tracking__c st : sTracks) {
			System.assertEquals(opp1Item.Customer_Status__c, st.Status__c);
		}
		System.assertEquals(1, sTracks.size());
	}

	@isTest
	public static void SeedTrackGeneral2Test() {
		Account acc = new Account(
			Site = 'www.fff.com',
			AccountNumber = '1243',
			Grupo_de_cuentas__c = 'US01 - Domestic Customers',
			Name = 'JERE',
			Nome_Fantasia__c = 'JRERE',
			CodigoSAP__c = '451254'
		);
		insert acc;
		General_Settings__c gs = new General_Settings__c();
		insert gs;

		Categoria__c cat = new Categoria__c(Name = 'BASIC');
		insert cat;
		Variedad__c var = new Variedad__c(Name = 'USG');
		insert var;
		Product2 p1 = new Product2(Name = '3810', Variedade__c = var.Id, Categ__c = cat.Id, Family = 'Royalty x Basica');
		insert p1;
		Pricebook2 pb2 = new Pricebook2(Name = 'Portal Pricelist', isActive = true);
		insert pb2;

		PricebookEntry pStd_aux = new PricebookEntry(
			pricebook2Id = Test.getStandardPricebookId(),
			Product2Id = p1.id,
			UnitPrice = 0,
			isActive = true,
			useStandardPrice = false
		);
		insert pStd_aux;
		PricebookEntry pbe = new PricebookEntry(Product2Id = p1.Id, UnitPrice = 2, Pricebook2Id = pb2.Id, isActive = true);
		insert pbe;

		RecordType rtStock = [SELECT Id FROM RecordType WHERE Name = 'Stock per plant' AND SobjectType = 'Opportunity'];

		Opportunity opp1 = new Opportunity(
			RecordTypeId = rtStock.Id,
			AccountId = acc.Id,
			Name = 'NEW',
			Safra__c = '20/2020',
			Marca__c = 'GDM',
			CloseDate = system.today(),
			Stagename = 'Approved',
			Pricebook2Id = pb2.Id,
			Type = 'Z6 - ROYALTY'
		);
		insert opp1;
		OpportunityLineItem opp1Item = new OpportunityLineItem(
			PricebookEntryId = pbe.Id,
			OpportunityId = opp1.Id,
			UnitPrice = 1,
			Quantity = 1,
			Inventory_Status__c = 'Pending',
			Customer_Status__c = 'TestStatus'
		);
		insert opp1Item;

		RecordType rtSale = [SELECT Id FROM RecordType WHERE Name = 'Sale' AND SobjectType = 'Opportunity'];

		Opportunity opp2 = new Opportunity(
			RecordTypeId = rtSale.Id,
			AccountId = acc.Id,
			Name = 'NEW',
			Safra__c = '20/2020',
			Marca__c = 'GDM',
			CloseDate = system.today(),
			Stagename = 'Editable',
			Pricebook2Id = pb2.Id,
			Type = 'Z6 - ROYALTY'
		);
		insert opp2;
		OpportunityLineItem opp2Item = new OpportunityLineItem(
			PricebookEntryId = pbe.Id,
			OpportunityId = opp2.Id,
			UnitPrice = 1,
			Quantity = 1
		);
		insert opp2Item;

		opp2.StageName = 'Approved';
		update opp2;

		List<Seed_Tracking__c> sTracks = [SELECT Id, Status__c, Sale_Order__c, Product__c FROM Seed_Tracking__c];
		for (Seed_Tracking__c st : sTracks) {
			System.assertEquals(null, st.Status__c);
		}

		Test.startTest();
		opp1Item.Inventory_Status__c = 'Approved';
		update opp1Item;
		Test.stopTest();

		//sTracks = [SELECT Id, Status__c, Sale_Order__c, Product__c FROM Seed_Tracking__c];
		//for(Seed_Tracking__c st : sTracks) {
		//    System.assertEquals(opp1Item.Customer_Status__c, st.Status__c);
		//}

		System.assertEquals(1, sTracks.size());
	}
}