force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GPOS_Customer_Report__c/GPOS_Customer_Report__c.object-meta.xml
<CustomObject>
    <label>GPOS Customer Report</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GPOS Customer Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GPOS_Customer_Report__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GPOS Customer Reports</relationshipLabel>
    <relationshipName>GPOS_Customer_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GPOS_Customer_Report__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/GPOS_Customer_Report__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GPOS_User__mdt/GPOS_User__mdt.object-meta.xml
<CustomObject>
    <label>GPOS User</label>
    <pluralLabel>GPOS Users</pluralLabel>
</CustomObject>

force-app/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de SiteUser</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteUser__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SiteUsers</relationshipLabel>
    <relationshipName>SiteUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>SiteUsers</relationshipLabel>
    <relationshipName>SiteUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteUserSession__c/SiteUserSession__c.object-meta.xml
<CustomObject>
    <label>SiteUserSession</label>
    <nameField>
        <displayFormat>S{00000000}</displayFormat>
        <label>SiteUserSession Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SiteUserSessions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/aSiteUploadFileController.cls
global class aSiteUploadFileController {
	private String token;
	private SiteUser__c logUser { get; set; }
	public Account activeAccount { get; set; }
	public SiteUserSession__c activeSession { get; set; }
	public String language { get; set; }
	public String titulo { get; set; }
	public ContentVersion csvFile { get; set; }
	public Boolean renderFinishedUpload { get; set; }
	public String userName { get; set; }
	public String fileName { get; set; }
	public SiteUser__c getUser() {
		return logUser;
	}
	public Account getAccount() {
		return activeAccount;
	}

	global aSiteUploadFileController() {
		try {
			language = [SELECT id, LanguageLocaleKey FROM User WHERE id = :UserInfo.getUserId()].LanguageLocaleKey;
			titulo = 'Upload GPOS File';
			renderFinishedUpload = false;
			csvFile = new ContentVersion();
		} catch (Exception e) {
		}
	}

	public void doUpload() {
		try {
			csvFile.PathOnClient = csvFile.Title + '.xls';
			if (csvFile.Title == 'Partner GPOS Template')
				csvFile.Title = 'Partner GPOS Template - Report';
			insert csvFile;
			fileName = csvFile.Title;
			csvFile = [SELECT VersionData, Id, Title, ContentDocumentId FROM ContentVersion WHERE Id = :csvFile.Id LIMIT 1];

			List<GPOS_User__mdt> gposUsers = [SELECT Id, User_Id__c FROM GPOS_User__mdt];
			List<ContentDocumentLink> links = new List<ContentDocumentLink>();
			for (GPOS_User__mdt user : gposUsers) {
				ContentDocumentLink contentDocumentLink = new ContentDocumentLink(
					LinkedEntityId = user.User_Id__c,
					ContentDocumentId = csvFile.ContentDocumentId,
					shareType = 'V',
					Visibility = 'AllUsers'
				);
				links.add(contentDocumentLink);
			}

			insert links;

			GPOS_Customer_Report__c report = new GPOS_Customer_Report__c();
			report.Document__c = '/sfc/servlet.shepherd/document/download/' + csvFile.ContentDocumentId;
			report.Account__c = activeAccount.Id;
			report.Name = csvFile.Title;
			report.Type__c = 'Customer';
			insert report;
			csvFile = new ContentVersion();
			renderFinishedUpload = true;
			aAppManager.sendNotification(new List<String>{ logUser.Email__c }, 'success');
		} catch (Exception ex) {
            System.debug(ex.getStackTraceString());
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, ex.getLineNumber() + '\n' + ex.getMessage()));
			//Commented because email sending is not enabled in sandbox enviroments
			aAppManager.sendNotification(new List<String>{ logUser.Email__c }, 'error');
		}
	}

	public PageReference validate() {
		token = System.currentPageReference().getParameters().get('token');
		if (token != null) {
			logUser = aSiteAuthManager.VerifyUserSession(token);
			userName = logUser.Contact__r.Name;
			if (logUser != null) {
				activeSession = aSiteAuthManager.getUserSession(token);
				activeAccount = aSiteAuthManager.getActiveAccount_byUser(logUser);
				return null;
			}
		}

		PageReference p = new PageReference('/apex/aSiteLogin');
		p.setRedirect(true);
		return p;
	}
}