force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Credit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High Risk</fullName>
                <color>#FF0000</color>
                <label>Finance Warning - Review Account</label>
            </value>
            <value>
                <fullName>Ok</fullName>
                <default>true</default>
                <label>Satisfactory</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/fields/Macroregion__c.field-meta.xml
<CustomField>
    <fullName>Macroregion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Macroregion</label>
    <referenceTo>Macroregion__c</referenceTo>
    <relationshipLabel>Counties</relationshipLabel>
    <relationshipName>Counties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Explore_Plot_Cell__c/Explore_Plot_Cell__c.object-meta.xml
<CustomObject>
    <label>Explore Plot Cell</label>
    <nameField>
        <displayFormat>{00000}</displayFormat>
        <label>Explore Plot Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Explore Plot Cells</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Explore_Plot_Cell__c/fields/Explore_Plot__c.field-meta.xml
<CustomField>
    <fullName>Explore_Plot__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Plot Location</description>
    <label>Explore Plot</label>
    <referenceTo>Plot_Location__c</referenceTo>
    <relationshipLabel>Explore Plot Cells</relationshipLabel>
    <relationshipName>Explore_Plot_Cells</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Explore_Plot_Cell__c/fields/QR_Code__c.field-meta.xml
<CustomField>
    <fullName>QR_Code__c</fullName>
    <label>QR Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Explore_Plot_Note_Score__c/Explore_Plot_Note_Score__c.object-meta.xml
<CustomObject>
    <label>Explore Plot Note Score</label>
    <nameField>
        <label>Explore Plot Note Score Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Explore Plot Note Scores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Explore_Plot_Note_Score__c/fields/Explore_Rating__c.field-meta.xml
<CustomField>
    <fullName>Explore_Rating__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Explore Rating</label>
    <referenceTo>Explore_Rating__c</referenceTo>
    <relationshipLabel>Explore Plot Note Scores</relationshipLabel>
    <relationshipName>Explore_Plot_Note_Scores</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Explore_Plot_Note_Score__c/fields/Plot_Note__c.field-meta.xml
<CustomField>
    <fullName>Plot_Note__c</fullName>
    <label>Plot Note</label>
    <referenceTo>Plot_Saved_Soy__c</referenceTo>
    <relationshipLabel>Explore Plot Note Scores</relationshipLabel>
    <relationshipName>Explore_Plot_Note_Scores</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Explore_Plot_Note_Score__c/fields/Score_Value__c.field-meta.xml
<CustomField>
    <fullName>Score_Value__c</fullName>
    <label>Score Value</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Explore_Rating__c/Explore_Rating__c.object-meta.xml
<CustomObject>
    <description>Explore Ratings will be the ratings that are used within GDM Explore. This object allows us to build customized ratings, related to a Ratings Scale, and assign who is able to see each Customized Rating within GDM Explore.</description>
    <label>Explore Rating</label>
    <nameField>
        <label>Explore Rating Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Explore Ratings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Explore_Rating__c/fields/Visible_Name__c.field-meta.xml
<CustomField>
    <fullName>Visible_Name__c</fullName>
    <inlineHelpText>This will control how the rating will be displayed within GDM Explore</inlineHelpText>
    <label>Visible Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Macroregion__c/Macroregion__c.object-meta.xml
<CustomObject>
    <label>Macroregion</label>
    <nameField>
        <label>Macroregion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroregions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Plot_Note__c/Mass_Plot_Note__c.object-meta.xml
<CustomObject>
    <label>Mass Plot Note</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Mass Plot Note Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Mass Plot Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mass_Plot_Note__c/fields/Explore_Rating__c.field-meta.xml
<CustomField>
    <fullName>Explore_Rating__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Explore Rating</label>
    <referenceTo>Explore_Rating__c</referenceTo>
    <relationshipLabel>Mass Plot Notes</relationshipLabel>
    <relationshipName>Mass_Plot_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mass_Plot_Note__c/fields/Plot_Location__c.field-meta.xml
<CustomField>
    <fullName>Plot_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot Location</label>
    <referenceTo>Plot_Location__c</referenceTo>
    <relationshipLabel>Mass Plot Notes</relationshipLabel>
    <relationshipName>Mass_Plot_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mass_Plot_Note__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>Mass Plot Notes</relationshipLabel>
    <relationshipName>Mass_Plot_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mass_Plot_Note__c/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plot_Location__c/Plot_Location__c.object-meta.xml
<CustomObject>
    <label>Plot Location</label>
    <nameField>
        <label>Plot Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plot Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Plot Locations</relationshipLabel>
    <relationshipName>Plot_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plot_Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>This will impact the locations that &quot;Commercial Accounts&quot; can view. Hidden = No. Public = Yes.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Plot_Saved_Soy__c/Plot_Saved_Soy__c.object-meta.xml
<CustomObject>
    <label>Plot Note</label>
    <nameField>
        <displayFormat>SS{0000000}</displayFormat>
        <label>Plot Note Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plot Notes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot_Saved_Soy__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <formula>Plot_Location__r.Location__r.Name + &quot;, &quot; + Plot_Location__r.Location__r.State_Id__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plot Location Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Plot_Saved_Soy__c/fields/Mass_Plot_Note__c.field-meta.xml
<CustomField>
    <fullName>Mass_Plot_Note__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Mass Plot Note</label>
    <referenceTo>Mass_Plot_Note__c</referenceTo>
    <relationshipLabel>Plot Notes</relationshipLabel>
    <relationshipName>Plot_Notes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plot_Saved_Soy__c/fields/Plot_Cell__c.field-meta.xml
<CustomField>
    <fullName>Plot_Cell__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot Cell</label>
    <referenceTo>Explore_Plot_Cell__c</referenceTo>
    <relationshipLabel>Plot Notes</relationshipLabel>
    <relationshipName>Plot_Saved_Soys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plot_Saved_Soy__c/fields/Plot_Location__c.field-meta.xml
<CustomField>
    <fullName>Plot_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot Location</label>
    <referenceTo>Plot_Location__c</referenceTo>
    <relationshipName>Plot_Saved_Soys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plot_Saved_Soy__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipName>Plot_Saved_Soys</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de SiteUser</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteUser__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SiteUsers</relationshipLabel>
    <relationshipName>SiteUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Brand_GDM__c.field-meta.xml
<CustomField>
    <fullName>Brand_GDM__c</fullName>
    <defaultValue>true</defaultValue>
    <label>View Brand GDM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Notification_Bean_Blog__c.field-meta.xml
<CustomField>
    <fullName>Notification_Bean_Blog__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Notification - Bean Blog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Notification_Visit__c.field-meta.xml
<CustomField>
    <fullName>Notification_Visit__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Notification - Visit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PlotNoteExecutionBOTest.cls
/**
 * An apex page controller that exposes the mssive creation of notes
 */
@IsTest public with sharing class PlotNoteExecutionBOTest {
     
     @IsTest(SeeAllData=true) public static void testNoteCreationTrigger() {
        
        Macroregion__c m = new Macroregion__c(Name='SCB');
        insert m;
        County__c co = new County__c(Name='TEST', Macroregion__c=m.Id);
        insert co;
        Location__c l = new Location__c(Name='TES',County__c=co.Id);
        insert l;
        Plot_location__c pl = new Plot_location__c(Location__c=l.Id, Name='TEST');
        insert pl;
        Explore_Plot_Cell__c cell = new Explore_Plot_Cell__c(Explore_Plot__c=pl.Id, QR_Code__c='123');
        insert cell;
        
        Account a = new Account(Name='TEST A', Location__c=l.Id);
        insert a;        
        SiteUser__c user = new SiteUser__c(Email__c='j@mil.com',Notification_Bean_Blog__c=true, Notification_Visit__c=true, Password__c='df',Name='JERE',Brand_GDM__c=true,Status__c='Approved', Account__c=a.Id);
        insert user;
        
        Explore_Rating__c rating = new Explore_Rating__c(Name='Eye', Visible_Name__c='Eye Appeal'); insert rating;    
        Explore_Rating__c ratingFill = new Explore_Rating__c(Name='FILL', Visible_Name__c='Fill'); insert ratingFill;    
        
        Plot_Saved_Soy__c note = new Plot_Saved_Soy__c(note__c='TEST',SiteUser__c=user.Id,Plot_location__c=pl.Id, Plot_Cell__c=cell.Id); insert note;
        Explore_Plot_Note_Score__c ex = new Explore_Plot_Note_Score__c(Explore_Rating__c=rating.Id, Plot_Note__c=note.Id, Score_Value__c='2'); insert ex;
                
        // Instantiate a new controller with all parameters in the page
        Mass_Plot_Note__c mm = new Mass_Plot_Note__c();
        mm.Plot_Location__c = pl.Id;
        mm.SiteUser__c = user.Id; 
        mm.Explore_Rating__c = rating.Id;                
        mm.Value__c = '1';
        
        insert mm;
                                  
        Plot_Saved_Soy__c note2 = new Plot_Saved_Soy__c(note__c='TEST',SiteUser__c=user.Id,Plot_location__c=pl.Id, Plot_Cell__c=cell.Id); insert note2;
        Explore_Plot_Note_Score__c ex2 = new Explore_Plot_Note_Score__c(Explore_Rating__c=rating.Id, Plot_Note__c=note2.Id, Score_Value__c='2'); insert ex2;
        Explore_Plot_Note_Score__c exFill = new Explore_Plot_Note_Score__c(Explore_Rating__c=ratingFill.Id, Plot_Note__c=note2.Id, Score_Value__c='1'); insert exFill;
        
    }    
}