force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Credit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High Risk</fullName>
                <color>#FF0000</color>
                <label>Finance Warning - Review Account</label>
            </value>
            <value>
                <fullName>Ok</fullName>
                <default>true</default>
                <label>Satisfactory</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/County__c/County__c.object-meta.xml
<CustomObject>
    <label>County</label>
    <nameField>
        <label>County Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Counties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/County__c/fields/Macroregion__c.field-meta.xml
<CustomField>
    <fullName>Macroregion__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Macroregion</label>
    <referenceTo>Macroregion__c</referenceTo>
    <relationshipLabel>Counties</relationshipLabel>
    <relationshipName>Counties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Location__c/fields/County__c.field-meta.xml
<CustomField>
    <fullName>County__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>County</label>
    <referenceTo>County__c</referenceTo>
    <relationshipLabel>Locations</relationshipLabel>
    <relationshipName>Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Macroregion__c/Macroregion__c.object-meta.xml
<CustomObject>
    <label>Macroregion</label>
    <nameField>
        <label>Macroregion Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Macroregions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot_Location__c/Plot_Location__c.object-meta.xml
<CustomObject>
    <label>Plot Location</label>
    <nameField>
        <label>Plot Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plot Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Plot_Location__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Location</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Plot Locations</relationshipLabel>
    <relationshipName>Plot_Locations</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Plot_Location__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>This will impact the locations that &quot;Commercial Accounts&quot; can view. Hidden = No. Public = Yes.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public</fullName>
            </value>
            <value>
                <fullName>Hidden</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SiteNotification__c/SiteNotification__c.object-meta.xml
<CustomObject>
    <label>SiteNotification</label>
    <nameField>
        <label>SiteNotification Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteNotifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteNotification__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SiteNotifications</relationshipLabel>
    <relationshipName>SiteNotifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteNotification__c/fields/Brand_GDM__c.field-meta.xml
<CustomField>
    <fullName>Brand_GDM__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Brand GDM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteNotification__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Bean Blog Post</fullName>
            </value>
            <value>
                <fullName>Business</fullName>
            </value>
            <value>
                <fullName>Events</fullName>
            </value>
            <value>
                <fullName>GDM Explore Harvest Visit Cancel</fullName>
            </value>
            <value>
                <fullName>GDM Explore Invitation Answer</fullName>
            </value>
            <value>
                <fullName>GDM Explore Invitation Cancelled</fullName>
            </value>
            <value>
                <fullName>GDM Explore Invitation Created</fullName>
            </value>
            <value>
                <fullName>GDM Explore Invitation Rescheduled</fullName>
            </value>
            <value>
                <fullName>GDM Explore New User Approval Request</fullName>
            </value>
            <value>
                <fullName>GDM Explore Note Sharing</fullName>
            </value>
            <value>
                <fullName>GDM Explore Visit</fullName>
            </value>
            <value>
                <fullName>GDM Explore Visit Canceled Harvest</fullName>
            </value>
            <value>
                <fullName>GDM Explore Visit Irrigation Off</fullName>
            </value>
            <value>
                <fullName>GDM Explore Visit Irrigation On</fullName>
            </value>
            <value>
                <fullName>GDM Explore Visit Reminder</fullName>
            </value>
            <value>
                <fullName>Plot Location Harvest</fullName>
            </value>
            <value>
                <fullName>Plot Location Irrigation</fullName>
            </value>
            <value>
                <fullName>Product Information</fullName>
            </value>
            <value>
                <fullName>Product Recommendation</fullName>
            </value>
            <value>
                <fullName>Reporting</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SiteNotification__c/fields/Plot_Location__c.field-meta.xml
<CustomField>
    <fullName>Plot_Location__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plot Location</label>
    <referenceTo>Plot_Location__c</referenceTo>
    <relationshipLabel>SiteNotifications</relationshipLabel>
    <relationshipName>SiteNotifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteNotification__c/fields/RecipientProfile__c.field-meta.xml
<CustomField>
    <fullName>RecipientProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RecipientProfile</label>
    <referenceTo>SiteUserProfile__c</referenceTo>
    <relationshipLabel>SiteNotifications</relationshipLabel>
    <relationshipName>SiteNotifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteNotification__c/fields/SiteUser__c.field-meta.xml
<CustomField>
    <fullName>SiteUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUser</label>
    <referenceTo>SiteUser__c</referenceTo>
    <relationshipLabel>SiteNotifications</relationshipLabel>
    <relationshipName>SiteNotifications</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de SiteUser</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteUser__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SiteUsers</relationshipLabel>
    <relationshipName>SiteUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Brand_GDM__c.field-meta.xml
<CustomField>
    <fullName>Brand_GDM__c</fullName>
    <defaultValue>true</defaultValue>
    <label>View Brand GDM</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Notification_Bean_Blog__c.field-meta.xml
<CustomField>
    <fullName>Notification_Bean_Blog__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Notification - Bean Blog</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Notification_Visit__c.field-meta.xml
<CustomField>
    <fullName>Notification_Visit__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Notification - Visit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/SiteUserProfile__c.field-meta.xml
<CustomField>
    <fullName>SiteUserProfile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SiteUserProfile</label>
    <referenceTo>SiteUserProfile__c</referenceTo>
    <relationshipLabel>SiteUsers</relationshipLabel>
    <relationshipName>SiteUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SiteUserProfile__c/SiteUserProfile__c.object-meta.xml
<CustomObject>
    <label>SiteUserProfile</label>
    <nameField>
        <label>Profile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUserProfiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteUserProfile__c/fields/Access_Business_Section__c.field-meta.xml
<CustomField>
    <fullName>Access_Business_Section__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Access Business Section</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUserProfile__c/fields/Access_Products_Section__c.field-meta.xml
<CustomField>
    <fullName>Access_Products_Section__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Access Products Section</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUserProfile__c/fields/Access_Reporting_Section__c.field-meta.xml
<CustomField>
    <fullName>Access_Reporting_Section__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Access Reporting Section</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SiteNotification_TriggerTest.cls
@isTest
private class SiteNotification_TriggerTest {

    static testmethod void test(){
        SiteUserProfile__c p = new SiteUserProfile__c(Name='Full',Access_Business_Section__c=true,Access_Reporting_Section__c=true,Access_Products_Section__c=true);        
        insert p;
        
        SiteNotification__c c = new SiteNotification__c(Name='TEST',RecipientProfile__c=p.Id);
        insert c;
        
        Macroregion__c m = new Macroregion__c(Name='SCB');
        insert m;
        County__c co = new County__c(Name='TEST', Macroregion__c=m.Id);
        insert co;
        Location__c l = new Location__c(Name='TES',County__c=co.Id);
        insert l;
        Plot_location__c pl = new Plot_location__c(Location__c=l.Id, Name='TEST');
        insert pl;
        Account a = new Account(Name='TEST A', Location__c=l.Id);
        insert a;
        
        SiteUser__c user = new SiteUser__c(Email__c='j@mil.com',Notification_Bean_Blog__c=true, Notification_Visit__c=true, Password__c='df',Name='JERE',Brand_GDM__c=true,Status__c='Approved',SiteUserProfile__c=p.Id, Account__c=a.Id);
        insert user;
        
        SiteNotification__c c2 = new SiteNotification__c(Name='TEST2',Plot_location__c=pl.Id,RecipientProfile__c=p.Id,Category__c='Bean Blog Post');
        insert c2;
        
        SiteNotification__c c3 = new SiteNotification__c(Name='TEST2',Plot_location__c=pl.Id,RecipientProfile__c=p.Id,Category__c='GDM Explore Visit Reminder',SiteUser__c=user.Id, Account__c=a.Id);
        insert c3;
    }  
}