force-app/main/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Credit Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>High Risk</fullName>
                <color>#FF0000</color>
                <label>Finance Warning - Review Account</label>
            </value>
            <value>
                <fullName>Ok</fullName>
                <default>true</default>
                <label>Satisfactory</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Configuracion_USA__c/Configuracion_USA__c.object-meta.xml
<CustomObject>
    <label>Admin Setting</label>
    <nameField>
        <label>Admin Settings Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Admin Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Seed_Tracking__c/Seed_Tracking__c.object-meta.xml
<CustomObject>
    <label>Seed Track</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Seed Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seed Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Seed_Tracking__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Seeds_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Variety</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Seed Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/SiteUser__c.object-meta.xml
<CustomObject>
    <description>Forma parte del circuito del Sitio Portal Web.</description>
    <label>SiteUser</label>
    <nameField>
        <label>Nombre de SiteUser</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SiteUser__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SiteUsers</relationshipLabel>
    <relationshipName>SiteUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Cadastro_pela_primeira_vez__c.field-meta.xml
<CustomField>
    <fullName>Cadastro_pela_primeira_vez__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has login before</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SiteUser__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SiteUserAccount__c/SiteUserAccount__c.object-meta.xml
<CustomObject>
    <label>SiteUserAccount</label>
    <nameField>
        <label>SiteUserAccount Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SiteUserAccounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/aSiteSeedTrackingControllerTest.cls
/**
 * @description       :
 * @author            : Horacio Calleja
 * @group             :
 * @last modified on  : 01-17-2023
 * @last modified by  : Horacio Calleja
 **/
@isTest
private class aSiteSeedTrackingControllerTest {
	@TestSetup
	static void makeData() {
		Configuracion_USA__c config = Build.aConfiguracionUSA()
			.withActiveSeason('23/2023')
			.withName('Config test')
			.withProductionSeason('23/2023')
			.withSalesSeason('23/2023')
			.withLastSeason('22/2022')
			.build();
		insert config;
		Account anAccount = Build.anAccount().withName('Test').build();
		insert anAccount;
		SiteUser__c siteUser = Build.aSiteUser()
			.withName('Site user test')
			.withAccount(anAccount)
			.withEmail('test@test.com')
			.withPassword('12345')
			.build();
		siteUser.Cadastro_pela_primeira_vez__c = true;
		insert siteUser;
		SiteUserAccount__c siteAccount = Build.aSiteUserAccount()
			.withAccount(anAccount)
			.withActive(true)
			.withName('SU')
			.withSiteUser(siteUser)
			.build();
		insert siteAccount;
		Seed_Tracking__c st = new Seed_Tracking__c(
			Account__c = anAccount.Id,
			Active__c = true,
			Brand__c = 'DONMARIO',
			Status__C = 'Pending',
			Type__c = 'Delivery'
		);
		insert st;
	}

	@isTest
	static void testValidateShouldBeOk() {
		Account theAccount = [SELECT Id FROM Account LIMIT 1];
		SiteUser__c theUser = [SELECT Id FROM SiteUser__c LIMIT 1];
		Pagereference pageRef = Page.aSiteSeedTracking;
		SiteUser__c siteUser = [SELECT Id, Email__c, Password__c FROM SiteUser__c LIMIT 1];
		Test.setCurrentPage(pageRef);
		aSiteLoginController loginCtrl = new aSiteLoginController();
		loginCtrl.username = siteUser.Email__c;
		loginCtrl.password = siteUser.Password__c;
		Pagereference pageRedirected = loginCtrl.login();
		String token = pageRedirected.getParameters().get('token');
		Test.startTest();
		aSiteSeedTrackingController stCtrl = new aSiteSeedTrackingController();
		pageRef.getParameters().put('token', token);
		stCtrl.validate();
		stCtrl.getFields();
		Test.stopTest();
		Account ac = stCtrl.getAccount();
		SiteUser__c su = stCtrl.getUser();
		System.assertEquals(theAccount.Id, ac.Id);
		System.assertEquals(theUser.Id, su.Id);
	}

	@isTest
	static void testValidateShouldFail() {
		Test.startTest();
		aSiteSeedTrackingController stCtrl = new aSiteSeedTrackingController();
		stCtrl.validate();
		Test.stopTest();
	}

	@isTest
	static void testGetOptionVarietyShouldBeOk() {
		aSiteSeedTrackingController stCtrl = validate();
		Test.startTest();
		List<SelectOption> varietyOptions = stCtrl.getOptionVariety();
		Test.stopTest();
		System.assertEquals(varietyOptions.size(), 2);
	}

	@isTest
	static void testGetOptionStatusShouldBeOk() {
		aSiteSeedTrackingController stCtrl = validate();
		Test.startTest();
		List<SelectOption> statusOptions = stCtrl.getOptionStatus();
		Test.stopTest();
		System.assertEquals(statusOptions.size(), 2);
	}

	@isTest
	static void testGetOptionSeedTypeShouldBeOk() {
		aSiteSeedTrackingController stCtrl = validate();
		Test.startTest();
		List<SelectOption> seedTypes = stCtrl.getOptionSeedType();
		Test.stopTest();
		System.assertEquals(seedTypes.size(), 2);
	}

	public static aSiteSeedTrackingController validate() {
		Pagereference pageRef = Page.aSiteSeedTracking;
		SiteUser__c siteUser = [SELECT Id, Email__c, Password__c FROM SiteUser__c LIMIT 1];
		Test.setCurrentPage(pageRef);
		aSiteLoginController loginCtrl = new aSiteLoginController();
		loginCtrl.username = siteUser.Email__c;
		loginCtrl.password = siteUser.Password__c;
		Pagereference pageRedirected = loginCtrl.login();
		String token = pageRedirected.getParameters().get('token');
		aSiteSeedTrackingController stCtrl = new aSiteSeedTrackingController();
		pageRef.getParameters().put('token', token);
		stCtrl.validate();
		return stCtrl;
	}
}