force-app/main/default/objects/Bitacora_NC__c/Bitacora_NC__c.object-meta.xml
<CustomObject>
    <label>Bitacora_NC</label>
    <nameField>
        <label>Bitacora_NC Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Bitacora_NCs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Bitacora_NC__c/fields/Fecha_Desde__c.field-meta.xml
<CustomField>
    <fullName>Fecha_Desde__c</fullName>
    <label>Fecha Desde</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Bitacora_NC__c/fields/fkart__c.field-meta.xml
<CustomField>
    <fullName>fkart__c</fullName>
    <label>fkart</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bitacora_NC__c/fields/numero_lote__c.field-meta.xml
<CustomField>
    <fullName>numero_lote__c</fullName>
    <label>numero lote</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Bitacora_NC__c/fields/sociedad__c.field-meta.xml
<CustomField>
    <fullName>sociedad__c</fullName>
    <label>sociedad</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Bitacora_NC__c/fields/vbtyp__c.field-meta.xml
<CustomField>
    <fullName>vbtyp__c</fullName>
    <label>vbtyp</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/schedulableFlujoDocUpdate.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 12-12-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
global class schedulableFlujoDocUpdate implements Schedulable {

    global void execute(SchedulableContext ctx) {

		Integer startTime = Limits.getCpuTime();

        try {
	
			for (Bitacora_NC__c b : [SELECT Id, vbtyp__c, fkart__c, Fecha_Desde__c, numero_lote__c, sociedad__c
									 FROM Bitacora_NC__c]) {

				sapFlujoDoc_caller.actItems(b.vbtyp__c, b.fkart__c, b.sociedad__c);
			}
				
		} catch (Exception ee) {

			System.debug('ERROR:  ' +ee.getStackTraceString());
		}

		Integer endTime = Limits.getCpuTime();
        System.debug('Tiempo de CPU utilizado: ' + (endTime - startTime) + ' ms');
    }
}