force-app/main/default/objects/Opportunity/fields/Attendance__c.field-meta.xml
<CustomField>
    <fullName>Attendance__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact of Sale</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades (Contact of Sale)</relationshipLabel>
    <relationshipName>Oportunidades2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Branch Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Branch Name)</relationshipLabel>
    <relationshipName>Opportunities_Branchs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Incoterm_1__c.field-meta.xml
<CustomField>
    <fullName>Incoterm_1__c</fullName>
    <label>Incoterm</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DED - Deliver to ship-to address</fullName>
                <default>true</default>
                <label>DED - Deliver to ship-to address</label>
            </value>
            <value>
                <fullName>DEP - Pick Up</fullName>
            </value>
            <value>
                <fullName>CFR - Cost and Freight</fullName>
            </value>
            <value>
                <fullName>CIF - Cost Insurance and Freight</fullName>
            </value>
            <value>
                <fullName>CIP - Carriage and Insurance Paid (To)</fullName>
            </value>
            <value>
                <fullName>CPT - Carriage Paid To</fullName>
            </value>
            <value>
                <fullName>DAP - Delivered At Place</fullName>
            </value>
            <value>
                <fullName>DAT - Delivered At Terminal</fullName>
            </value>
            <value>
                <fullName>DDP - Delivered Duty Paid</fullName>
            </value>
            <value>
                <fullName>DIB - Deliver</fullName>
            </value>
            <value>
                <fullName>EXW - Ex Works</fullName>
            </value>
            <value>
                <fullName>FAS - Free Alongside Ship</fullName>
            </value>
            <value>
                <fullName>FCA - Free Carrier</fullName>
            </value>
            <value>
                <fullName>FOB - Free On Board</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Incoterm_2__c.field-meta.xml
<CustomField>
    <fullName>Incoterm_2__c</fullName>
    <label>Incoterm 2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MARION</fullName>
            </value>
            <value>
                <fullName>NEWPORT</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ship To)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Sale.recordType-meta.xml
<RecordType>
    <fullName>Sale</fullName>
    <active>true</active>
    <businessProcess>Invoice</businessProcess>
    <label>Sale</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Order Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Price_by_140k__c.field-meta.xml
<CustomField>
    <fullName>Price_by_140k__c</fullName>
    <formula>IF(TEXT(PricebookEntry.Product2.UNIDADE__c)=&apos;BAGS BY LBS&apos; 
,UnitPrice*50/VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c) 
,UnitPrice*140/VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c))
- IF(Quantity_by_140k__c&lt;&gt;0,CM_Amount__c/Quantity_by_140k__c,0)
+ IF(Quantity_by_140k__c&lt;&gt;0,DB_Amount__c/Quantity_by_140k__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Result of Sales Price equivalence in 140k, after credit memos if any.</inlineHelpText>
    <label>Price by 140k</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Quantity_by_140k__c.field-meta.xml
<CustomField>
    <fullName>Quantity_by_140k__c</fullName>
    <description>,Quantity* NULLVALUE(Seed_per_pound__c, 0)/140000*VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c)</description>
    <formula>IF(AND(Motivo_de_Rechazo__c!=&apos;Z9&apos;,Motivo_de_Rechazo__c!=&apos;Z5&apos;,Motivo_de_Rechazo__c!=&apos;Z4&apos;),

  IF(TEXT(PricebookEntry.Product2.UNIDADE__c)=&apos;BAGS BY LBS&apos;,
    (Quantity-Returned_Quantity__c)/50*VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c),
    (Quantity-Returned_Quantity__c)/140*VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c)
    ),
  0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>IF(AND(Motivo_de_Rechazo__c!=&apos;Z3&apos;,Motivo_de_Rechazo__c!=&apos;Z5&apos;),

  IF(TEXT(PricebookEntry.Product2.UNIDADE__c)=&apos;BAGS BY LBS&apos;,
    (Quantity-Returned_Quantity__c)/50*VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c),
    (Quantity-Returned_Quantity__c)/140*VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c)
    ),
  0)</inlineHelpText>
    <label>Quantity by 140k</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Variedad__c.field-meta.xml
<CustomField>
    <fullName>Variedad__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Variedades que pueden incluirse en el contrato de multiplicacion</description>
    <label>Variety Name DO NOT USE</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Producto de oportunidad</relationshipLabel>
    <relationshipName>Producto_de_oportunidad</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Variedade_de_Produto__c.field-meta.xml
<CustomField>
    <fullName>Variedade_de_Produto__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GDM Commercial Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BAG 140K</fullName>
            </value>
            <value>
                <fullName>BAG 40(140K)</fullName>
            </value>
            <value>
                <fullName>LB</fullName>
            </value>
            <value>
                <fullName>BAGS BY LBS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <label>Variety</label>
    <nameField>
        <label>Variety Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Varieties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DatosPedidoVentaControllerTest.cls
@isTest
private class DatosPedidoVentaControllerTest {
	@TestSetup
	static void makeData() {
		Contact aContact = new Contact(FirstName = 'Fake contact', LastName = 'Fake');
		insert aContact;
		Account anAccount = Build.anAccount()
			.withName('Test account')
			.withShippingCity('New York')
			.withShippingCountry('United states')
			.withShippingState('NY')
			.withShippingStreet('Fake street 123')
			.withShippingPostalCode('1234')
			.withBillingCity('New york')
			.withBillingState('NY')
			.withBillingCountry('United States')
			.withBillingPostalCode('1234')
			.withBillingStreet('Fake street')
			.build();
		insert anAccount;
		Opportunity theOppGDM = Build.anOpportunity()
			.withAccountId(anAccount)
			.withActiva(true)
			.withCompany('GDM')
			.withDescription('Desc')
			.withCloseDate(date.today())
			.withShipTo(anAccount)
			.withBranchName(anAccount)
			.withType('Z2 - PARENT SEED')
			.withAttendance(aContact)
			.build();
		insert theOppGDM;
		Opportunity theOppVirtue = Build.anOpportunity()
			.withAccountId(anAccount)
			.withActiva(true)
			.withCompany('B&B')
			.withDescription('Desc')
			.withCloseDate(date.today())
			.withShipTo(anAccount)
			.withBranchName(anAccount)
			.withType('Z2 - PARENT SEED')
			.withCloseDate(date.today())
			.withAttendance(aContact)
			.build();
		insert theOppVirtue;
		Product2 aProduct = Build.aProduct2().withName('Test prod').withUNIDADE('BAG 40(140K').build();
		insert aProduct;
		Variedad__c variety = Build.aVariedad().withName('Test variety').build();
		insert variety;
		Pricebook2 aPricebook = Build.aPricebook2()
			.withBrand('GDM')
			.withIsActive(true)
			.withDescription('Desc')
			.withName('Test pb')
			.build();
		insert aPricebook;
		PricebookEntry standarPbeOne = Build.aPricebookEntry()
			.withIsActive(true)
			.withPricebook2Id(Test.getStandardPricebookId())
			.withProduct2Id(aProduct)
			.build();
		insert standarPbeOne;
		PricebookEntry pbeOne = Build.aPricebookEntry()
			.withIsActive(true)
			.withPricebook2Id(aPricebook)
			.withProduct2Id(aProduct)
			.build();
		insert pbeOne;
		OpportunityLineItem oliOne = Build.anOpportunityLineItem()
			.withOpportunityId(theOppGDM)
			.withQuantity(10)
			.withCurrentSale140kUnits(10)
			.withUnitsEstimate140K(10)
			.withForecastQuantity(10)
			.withPricebookEntryId(pbeOne)
			.withProduct2Id(aProduct)
			.withUnitPrice(10)
			.build();
		insert oliOne;

		OpportunityLineItem oliTwo = Build.anOpportunityLineItem()
			.withOpportunityId(theOppVirtue)
			.withQuantity(10)
			.withCurrentSale140kUnits(10)
			.withUnitsEstimate140K(10)
			.withForecastQuantity(10)
			.withPricebookEntryId(pbeOne)
			.withProduct2Id(aProduct)
			.withUnitPrice(10)
			.build();
		insert oliTwo;
	}

	@isTest
	static void testDatosPedidoVentaControllerShouldRetrieveOpportunityWithProductsGDM() {
		Opportunity opp = [
			SELECT
				Id,
				Company__c,
				Name,
				Account.Name,
				Branch_Name__r.Name,
				Branch_Name__r.BillingStreet,
				Branch_Name__r.BillingCity,
				Branch_Name__r.BillingState,
				Branch_Name__r.BillingPostalCode,
				Branch_Name__r.BillingCountry,
				Description,
				Account.BillingStreet,
				Account.BillingCity,
				Account.BillingState,
				Account.BillingPostalCode,
				Account.BillingCountry,
				Ship_To__r.Name,
				Ship_To__r.ShippingStreet,
				Ship_To__r.ShippingCity,
				Ship_To__r.ShippingState,
				Ship_To__r.ShippingPostalCode,
				Ship_To__r.ShippingCountry,
				Attendance__r.Name,
				CloseDate,
				Owner.Name,
				Incoterm_1__c,
				Incoterm_2__c,
				(
					SELECT
						Id,
						Quantity,
						Quantity_by_140k__c,
						Price_by_140k__c,
						Variedade_de_Produto__c,
						UnitPrice,
						Product2.UNIDADE__c
					FROM OpportunityLineItems
				)
			FROM Opportunity
			WHERE Company__c = 'GDM'
		][0];
		Pagereference pdfPedidoVentaPage = Page.PDFPedidoVenta;
		Test.setCurrentPage(pdfPedidoVentaPage);
		Apexpages.currentPage().getParameters().put('idOpp', opp.Id);
		Test.startTest();
		DatosPedidoVentaController dpvCtrl = new DatosPedidoVentaController();
		Test.stopTest();
		DatosPedidoVentaVF pedido = dpvCtrl.pedido;
		System.assertEquals(
			'30 days upon receipt of applicable invoice, as issued by GDM. A service charge of 1.5% per month (18% per annum) will be added on all accounts over 30 days.',
			pedido.salePayment
		);
		System.assertEquals(
			'Buyer agrees and understands that he will receive the Seeds as detailed herein, subject to that certain soybean license agreement (the “SLA”) entered into by and between GDM Seeds Inc. and Buyer. Buyer will abide by all terms and conditions set forth therein and use the Seed for said purposes only, and in particular, agrees that if Buyer is receiving Testing Seed, it shall be used exclusively for non-for-profit purposes, as further detailed in the SLA. This Confirmation of Sale shall be construed consistently with the provisions of the SLA, and in the event of any conflicts, the provisions of the SLA shall prevail. Governing Law and Submission to Jurisdiction provisions as set forth in the SLA shall be applicable to this instrument, as well.',
			pedido.saleApplica
		);
		System.assertEquals(
			'Questions concerning this order? Contact Sales Administration at salesadminusa@gdmseeds.com.',
			pedido.saleSupport
		);
		System.assert(pedido.lstDadosProduto.size() > 0);
	}

	@isTest
	static void testDatosPedidoVentaControllerShouldRetrieveOpportunityWithProductsBandB() {
		Opportunity opp = [
			SELECT
				Id,
				Company__c,
				Name,
				Account.Name,
				Branch_Name__r.Name,
				Branch_Name__r.BillingStreet,
				Branch_Name__r.BillingCity,
				Branch_Name__r.BillingState,
				Branch_Name__r.BillingPostalCode,
				Branch_Name__r.BillingCountry,
				Description,
				Account.BillingStreet,
				Account.BillingCity,
				Account.BillingState,
				Account.BillingPostalCode,
				Account.BillingCountry,
				Ship_To__r.Name,
				Ship_To__r.ShippingStreet,
				Ship_To__r.ShippingCity,
				Ship_To__r.ShippingState,
				Ship_To__r.ShippingPostalCode,
				Ship_To__r.ShippingCountry,
				Attendance__r.Name,
				CloseDate,
				Owner.Name,
				Incoterm_1__c,
				Incoterm_2__c,
				(
					SELECT
						Id,
						Quantity,
						Quantity_by_140k__c,
						Price_by_140k__c,
						Variedade_de_Produto__c,
						UnitPrice,
						Product2.UNIDADE__c
					FROM OpportunityLineItems
				)
			FROM Opportunity
			WHERE Company__c = 'B&B'
		][0];
		Pagereference pdfPedidoVentaPage = Page.PDFPedidoVenta;
		Test.setCurrentPage(pdfPedidoVentaPage);
		Apexpages.currentPage().getParameters().put('idOpp', opp.Id);
		Test.startTest();
		DatosPedidoVentaController dpvCtrl = new DatosPedidoVentaController();
		Test.stopTest();
		DatosPedidoVentaVF pedido = dpvCtrl.pedido;
		System.assertEquals(
			'30 days upon receipt of applicable invoice, as issued by B&B Seeds, LLC. A service charge of 1.5% per month (18% per annum) will be added on all accounts over 30 days.',
			pedido.salePayment
		);
		System.assertEquals(
			'Buyer agrees and understands that he will receive the Seeds as detailed herein, subject to that certain soybean license agreement titled DONMARIO® GROWPRO PARTNER AGREEMENT entered into by and  between B&B SEEDS, LLC. and Buyer. Buyer will abide by all terms and conditions set forth therein and use the Seed for said purposes. This Confirmation of Sale shall be construed consistently with the provisions of the above referred agreement, and in the event of any conflicts, the provisions of the such agreement shall prevail. Governing Law and Submission to Jurisdiction provisions as set forth in the agreement shall be applicable to this instrument, as well.',
			pedido.saleApplica
		);
		System.assertEquals(
			'Questions concerning this order? Contact Sales Administration at salesadminusa@gdmseeds.com.',
			pedido.saleSupport
		);
		System.assert(pedido.lstDadosProduto.size() > 0);
	}
}