force-app/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tipo__c.field-meta.xml
<CustomField>
    <fullName>Tipo__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZO13 - Export Order</fullName>
            </value>
            <value>
                <fullName>ZO14 – Local Order</fullName>
                <default>true</default>
                <label>ZO14 – Local Order - Seeds</label>
            </value>
            <value>
                <fullName>ZO15 - Local Order</fullName>
                <label>ZO15 - Local Order - Royalty</label>
            </value>
            <value>
                <fullName>Customer Goal</fullName>
            </value>
            <value>
                <fullName>Budget</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Sale.recordType-meta.xml
<RecordType>
    <fullName>Sale</fullName>
    <active>true</active>
    <businessProcess>Invoice</businessProcess>
    <label>Sale</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Price_by_140k__c.field-meta.xml
<CustomField>
    <fullName>Price_by_140k__c</fullName>
    <formula>IF(TEXT(PricebookEntry.Product2.UNIDADE__c)=&apos;BAGS BY LBS&apos; 
,UnitPrice*50/VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c) 
,UnitPrice*140/VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c))
- IF(Quantity_by_140k__c&lt;&gt;0,CM_Amount__c/Quantity_by_140k__c,0)
+ IF(Quantity_by_140k__c&lt;&gt;0,DB_Amount__c/Quantity_by_140k__c,0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Result of Sales Price equivalence in 140k, after credit memos if any.</inlineHelpText>
    <label>Price by 140k</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Price_by_140K_value__c.field-meta.xml
<CustomField>
    <fullName>Price_by_140K_value__c</fullName>
    <label>Price by 140K value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Quantity_by_140k__c.field-meta.xml
<CustomField>
    <fullName>Quantity_by_140k__c</fullName>
    <description>,Quantity* NULLVALUE(Seed_per_pound__c, 0)/140000*VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c)</description>
    <formula>IF(AND(Motivo_de_Rechazo__c!=&apos;Z9&apos;,Motivo_de_Rechazo__c!=&apos;Z5&apos;,Motivo_de_Rechazo__c!=&apos;Z4&apos;),

  IF(TEXT(PricebookEntry.Product2.UNIDADE__c)=&apos;BAGS BY LBS&apos;,
    (Quantity-Returned_Quantity__c)/50*VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c),
    (Quantity-Returned_Quantity__c)/140*VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c)
    ),
  0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>IF(AND(Motivo_de_Rechazo__c!=&apos;Z3&apos;,Motivo_de_Rechazo__c!=&apos;Z5&apos;),

  IF(TEXT(PricebookEntry.Product2.UNIDADE__c)=&apos;BAGS BY LBS&apos;,
    (Quantity-Returned_Quantity__c)/50*VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c),
    (Quantity-Returned_Quantity__c)/140*VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c)
    ),
  0)</inlineHelpText>
    <label>Quantity by 140k</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Quantity_by_140k_value__c.field-meta.xml
<CustomField>
    <fullName>Quantity_by_140k_value__c</fullName>
    <description>Stores the value of the formula Quantity By 140K value in order to use is in Opportunity roll up summary fields</description>
    <inlineHelpText>Stores the value of the formula Quantity By 140K value in order to use is in Opportunity roll up summary fields</inlineHelpText>
    <label>Quantity by 140k value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/UpdateOpportunityLineItemBatch.cls
public with sharing class UpdateOpportunityLineItemBatch implements Database.Batchable<sObject> {
	public final String season = '22/2022';
	public final List<String> types = new List<String>{
		'Z2 - PARENT SEED',
		'Z3 - TEST SEED',
		'Z4 - WHOLESALE SEED',
		'Z13 - COMMERCIAL SEED',
		'Z14 - STOCK SEED'
	};
	public final String rtName = 'Sale';
	public final String orderType = 'ZO14 – Local Order';
	public final String query = 'SELECT Id, Price_by_140k__c, Price_by_140K_value__c, Quantity_by_140k__c, Quantity_by_140k_value__c FROM OpportunityLineItem	WHERE Opportunity.Safra__c =: season  AND Opportunity.Type IN: types AND Opportunity.RecordType.Name =: rtName AND Opportunity.Tipo__c =: orderType';

	public Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

	public void execute(Database.BatchableContext BC, List<OpportunityLineItem> items) {
		List<OpportunityLineItem> itemsToUpdate = new List<OpportunityLineItem>();
		for (OpportunityLineItem item : items) {
			if (
				item.Price_by_140k__c != item.Price_by_140K_value__c ||
				item.Quantity_by_140k__c != item.Quantity_by_140k_value__c
			) {
				itemsToUpdate.add(item);
			}
		}
		if (itemsToUpdate.size() > 0) {
			update items;
		}
	}

	public void finish(Database.BatchableContext BC) {
	}
}