force-app/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_Summary__c/Dealer_Summary__c.object-meta.xml
<CustomObject>
    <label>Dealer Summary</label>
    <nameField>
        <label>Dealer Summary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dealers Summaries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dealer_Summary__c/fields/Blocked__c.field-meta.xml
<CustomField>
    <fullName>Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Blocked</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dealer_Summary__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Client</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Dealers Summaries</relationshipLabel>
    <relationshipName>Dealers_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GPOS_Grower_Temp__c/GPOS_Grower_Temp__c.object-meta.xml
<CustomObject>
    <label>GPOS Grower Temp</label>
    <nameField>
        <label>GPOS Grower Temp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GPOS Grower Temps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GPOS_Grower_Temp__c/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GPOS Grower Temps</relationshipLabel>
    <relationshipName>GPOS_Grower_Temps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GPOS_Grower_Temp__c/fields/Dealer_Summary__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Summary__c</fullName>
    <label>Dealer Summary</label>
    <referenceTo>Dealer_Summary__c</referenceTo>
    <relationshipLabel>GPOS Grower Temps</relationshipLabel>
    <relationshipName>GPOS_Grower_Temps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GPOS_Grower_Temp__c/fields/Grower__c.field-meta.xml
<CustomField>
    <fullName>Grower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grower</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GPOS Grower Temps (Grower)</relationshipLabel>
    <relationshipName>GPOS_Grower_Temps1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GPOS_Variety_Consolidation__c/GPOS_Variety_Consolidation__c.object-meta.xml
<CustomObject>
    <label>GPOS Variety Consolidation</label>
    <nameField>
        <label>GPOS Variety Temp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GPOS Varieties Consolidations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GPOS_Variety_Consolidation__c/fields/GPOS_Grower_Temp__c.field-meta.xml
<CustomField>
    <fullName>GPOS_Grower_Temp__c</fullName>
    <label>GPOS Grower Temp</label>
    <referenceTo>GPOS_Grower_Temp__c</referenceTo>
    <relationshipName>GPOS_Variety_Temps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GPOS_Variety_Consolidation__c/fields/Variety__c.field-meta.xml
<CustomField>
    <fullName>Variety__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variety</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipName>GPOS_Variety_Temps</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GPOS_Variety_Temp__c/GPOS_Variety_Temp__c.object-meta.xml
<CustomObject>
    <label>GPOS Variety Temp</label>
    <nameField>
        <label>GPOS Variety Temp Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GPOS Variety Temps</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GPOS_Variety_Temp__c/fields/GPOS_Variety_Consolidation__c.field-meta.xml
<CustomField>
    <fullName>GPOS_Variety_Consolidation__c</fullName>
    <label>GPOS Variety Consolidation</label>
    <referenceTo>GPOS_Variety_Consolidation__c</referenceTo>
    <relationshipLabel>GPOS Variety Temps</relationshipLabel>
    <relationshipName>GPOS_Variety_Temps</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GPOS_Variety_Temp__c/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IV</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>RP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Dealer__c.field-meta.xml
<CustomField>
    <fullName>Dealer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Dealer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Dealer)</relationshipLabel>
    <relationshipName>Dealer_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Dealer_Summary__c.field-meta.xml
<CustomField>
    <fullName>Dealer_Summary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dealer Summary</label>
    <referenceTo>Dealer_Summary__c</referenceTo>
    <relationshipLabel>Opportunities</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Grower__c.field-meta.xml
<CustomField>
    <fullName>Grower__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grower</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Grower)</relationshipLabel>
    <relationshipName>Grower_Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <inlineHelpText>Invoice Number from SAP - Manual Entry</inlineHelpText>
    <label>Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IV</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>RP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Invoice_Number__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Number__c</fullName>
    <label>Invoice Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Invoice_Type__c.field-meta.xml
<CustomField>
    <fullName>Invoice_Type__c</fullName>
    <label>Invoice Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IV</fullName>
            </value>
            <value>
                <fullName>CM</fullName>
            </value>
            <value>
                <fullName>RP</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Ship_Date__c.field-meta.xml
<CustomField>
    <fullName>Ship_Date__c</fullName>
    <label>Ship Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BAG 140K</fullName>
            </value>
            <value>
                <fullName>BAG 40(140K)</fullName>
            </value>
            <value>
                <fullName>LB</fullName>
            </value>
            <value>
                <fullName>BAGS BY LBS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variety Name</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <label>Variety</label>
    <nameField>
        <label>Variety Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Varieties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/gposGenerateOpportunitiesController.cls
public class gposGenerateOpportunitiesController {

    @AuraEnabled
    public static resultWrapper getSummaryText(String recordId) {
        
        List<GPOS_Grower_Temp__c> temps = getTemps(recordId);
        Set<String> tempsIds = new Set<String>();
        for(GPOS_Grower_Temp__c t : temps) {
            tempsIds.add(t.Id);
        }
        List<GPOS_Variety_Temp__c> varTemps = getVarietyTemps(tempsIds);

        String message = 'There are ' + temps.size() + ' temporary records with ' + varTemps.size() + ' varieties items.';
        resultWrapper result = new resultWrapper();
        result.message = message;
        if(temps.size() > 0)
            result.hasRecords = true;
        return result;
    }

    @AuraEnabled
    public static void generateOpps(String recordId){

        Dealer_Summary__c ds = [SELECT Id, Blocked__c FROM Dealer_Summary__c WHERE Id =: recordId];
        System.debug(ds.Blocked__c);
        if(ds.Blocked__c) {
            throw new AuraHandledException('This summary is blocked');
        }

        
            List<GPOS_Grower_Temp__c> temps = getTemps(recordId);
            Set<String> tempsIds = new Set<String>();
            for(GPOS_Grower_Temp__c t : temps) {
                tempsIds.add(t.Id);
            }
            List<GPOS_Variety_Temp__c> varTemps = getVarietyTemps(tempsIds);

            // Get Existing Data
            Map<String, List<GPOS_Variety_Temp__c>> varTempsMap = new Map<String, List<GPOS_Variety_Temp__c>>();
            List<GPOS_Variety_Temp__c> varTempList;
            Set<String> varieties = new Set<String>();
            for(GPOS_Variety_Temp__c varTemp : varTemps) {
                if(varTempsMap.containsKey(varTemp.GPOS_Variety_Consolidation__r.GPOS_Grower_Temp__c)) {
                    varTempList = varTempsMap.get(varTemp.GPOS_Variety_Consolidation__r.GPOS_Grower_Temp__c);
                    varTempList.add(varTemp);
                    varTempsMap.put(varTemp.GPOS_Variety_Consolidation__r.GPOS_Grower_Temp__c, varTempList);
                }
                else {
                    varTempList = new List<GPOS_Variety_Temp__c>();
                    varTempList.add(varTemp);
                    varTempsMap.put(varTemp.GPOS_Variety_Consolidation__r.GPOS_Grower_Temp__c, varTempList);
                }
                varieties.add(varTemp.GPOS_Variety_Consolidation__r.Variety__c);
            }
            Pricebook2 standardPb = [SELECT Id FROM Pricebook2 WHERE IsStandard = true];
            List<PricebookEntry> standardPbes = [SELECT Id, Product2.Variedade__c
                                                    FROM PricebookEntry 
                                                    WHERE Product2.Variedade__c IN :varieties 
                                                            AND Product2.Categ__r.Name = 'PARENTAL' 
                                                            AND Product2.UNIDADE__c = 'BAG 140K'
                                                            AND Pricebook2Id = :standardPb.Id
                                                            AND IsActive = true];
            Map<String, PricebookEntry> pbeByVariety = new Map<String, PricebookEntry>();
            for(PricebookEntry entry : standardPbes) {
                pbeByVariety.put(entry.Product2.Variedade__c, entry);
            }

            // Generate Opportunities
            
            Map<String, Opportunity> results = new Map<String, Opportunity>();
            RecordType gposRecordType = [Select Id From RecordType where sobjecttype = 'Opportunity' and name = 'GPOS Opportunity'];
            for(GPOS_Grower_Temp__c t : temps) {
                Opportunity newOpp = new Opportunity();
                newOpp.AccountId = t.Dealer_Summary__r.Client__c;
                newOpp.Grower__c = t.Grower__c;
                newOpp.Dealer__c = t.Dealer__c;
                newOpp.Pricebook2Id = standardPb.Id;
                newOpp.Dealer_Summary__c = recordId;
                newOpp.Name = t.Grower__r.Name + ' - ' + t.Dealer__r.Name + ' - ' + t.Dealer_Summary__r.Season__c;
                newOpp.StageName = 'Editable';
                newOpp.CloseDate = System.today();
                newOpp.RecordTypeId = gposRecordType.Id;
                results.put(t.Grower__c + '' + t.Dealer__c, newOpp);
            }
            insert results.values();

            // Generate Opportunity Line Items

            List<OpportunityLineItem> items = new List<OpportunityLineItem>();
            for(GPOS_Grower_Temp__c t : temps) {
                Opportunity opp = results.get(t.Grower__c + '' + t.Dealer__c);
                
                if(varTempsMap.containsKey(t.Id)) {
                    varTempList = varTempsMap.get(t.Id);
                    for(GPOS_Variety_Temp__c varTemp : varTempList) {
                        OpportunityLineItem item = new OpportunityLineItem();

                        if(!pbeByVariety.containsKey(varTemp.GPOS_Variety_Consolidation__r.Variety__c))
                            throw new AuraHandledException('The ' + varTemp.GPOS_Variety_Consolidation__r.Variety__r.Name + ' is missing a Standard Pricebook Entry or Product');
                        item.PricebookEntryId = pbeByVariety.get(varTemp.GPOS_Variety_Consolidation__r.Variety__c).Id;
                        item.Ship_Date__c = varTemp.Ship_Date__c;
                        item.Invoice_Date__c = varTemp.Invoice_Date__c;
                        item.Invoice_Number__c = varTemp.Invoice_Number__c;
                        item.Invoice_Type__c = varTemp.Invoice_Type__c;
                        item.OpportunityId = opp.Id;
                        item.Quantity = varTemp.Amount__c;
                        item.TotalPrice = 1;
                        items.add(item);
                    }
                }
            }
        try {
            insert items;
            ds.Blocked__c = true;
            update ds;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage() + ' in line ' + e.getLineNumber());
        }
    }

    public static List<GPOS_Grower_Temp__c> getTemps(String recordId) {
        List<GPOS_Grower_Temp__c> temps = [SELECT Id, Dealer_Summary__r.Client__c, Grower__c, Dealer__c, Dealer_Summary__r.Season__c,
                                            Grower__r.Name, Dealer__r.Name
                                            FROM GPOS_Grower_Temp__c 
                                            WHERE Dealer_Summary__c =:recordId];
        return temps;
    }

    public static List<GPOS_Variety_Temp__c> getVarietyTemps(Set<String> tempsIds) {
        List<GPOS_Variety_Temp__c> varTemps = [SELECT Id, GPOS_Variety_Consolidation__r.GPOS_Grower_Temp__c,
                                                GPOS_Variety_Consolidation__r.Variety__c, GPOS_Variety_Consolidation__r.Variety__r.Name, Ship_Date__c, Invoice_Date__c,
                                                Invoice_Number__c, Invoice_Type__c, Amount__c
                                                FROM GPOS_Variety_Temp__c 
                                                WHERE GPOS_Variety_Consolidation__r.GPOS_Grower_Temp__c IN :tempsIds];
        return varTemps;
    }
    
    public class resultWrapper {
        @AuraEnabled
        public Boolean hasRecords = false;
        @AuraEnabled
        public String message;
    }
}