force-app/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_del_Contrato__c/Item_del_Contrato__c.object-meta.xml
<CustomObject>
    <description>Addendum Variety item</description>
    <label>Schedule A Variety</label>
    <nameField>
        <label>Schedule A Variety</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules A Variety</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_del_Contrato__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Indicates category of the licensee product</description>
    <inlineHelpText>Indicates category of the licensee product</inlineHelpText>
    <label>Category</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipName>Items_del_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item_del_Contrato__c/fields/Nombre_de_Registro__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Registro__c</fullName>
    <formula>Cultivar__r.Variedade__r.GID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GDM Variety Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Item_del_Contrato__c/fields/Precio__c.field-meta.xml
<CustomField>
    <fullName>Precio__c</fullName>
    <label>Royalty Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Item_del_Contrato__c/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <formula>Cultivar__r.Variedade__r.Name</formula>
    <label>Variety Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Reservation.recordType-meta.xml
<RecordType>
    <fullName>Reservation</fullName>
    <active>true</active>
    <businessProcess>Reservation</businessProcess>
    <label>Reservation</label>
</RecordType>

force-app/main/default/objects/Opportunity/recordTypes/Sales_Report.recordType-meta.xml
<RecordType>
    <fullName>Sales_Report</fullName>
    <active>true</active>
    <businessProcess>Portal Reports</businessProcess>
    <label>Sales Report</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Order Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/List_Royalty_Rate__c.field-meta.xml
<CustomField>
    <fullName>List_Royalty_Rate__c</fullName>
    <label>List Royalty Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Royalty_Rate__c.field-meta.xml
<CustomField>
    <fullName>Royalty_Rate__c</fullName>
    <label>Royalty Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Variedade_de_Produto__c.field-meta.xml
<CustomField>
    <fullName>Variedade_de_Produto__c</fullName>
    <formula>PricebookEntry.Product2.Variedade__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>GDM Commercial Code</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Waiting_Sync_To_Delete__c.field-meta.xml
<CustomField>
    <fullName>Waiting_Sync_To_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Waiting Sync To Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ZZPOSSF__c.field-meta.xml
<CustomField>
    <fullName>ZZPOSSF__c</fullName>
    <label>z_ZZPOSSF</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Pricebook2/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PARENT SEED</fullName>
            </value>
            <value>
                <fullName>WHOLESALE SEED</fullName>
            </value>
            <value>
                <fullName>TRADEMARK</fullName>
            </value>
            <value>
                <fullName>PORTAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Categ__c.field-meta.xml
<CustomField>
    <fullName>Categ__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Productos</relationshipLabel>
    <relationshipName>Productos</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Codigo_Material_SAP__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Material_SAP__c</fullName>
    <label>SAP Product ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Semilla_Tratada__c.field-meta.xml
<CustomField>
    <fullName>Semilla_Tratada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Semilla Tratada</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/UNIDADE__c.field-meta.xml
<CustomField>
    <fullName>UNIDADE__c</fullName>
    <label>Unit Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>BAG 140K</fullName>
            </value>
            <value>
                <fullName>BAG 40(140K)</fullName>
            </value>
            <value>
                <fullName>LB</fullName>
            </value>
            <value>
                <fullName>BAGS BY LBS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variety Name</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <label>Variety</label>
    <nameField>
        <label>Variety Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Varieties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Variedad__c/fields/Nombre_de_Registro__c.field-meta.xml
<CustomField>
    <fullName>Nombre_de_Registro__c</fullName>
    <label>GID Access Code</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Variedad__c/fields/Royalty_Rate__c.field-meta.xml
<CustomField>
    <fullName>Royalty_Rate__c</fullName>
    <label>Royalty Rate</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/opportunityProductEntryExtension.cls
public with sharing class opportunityProductEntryExtension {
	private opportunityLineItem[] forDeletion = new List<opportunityLineItem>{};

	public Opportunity theOpp { get; set; }
	public Pricebook2 theBook { get; set; }
	public String searchString { get; set; }
	public opportunityLineItem[] shoppingCart { get; set; }
	public priceBookEntry[] AvailableProducts { get; set; }
	public Item_del_contrato__c[] AvailableSchedules { get; set; }

	public String toSelect { get; set; }
	public String toUnselect { get; set; }
	public String toReselect { get; set; }
	public Decimal Total { get; set; }

	public Boolean overLimit { get; set; }
	public Boolean exclusiveWarning { get; set; }

	private Boolean forcePricebookSelection = false;
	private String compania = '';
	private Integer contador = 0;

	private Map<String, Schema.SObjectField> objectFields_oppItems = Schema.getGlobalDescribe()
		.get('OpportunityLineItem')
		.getDescribe()
		.fields.getMap();
	private Map<String, Schema.SObjectField> objectFields_opps = Schema.getGlobalDescribe()
		.get('Opportunity')
		.getDescribe()
		.fields.getMap();
	private Map<String, PricebookEntry> mapTradeMarkPrices = new Map<String, PricebookEntry>();
	private Map<String, Item_del_Contrato__c> mapSchedule = new Map<String, Item_del_Contrato__c>();
	private Map<String, Item_del_Contrato__c> mapExclusives = new Map<String, Item_del_Contrato__c>();

	public void setforcePricebookSelection(Boolean a) {
		forcePricebookSelection = a;
	}

	public opportunityProductEntryExtension(ApexPages.StandardController controller) {
		List<PricebookEntry> tmpPriceItems = new List<PricebookEntry>();

		try {
			map<Id, User> propRol = new Map<Id, User>();

			String queryOpp = 'SELECT ';
			for (String s : objectFields_opps.keySet())
				queryOpp += ' ' + s + ',';
			queryOpp +=
				'RecordType.Name, RecordType.DeveloperName, PriceBook2.Name FROM Opportunity Where Id = \'' +
				controller.getRecord().Id +
				'\' limit 1';
			theOpp = Database.query(queryOpp);

			// Obtengo los productos ya cargados a la opp y los cargo como "Seleccionados"
			String queryItems = 'SELECT ';
			for (String s : objectFields_oppItems.keySet())
				queryItems += ' ' + s + ',';
			queryItems += 'PriceBookEntry.UnitPrice, PriceBookEntry.IsActive, PriceBookEntry.Product2Id, PriceBookEntry.Product2.Name, PriceBookEntry.PriceBook2Id,';
			queryItems += 'Categoria__r.Name, PricebookEntry.Product2.Categ__c, PricebookEntry.Product2.Variedade__c, PricebookEntry.Product2.Variedade__r.Name, Product2.Family, ';
			queryItems += 'PricebookEntry.Product2.Variedade__r.Nombre_de_Registro__c, PricebookEntry.Product2.Categ__r.Name, PricebookEntry.Product2.Semilla_Tratada__c, Opportunity.StageName ';
			queryItems +=
				'FROM OpportunityLineItem Where OpportunityId = \'' +
				theOpp.Id +
				'\' Order by Variedade_de_Produto__c ASC';
			shoppingCart = Database.query(queryItems);
			for (OpportunityLineItem o : shoppingCart) {
				o.ZZPOSSF__c = String.ValueOf(contador);
				contador++;
			}
			for (User u : [SELECT Id, UserRole.Name, Profile.Name FROM User]) {
				propRol.put(u.Id, u);
			}

			if (theOpp.Type == 'Z31 - STOCK SEED') {
				String queryPlus = 'Pricebook2.Type__c, Product2.Variedade__r.Name';
				tmpPriceItems = aSiteUtils.queryResults1(
					PricebookEntry.SObjectType,
					queryPlus,
					'Pricebook2.Type__c = :v1',
					'TRADEMARK'
				);

				for (PricebookEntry pb : tmpPriceItems) {
					if (!mapTradeMarkPrices.containsKey(pb.Product2.Variedade__r.Name)) {
						mapTradeMarkPrices.put(pb.Product2.Variedade__r.Name, pb);
					}
				}
			}

			mapSchedule = aAppManager.getMapSchedules(theOpp.AccountId, theOpp.Safra__c, theOpp.Marca__c);
			mapExclusives = aAppManager.getMapSchedulesExclusives(theOpp.AccountId);

			exclusiveWarning = false;
			// Chequeo si la opp ya tiene una lista de precios
			if (theOpp.Pricebook2Id == null) {
				String nombreLista = 'Portal PriceList';
				Pricebook2[] activepbs = [
					SELECT Id, Name
					FROM Pricebook2
					WHERE Name = :nombreLista AND isActive = TRUE
					LIMIT 1
				];
				if (activepbs.size() == 2) {
					forcePricebookSelection = true;
					theBook = new Pricebook2();
				} else {
					theBook = activepbs[0];
				}
			} else {
				theBook = theOpp.Pricebook2;
			}
			System.debug(theBook);
		} catch (Exception e) {
			ApexPages.addMessages(e);
			return;
		}

		if (!forcePricebookSelection)
			updateAvailableList();
	}

	// metodo 'action' del inicio de la pagina VF
	public PageReference priceBookCheck() {
		if (theOpp == null)
			return null;

		if (forcePricebookSelection) {
			//si es necesario elegir la lista entonces va a la pagina estandar
			return changePricebook();
		} else {
			System.debug(theOpp.pricebook2Id);
			System.debug(theBook);
			if (theOpp.pricebook2Id != theBook.Id) {
				// si solo hay una lista activa, entonces seteamos esa lista y grabamos la opp
				try {
					theOpp.Pricebook2Id = theBook.Id;
					update (theOpp);
				} catch (Exception e) {
					ApexPages.addMessages(e);
				}
			}

			return null;
		}
	}

	public PageReference changePricebook() {
		// Simplemente retornamos la pagina comun de seleccion de lista de precios
		PageReference ref = new PageReference('/oppitm/choosepricebook.jsp');
		ref.getParameters().put('id', theOpp.Id);
		ref.getParameters().put('retURL', '/apex/opportunityProductEntry?id=' + theOpp.Id);
		return ref;
	}

	public void updateAvailableList() {
		Set<Id> prodsARel;
		List<Id> oppsARel;

		if (theBook == null)
			return;

		// Construimos un query dinamico sobre los productos de la lista de precios
		String qString = 'select Id, Pricebook2Id, IsActive, Product2Id, UnitPrice,';
		qString += ' Product2.Name, Product2.Codigo_material_SAP__c, Product2.IsActive, Product2.UNIDADE__c, Product2.Variedade__c, Product2.Categ__c,';
		qString += ' Product2.Variedade__r.Nombre_de_Registro__c, Product2.Variedade__r.Royalty_Rate__c, Product2.Variedade__r.Name, Product2.Categ__r.Name, Product2.Family';
		qString += ' from PricebookEntry where IsActive=true and Pricebook2Id = \'' + theBook.Id + '\'';

		// buscamos productos cuya descripcion o nombre coindidan con el texto ingresado
		if (searchString != null) {
			qString +=
				' and (Product2.Name like \'%' +
				searchString +
				'%\' or Product2.Codigo_material_SAP__c like \'%' +
				searchString +
				'%\' or Product2.Variedade__r.Name like \'%' +
				searchString +
				'%\' or Product2.Variedade__r.Nombre_de_Registro__c like \'%' +
				searchString +
				'%\')';
		}

		qString += ' order by Product2.Name';
		qString += ' limit 31';

		system.debug('qString:' + qString);
		AvailableProducts = database.query(qString);

		// Solo se mostraran hasta 30 registros... si el query tiene mas, entonces el usuario vera un mensaje
		if (AvailableProducts.size() == 31) {
			AvailableProducts.remove(30);
			overLimit = true;
		} else {
			overLimit = false;
		}
	}

	public PageReference addToShoppingCart() {
		Decimal royalty = 3.5;
		Decimal list_roy = 3.5;

		exclusiveWarning = false;

		// Cuando el usuario presiona "Seleccionar" en un producto
		for (PricebookEntry d : AvailableProducts) {
			if ((String) d.Id == toSelect) {
				royalty = d.Product2.Variedade__r.Royalty_Rate__c;
				list_roy = d.Product2.Variedade__r.Royalty_Rate__c;
				Item_del_Contrato__c itemS = new Item_del_Contrato__c();

				if (mapSchedule.containsKey(d.Product2.Variedade__r.Name)) {
					itemS = mapSchedule.get(d.Product2.Variedade__r.Name);
					if (!itemS.active__c)
						continue;

					royalty = items.Precio__c;
				}

				if (theOpp.RecordType.Name != 'Reservation' && mapExclusives.containsKey(d.Product2.Variedade__r.Name)) {
					exclusiveWarning = true;
					continue;
				}

				if (theOpp.Type == 'Z31 - STOCK SEED') {
					if (mapTradeMarkPrices.containsKey(d.Product2.Variedade__r.Name)) {
						royalty = mapTradeMarkPrices.get(d.Product2.Variedade__r.Name).UnitPrice;
						list_roy = mapTradeMarkPrices.get(d.Product2.Variedade__r.Name).UnitPrice;
					}
				}

				OpportunityLineItem item = new opportunityLineItem(
					Company__c = theOpp.Company__c,
					List_Royalty_Rate__c = list_roy,
					Royalty_rate__c = royalty,
					OpportunityId = theOpp.Id,
					PriceBookEntry = d,
					PriceBookEntryId = d.Id,
					UnitPrice = d.UnitPrice,
					ZZPOSSF__c = String.valueOf(contador)
				);
				item.Product2 = d.Product2;

				shoppingCart.add(item);
				contador++;
				break;
			}
		}
		return null;
	}

	public PageReference removeFromShoppingCart() {
		// Cuando el usuario presiona "Eliminar" en un producto seleccionado
		Integer count = 0;
		for (opportunityLineItem d : shoppingCart) {
			if ((String) d.ZZPOSSF__c == toUnselect) {
				if (d.Id != null && (d.Posicion_Relativa_Consign__c == null || d.Posicion_Relativa_Consign__c == '')) {
					forDeletion.add(d);
					shoppingCart.remove(count);
				} else if (d.Posicion_Relativa_Consign__c != null && d.Posicion_Relativa_Consign__c != '') {
					d.Waiting_Sync_To_Delete__c = true;
				}

				break;
			}
			count++;
		}

		updateAvailableList();

		return null;
	}

	public PageReference reAddToShoppingCart() {
		// Cuando el usuario presiona "Eliminar" en un producto seleccionado
		Integer count = 0;
		for (opportunityLineItem d : shoppingCart) {
			if ((String) d.ZZPOSSF__c == toReselect) {
				d.Waiting_Sync_To_Delete__c = false;

				break;
			}
			count++;
		}

		updateAvailableList();

		return null;
	}

	public PageReference onSave() {
		List<OpportunityLineItem> deleteVB = new List<OpportunityLineItem>();
		List<OpportunityLineItem> insertVB = new List<OpportunityLineItem>();
		OpportunityLineItem cloneVB = new OpportunityLineItem();
		Boolean ofPend = false;
		// Si algun producto ya selecciondo es eliminado, entonces debemos quitarlo
		Savepoint sp;
		try {
			// Los datos ya cargados deben ser actualizados
			sp = Database.setSavepoint();
			if (forDeletion.size() > 0)
				delete (forDeletion);

			for (OpportunityLineItem i : shoppingCart) {
				if (i.Quantity == null)
					i.Quantity = 0.01;
			}

			if (shoppingCart.size() > 0)
				upsert (shoppingCart);
		} catch (Exception e) {
			ApexPages.Message myMsg = new ApexPages.Message(
				ApexPages.Severity.ERROR,
				E.getMessage() +
				' - ' +
				e.getStackTraceString()
			);
			ApexPages.addMessage(myMsg);
			Database.rollback(sp);
			return null;
		}

		// Luego de grabar los cambios retornamos al usuario a la opp
		//        return new PageReference('/' + ApexPages.currentPage().getParameters().get('Id'));

		PageReference tempPage = new PageReference('/' + ApexPages.currentPage().getParameters().get('Id'));
		tempPage.setRedirect(true);
		return tempPage;
	}

	public PageReference onCancel() {
		return new PageReference('/' + ApexPages.currentPage().getParameters().get('Id'));
	}

	public List<Schema.FieldSetMember> getFields() {
		Opportunity o = [SELECT RecordType.Name FROM Opportunity WHERE Id = :theOpp.Id];
		if (o.RecordType.Name == 'Sales Report')
			return SObjectType.OpportunityLineItem.FieldSets.Sales_report.getFields();
		if (o.RecordType.Name == 'Production Report')
			return SObjectType.OpportunityLineItem.FieldSets.Production_forecast_report.getFields();
		return new List<Schema.FieldSetMember>();
	}
}