force-app/main/default/objects/Categoria__c/Categoria__c.object-meta.xml
<CustomObject>
    <label>Category</label>
    <nameField>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_To__c.field-meta.xml
<CustomField>
    <fullName>Ship_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Ship To</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Ship To)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_To_City__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_City__c</fullName>
    <formula>Ship_To__r.BillingCity</formula>
    <label>Ship To City</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Ship_To_Street__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Street__c</fullName>
    <formula>Ship_To__r.BillingStreet</formula>
    <label>Ship To Street</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Category</label>
    <referenceTo>Categoria__c</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Quantity_by_140k__c.field-meta.xml
<CustomField>
    <fullName>Quantity_by_140k__c</fullName>
    <description>,Quantity* NULLVALUE(Seed_per_pound__c, 0)/140000*VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c)</description>
    <formula>IF(AND(Motivo_de_Rechazo__c!=&apos;Z9&apos;,Motivo_de_Rechazo__c!=&apos;Z5&apos;,Motivo_de_Rechazo__c!=&apos;Z4&apos;),

  IF(TEXT(PricebookEntry.Product2.UNIDADE__c)=&apos;BAGS BY LBS&apos;,
    (Quantity-Returned_Quantity__c)/50*VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c),
    (Quantity-Returned_Quantity__c)/140*VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c)
    ),
  0)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>IF(AND(Motivo_de_Rechazo__c!=&apos;Z3&apos;,Motivo_de_Rechazo__c!=&apos;Z5&apos;),

  IF(TEXT(PricebookEntry.Product2.UNIDADE__c)=&apos;BAGS BY LBS&apos;,
    (Quantity-Returned_Quantity__c)/50*VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c),
    (Quantity-Returned_Quantity__c)/140*VALUE(PricebookEntry.Product2.CANTIDAD_SUB_UNIDAD__c)
    ),
  0)</inlineHelpText>
    <label>Quantity by 140k</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Centro_de_despacho__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEVE-DEVELOPMENT</fullName>
            </value>
            <value>
                <fullName>COME-COMERCIAL</fullName>
            </value>
            <value>
                <fullName>PROD-PRODUCTION</fullName>
            </value>
            <value>
                <fullName>RESE-RESEARCH</fullName>
            </value>
            <value>
                <fullName>ADM -ADMINISTRATION</fullName>
            </value>
            <value>
                <fullName>W001-CHAMPAIGN WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>W001-GDM - HUTCHINSON</fullName>
            </value>
            <value>
                <fullName>W001-GDM - DES MOINES</fullName>
            </value>
            <value>
                <fullName>W001-GIBSON CITY WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>W001-JONESBORO WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>W001-PRO AG WAREHOUSE</fullName>
            </value>
            <value>
                <fullName>T001-KAUFFMAN</fullName>
            </value>
            <value>
                <fullName>T002-STRATTON SEED-AR</fullName>
            </value>
            <value>
                <fullName>T003-SGD</fullName>
            </value>
            <value>
                <fullName>T004-PLANTATION SEED</fullName>
            </value>
            <value>
                <fullName>T005-GENERATION FARMS</fullName>
            </value>
            <value>
                <fullName>T006-JMR FARMS</fullName>
            </value>
            <value>
                <fullName>T007-STRATTON - ANNISTON</fullName>
            </value>
            <value>
                <fullName>T001-PRO AG CHB (ARG)</fullName>
            </value>
            <value>
                <fullName>TC01-Shoffner Comercial</fullName>
            </value>
            <value>
                <fullName>TP01-Shoffner Production</fullName>
            </value>
            <value>
                <fullName>TC02-CRV Comercial</fullName>
            </value>
            <value>
                <fullName>TP02-CRV Production</fullName>
            </value>
            <value>
                <fullName>TC03-Burrus Seed Comercial</fullName>
            </value>
            <value>
                <fullName>TP03-Burrus Seed Production</fullName>
            </value>
            <value>
                <fullName>TC05-CPS Comercial</fullName>
            </value>
            <value>
                <fullName>TP05-CPS Production</fullName>
            </value>
            <value>
                <fullName>TC06-Remington Wal.Comercial</fullName>
            </value>
            <value>
                <fullName>TP06-Remington Wal.Production</fullName>
            </value>
            <value>
                <fullName>TC07-Stratton AR Comercial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/Seed_Tracking__c.object-meta.xml
<CustomObject>
    <label>Seed Track</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Seed Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seed Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Seed_Tracking__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Seeds_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Avion_Barco__c.field-meta.xml
<CustomField>
    <fullName>Avion_Barco__c</fullName>
    <label>Avion/Barco</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Variety</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Shipping Contact</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/ETA_Customer__c.field-meta.xml
<CustomField>
    <fullName>ETA_Customer__c</fullName>
    <label>ETA Customer</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/ETA_USA__c.field-meta.xml
<CustomField>
    <fullName>ETA_USA__c</fullName>
    <label>ETA USA</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/GDM_Variety_Code__c.field-meta.xml
<CustomField>
    <fullName>GDM_Variety_Code__c</fullName>
    <label>GDM Variety Code</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/GID__c.field-meta.xml
<CustomField>
    <fullName>GID__c</fullName>
    <label>GID</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Harvest__c.field-meta.xml
<CustomField>
    <fullName>Harvest__c</fullName>
    <label>Harvest</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Contact Phone Number</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Quantity_by_140k__c.field-meta.xml
<CustomField>
    <fullName>Quantity_by_140k__c</fullName>
    <label>Quantity by 140k</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Responsable__c.field-meta.xml
<CustomField>
    <fullName>Responsable__c</fullName>
    <label>Responsable</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Rotulos__c.field-meta.xml
<CustomField>
    <fullName>Rotulos__c</fullName>
    <label>Rotulos</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Ship_To_City__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_City__c</fullName>
    <label>Ship To City</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Ship_To_Street__c.field-meta.xml
<CustomField>
    <fullName>Ship_To_Street__c</fullName>
    <label>Ship To Street</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Shipping State</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Seed Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Unit_Type__c.field-meta.xml
<CustomField>
    <fullName>Unit_Type__c</fullName>
    <label>Unit Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Warehouse__c.field-meta.xml
<CustomField>
    <fullName>Warehouse__c</fullName>
    <label>Warehouse</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Zip__c.field-meta.xml
<CustomField>
    <fullName>Zip__c</fullName>
    <label>Shipping Zip</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CSVCreator.cls
public class CSVCreator  {

    private static List<String> separateCommas(String input){
        List<String> results = input.split(';');

        for(String result : results) {
            result = result.trim();
        }

        return results;
    }

    @AuraEnabled
    public static CSVObject getCSVObject(String csv_str) {
        List<String> lines_raw = csv_str.split('\n');
        List<String> headers_raw = separateCommas(lines_raw[0]);
        List<List<String>> lines = new List<List<String>>();
        List<CSVHeader> headers = new List<CSVHeader>();

        lines_raw.remove(0);

        //Handling fields with commas

        for(String line : lines_raw) {
            List<String> line_sep = separateCommas(line);
            List<String> fields = new List<String>();
            Boolean makeCompositeField = false;
            String compositeField;
            for(String field : line_sep) {
                if (field.startsWith('"') && field.endsWith('"')) {
                    fields.add(field.trim());
                } else if (field.startsWith('"')) {
                    makeCompositeField = true;
                    compositeField = field;
                } else if (field.endsWith('"')) {
                    compositeField += ',' + field;
                    fields.add(compositeField.trim());
                    makeCompositeField = false;
                } else if (makeCompositeField) {
                    compositeField +=  ',' + field;
                } else {
                    fields.add(field.trim());
                }
            }
            lines.add(fields);
        }

        for(String header : headers_raw) {
            headers.add(new CSVHeader(header));
        }

        return new CSVObject(headers, lines);        
    }
    
    @AuraEnabled
    public static String crearSeedTracking(String jsonString) {
    
        Savepoint sp = Database.setSavepoint();
        
        try{
        
            CSVObject csv_obj = (CSVObject)JSON.deserialize(jsonString, CSVObject.class);

            for (List<String> s : csv_obj.lines){
                if (s[25] == null || s[25] == '')
                    return 'Missing AccountId data.';
            }
        
            /*
            List<Opportunity> oppsActuales = New List<Opportunity>();
            oppsActuales = [Select Id From Opportunity Where RecordType.Name = 'Seed Tracking'];
            if (oppsActuales.size() > 0)
                delete oppsActuales;
        
            Map<String,Id> rty = Opp_Utils.cargarRecordTypesOportunidades();    
            String rt_st = rty.get('Seed Tracking');
        
            Map<String,Opportunity> mapOpps = new Map<String,Opportunity>();
            for (List<String> s : csv_obj.lines){
                Opportunity o = mapOpps.get(s[4]);
                if (o == null){
                    o = new Opportunity(Name='Seed Tracking',Stagename='Editable',CloseDate=System.today(),RecordTypeId=rt_st,AccountId=s[4],Safra__c='20/2020',Marca__c='GDM');
                    mapOpps.put(s[4], o);
                }            
            }
            insert mapOpps.values();    

            List<OpportunityLineItem> items = new List<OpportunityLineItem>();
            for (List<String> s : csv_obj.lines){    
                OpportunityLineItem item = new OpportunityLineItem();
                                
                item.OpportunityId = mapOpps.get(s[4]).Id;
                item.Quantity = Double.valueOf(s[3]);
                item.UnitPrice = 1;
                item.PricebookEntryId = s[5];
                item.Categoria__c = tmp.categoria_id;                                             
    
                items.add(item);
            }

            insert items;   
            */      
        
            List<Seed_Tracking__c> registrosActuales = New List<Seed_Tracking__c>();
            registrosActuales = [Select Id From Seed_Tracking__c];
            if (registrosActuales.size() > 0)
                delete registrosActuales;   
            
            List<Seed_Tracking__c> l_st = New List<Seed_Tracking__c>();
            for (List<String> s : csv_obj.lines){
                Seed_Tracking__c st = New Seed_Tracking__c();
                st.Order__c = String.valueOf(s[0]);
                st.Brand__c = String.valueOf(s[1]);
                st.GDM_Variety_Code__c = String.valueOf(s[2]);
                st.GID__c = String.valueOf(s[3]);
                st.Quantity__c = null;
                st.Quantity_by_140k__c = null;
                if (String.valueOf(s[4]) != '')
                    st.Quantity__c = Double.valueOf(String.valueOf(s[4]).replaceAll(',','.'));
                if (String.valueOf(s[5]) != '')
                    st.Quantity_by_140k__c = Double.valueOf(String.valueOf(s[5]).replaceAll(',','.'));
                st.Unit_Type__c = String.valueOf(s[6]);
                st.Warehouse__c = String.valueOf(s[7]);
                st.Ship_To__c = String.valueOf(s[8]);
                st.Ship_To_Street__c = String.valueOf(s[9]);
                st.Ship_To_City__c = String.valueOf(s[10]);
                st.State__c = String.valueOf(s[11]);
                st.Zip__c = String.valueOf(s[12]);
                st.Contact__c = String.valueOf(s[15]);
                st.Phone_Number__c = String.valueOf(s[16]);
                st.Type__c = String.valueOf(s[17]);
                st.Avion_Barco__c = String.valueOf(s[18]);
                st.Responsable__c = String.valueOf(s[19]);
                st.Rotulos__c = String.valueOf(s[20]);
                st.Harvest__c = String.valueOf(s[21]);
                st.ETA_USA__c = String.valueOf(s[22]);
                st.Status__c = String.valueOf(s[23]);
                st.ETA_Customer__c = String.valueOf(s[24]);
                st.Account__c = String.valueOf(s[25]);
                l_st.add(st);                        
            }
        
            if (l_st.size() > 0)
                insert l_st;
                
         }catch(Exception e){  
            Database.rollback(sp);          
            return 'ERROR ' + e.getMessage();
         }
                
         return 'The data has been imported successfully.';
        
    }

}