force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>Addendum to the Soybean Germplasm Aggrement.</description>
    <label>Schedule A</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Schedule A Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Contrato__c/fields/Tipo_de_Cota_o__c.field-meta.xml
<CustomField>
    <fullName>Tipo_de_Cota_o__c</fullName>
    <label>Tipo de Cotação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DOLAR</fullName>
            </value>
            <value>
                <fullName>SOJA</fullName>
            </value>
            <value>
                <fullName>FATURAMENTO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_del_Contrato__c/Item_del_Contrato__c.object-meta.xml
<CustomObject>
    <description>Addendum Variety item</description>
    <label>Schedule A Variety</label>
    <nameField>
        <label>Schedule A Variety</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules A Variety</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_del_Contrato__c/fields/Contrato_de_Multiplicacion__c.field-meta.xml
<CustomField>
    <fullName>Contrato_de_Multiplicacion__c</fullName>
    <description>Agreement related to</description>
    <inlineHelpText>Agreement related to</inlineHelpText>
    <label>Schedule A</label>
    <referenceTo>Contrato__c</referenceTo>
    <relationshipLabel>Schedules A Variety</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/ContratoBeforeUpdate_AnexosTest.cls
@isTest
private class ContratoBeforeUpdate_AnexosTest {

    static testmethod void test(){
        Contrato__c cc = new Contrato__c();
        insert cc;
      
        Item_del_Contrato__c it = new Item_del_Contrato__c();
        it.Contrato_de_Multiplicacion__c = cc.id;
        insert it;
        
        try
        {
            cc.Tipo_de_Cota_o__c = 'DOLAR';
            update cc;
        }
        catch(Exception e)
        {
            Boolean expectedExceptionThrown = e.getMessage().contains('Não pode ser modificado o tipo de cotação') ? true : false;
            System.AssertEquals(expectedExceptionThrown, true);
        }   
    }  
}