force-app/main/default/objects/Contrato__c/Contrato__c.object-meta.xml
<CustomObject>
    <description>Addendum to the Soybean Germplasm Aggrement.</description>
    <label>Schedule A</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Schedule A Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedules A</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_del_Contrato__c/Item_del_Contrato__c.object-meta.xml
<CustomObject>
    <description>Addendum Variety item</description>
    <label>Schedule A Variety</label>
    <nameField>
        <label>Schedule A Variety</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Schedules A Variety</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item_del_Contrato__c/fields/Cultivar__c.field-meta.xml
<CustomField>
    <fullName>Cultivar__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Cultivar por el/los que se confecciona el contrato</description>
    <inlineHelpText>Cultivar por el/los que se confecciona el contrato</inlineHelpText>
    <label>Product Name</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.Family</field>
            <operation>equals</operation>
            <value>Royalty</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Schedules A Variety</relationshipLabel>
    <relationshipName>Items_del_Contrato</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Item_del_Contrato__c/fields/Exclusive__c.field-meta.xml
<CustomField>
    <fullName>Exclusive__c</fullName>
    <label>Exclusive</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>YES</fullName>
            </value>
            <value>
                <fullName>NO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Item_del_Contrato__c/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <formula>Cultivar__r.Variedade__r.Name</formula>
    <label>Variety Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Exclusive_Variety__c.field-meta.xml
<CustomField>
    <fullName>Exclusive_Variety__c</fullName>
    <formula>Variedade__r.Exclusive_Variety__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Exclusive Variety</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Variedade__c.field-meta.xml
<CustomField>
    <fullName>Variedade__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Variety Name</label>
    <referenceTo>Variedad__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Variedad__c/Variedad__c.object-meta.xml
<CustomObject>
    <label>Variety</label>
    <nameField>
        <label>Variety Description</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Varieties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Variedad__c/fields/Exclusive_Variety__c.field-meta.xml
<CustomField>
    <fullName>Exclusive_Variety__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Exclusive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ScheduleAVarietyTriggerTest.cls
@isTest
private class ScheduleAVarietyTriggerTest {
	@TestSetup
	static void makeData() {
		Variedad__c aVariety = Build.aVariedad().withName('Variety One').build();
		insert aVariety;
		Product2 aProduct = Build.aProduct2().withName('Product 1').withVariedade(aVariety).withFamily('ROYALTY').build();
		insert aProduct;
		Contrato__c schedule = Build.aContratoParentSeedScheduleA().build();
        insert schedule;
		Item_del_contrato__c aScheduleAv = Build.anItemdelContrato().withActive(true).withCultivar(aProduct).withContratodeMultiplicacion(schedule).build();
		insert aScheduleAv;
	}

	@isTest
	static void testChangingScheduleAVarietyExclusiveToYesShouldChangeInVariety() {
		Item_del_Contrato__c scheduleAV = [
			SELECT Id, Cultivar__r.Variedade__r.Exclusive_Variety__c
			FROM Item_del_Contrato__c
			LIMIT 1
		];
		scheduleAV.Exclusive__c = 'YES';
		Test.startTest();
		update scheduleAV;
		Test.stopTest();
		Variedad__c aVariety = [
			SELECT Id, Exclusive_Variety__c
			FROM Variedad__c
			WHERE Id = :scheduleAV.Cultivar__r.Variedade__c
			LIMIT 1
		];
		System.assertEquals(scheduleAV.Exclusive__c == 'YES', aVariety.Exclusive_Variety__c);
	}
}