force-app/main/default/objects/Seed_Tracking__c/Seed_Tracking__c.object-meta.xml
<CustomObject>
    <label>Seed Track</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Seed Track Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seed Tracks</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Seed_Tracking__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Seeds_Tracking</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Variety</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Seed_Tracking__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Seed Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/aSeedTrackingManager.cls
public class aSeedTrackingManager{
    
    public aSeedTrackingManager(){}        
    
    public static Set<String> getVarietiesSeedTracking(Id accId){
        try{
            List<Seed_Tracking__c> tmpOppItems = new List<Seed_Tracking__c>();
            Set<String> variedades = new Set<String>();
                                 
            tmpOppItems = aSiteUtils.queryResults1(Seed_Tracking__c.SObjectType, null, 'Account__c = :v1', accId);
            for(Seed_Tracking__c s : tmpOppItems){
                if (s.Brand__c != null && s.Brand__c != '')
                    variedades.add(s.Brand__c);                
            }
            return variedades;
        }
        catch(Exception e){
            return null;
        }
    }
    
    public static Set<String> getStatusSeedTracking(Id accId){
        try{
            List<Seed_Tracking__c> tmpOppItems = new List<Seed_Tracking__c>();
            Set<String> status = new Set<String>();
                                 
            tmpOppItems = aSiteUtils.queryResults1(Seed_Tracking__c.SObjectType, null, 'Account__c = :v1', accId);
            for(Seed_Tracking__c s : tmpOppItems){
                if (s.Status__c != null && s.Status__c != '')
                    status.add(s.Status__c);                
            }
            return status;
        }
        catch(Exception e){
            return null;
        }
    }
    
    public static Set<String> getSeedTypeSeedTracking(Id accId){
        try{
            List<Seed_Tracking__c> tmpOppItems = new List<Seed_Tracking__c>();
            Set<String> types = new Set<String>();
                                 
            tmpOppItems = aSiteUtils.queryResults1(Seed_Tracking__c.SObjectType, null, 'Account__c = :v1', accId);
            for(Seed_Tracking__c s : tmpOppItems){
                if (s.Type__c != null && s.Type__c != '')
                    types.add(s.Type__c);                
            }
            return types;
        }
        catch(Exception e){
            return null;
        }
    }
    
    public static List<Seed_Tracking__c> getItemsSeedTracking(Id accId, String variety, String status, String seedType){
        try{
        
            String query = 'Select ' + string.join(new list<string>(Seed_Tracking__c.SObjectType.getdescribe().fields.getmap().keyset()),',');
            query += ' From Seed_Tracking__c Where Account__c = \'' + accId + '\'';
            if (variety != '' && variety != null)
                query += ' And Brand__c = \'' + variety + '\'';
            if (status != '' && status != null)
                query += ' And Status__c = \'' + status + '\'';
            if (seedType!= '' && seedType!= null)
                query += ' And Type__c = \'' + seedType + '\'';
                               
            return Database.query(query);                                
            
        }
        catch(Exception e){
            return null;
        }
    }
    
}