force-app/main/default/objects/Centro_de_CO__c/Centro_de_CO__c.object-meta.xml
<CustomObject>
    <label>Centro de CO</label>
    <nameField>
        <label>CO Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centros de CO</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Centro_de_CO__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Centro_de_CO__c/fields/Campania__c.field-meta.xml
<CustomField>
    <fullName>Campania__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>15/16</fullName>
            </value>
            <value>
                <fullName>16/2016</fullName>
            </value>
            <value>
                <fullName>17/2017</fullName>
            </value>
            <value>
                <fullName>18/2018</fullName>
            </value>
            <value>
                <fullName>19/2019</fullName>
            </value>
            <value>
                <fullName>20/2020</fullName>
            </value>
            <value>
                <fullName>21/2021</fullName>
            </value>
            <value>
                <fullName>22/2022</fullName>
            </value>
            <value>
                <fullName>23/2023</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Centro_de_CO__c/fields/Orden__c.field-meta.xml
<CustomField>
    <fullName>Orden__c</fullName>
    <label>SAP Order</label>
    <length>16</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Centro_de_CO__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Royalty</fullName>
            </value>
            <value>
                <fullName>Seed</fullName>
            </value>
            <value>
                <fullName>Freight</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Centro_de_CO__c/fields/Sociedad__c.field-meta.xml
<CustomField>
    <fullName>Sociedad__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>01US</fullName>
            </value>
            <value>
                <fullName>02US</fullName>
            </value>
            <value>
                <fullName>BRMX</fullName>
                <isActive>false</isActive>
                <label>BRMX</label>
            </value>
            <value>
                <fullName>DSEM</fullName>
                <isActive>false</isActive>
                <label>DSEM</label>
            </value>
            <value>
                <fullName>E002</fullName>
                <isActive>false</isActive>
                <label>E002</label>
            </value>
            <value>
                <fullName>U001</fullName>
                <isActive>false</isActive>
                <label>U001</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Centro_de_CO_Item__c/Centro_de_CO_Item__c.object-meta.xml
<CustomObject>
    <label>Centro de CO Item</label>
    <nameField>
        <label>Nombre de Centro de CO</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Centro de CO Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Centro_de_CO_Item__c/fields/Centro_de_CO__c.field-meta.xml
<CustomField>
    <fullName>Centro_de_CO__c</fullName>
    <label>Centro de CO</label>
    <referenceTo>Centro_de_CO__c</referenceTo>
    <relationshipLabel>Centro de CO Items</relationshipLabel>
    <relationshipName>Centro_de_CO_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Centro_de_CO_Item__c/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Centro_de_CO__r.Campania__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Season</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Condicion_de_Pago__c.field-meta.xml
<CustomField>
    <fullName>Condicion_de_Pago__c</fullName>
    <label>Payment Terms</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZC05 Net 30 days from shipping date</fullName>
                <default>true</default>
                <label>Net 30 days from shipping date</label>
            </value>
            <value>
                <fullName>ZC04 Net 20 days from shipping date</fullName>
                <label>Net 20 days from shipping date</label>
            </value>
            <value>
                <fullName>ZC05 - S4 test Condition</fullName>
                <label>S4 test Condition</label>
            </value>
            <value>
                <fullName>ZC00 Due Upon Receipt</fullName>
                <label>Due Upon Receipt</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Contact_of_Shipping__c.field-meta.xml
<CustomField>
    <fullName>Contact_of_Shipping__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact of Shipping</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Ship_To__c</field>
            <operation>equals</operation>
            <valueField>Contact.Account.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Contact of Shipping)</relationshipLabel>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/discharge_date_sap__c.field-meta.xml
<CustomField>
    <fullName>discharge_date_sap__c</fullName>
    <label>discharge date sap</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/docRel__c.field-meta.xml
<CustomField>
    <fullName>docRel__c</fullName>
    <label>docRel</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Incoterm_1__c.field-meta.xml
<CustomField>
    <fullName>Incoterm_1__c</fullName>
    <label>Incoterm</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DED - Deliver to ship-to address</fullName>
                <default>true</default>
                <label>DED - Deliver to ship-to address</label>
            </value>
            <value>
                <fullName>DEP - Pick Up</fullName>
            </value>
            <value>
                <fullName>CFR - Cost and Freight</fullName>
            </value>
            <value>
                <fullName>CIF - Cost Insurance and Freight</fullName>
            </value>
            <value>
                <fullName>CIP - Carriage and Insurance Paid (To)</fullName>
            </value>
            <value>
                <fullName>CPT - Carriage Paid To</fullName>
            </value>
            <value>
                <fullName>DAP - Delivered At Place</fullName>
            </value>
            <value>
                <fullName>DAT - Delivered At Terminal</fullName>
            </value>
            <value>
                <fullName>DDP - Delivered Duty Paid</fullName>
            </value>
            <value>
                <fullName>DIB - Deliver</fullName>
            </value>
            <value>
                <fullName>EXW - Ex Works</fullName>
            </value>
            <value>
                <fullName>FAS - Free Alongside Ship</fullName>
            </value>
            <value>
                <fullName>FCA - Free Carrier</fullName>
            </value>
            <value>
                <fullName>FOB - Free On Board</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Incoterm_2__c.field-meta.xml
<CustomField>
    <fullName>Incoterm_2__c</fullName>
    <label>Incoterm 2</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>MARION</fullName>
            </value>
            <value>
                <fullName>NEWPORT</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Marca__c.field-meta.xml
<CustomField>
    <fullName>Marca__c</fullName>
    <label>Brand</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Marca</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Nro_Pedido_SAP__c.field-meta.xml
<CustomField>
    <fullName>Nro_Pedido_SAP__c</fullName>
    <externalId>true</externalId>
    <label>SAP Order Number</label>
    <length>12</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <label>Season</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Safra</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Sales_Office__c.field-meta.xml
<CustomField>
    <fullName>Sales_Office__c</fullName>
    <label>Sales Office</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Company__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>US00 - Without office</fullName>
                <default>true</default>
                <label>US00 - Without office</label>
            </value>
            <value>
                <fullName>US01 - Exterior</fullName>
            </value>
            <value>
                <fullName>US02 - North Corn Belt</fullName>
            </value>
            <value>
                <fullName>US03 - Mindaka</fullName>
            </value>
            <value>
                <fullName>US04 - West</fullName>
            </value>
            <value>
                <fullName>US05 - Eastern Corn Belt</fullName>
            </value>
            <value>
                <fullName>US06 - Central Cornbelt</fullName>
            </value>
            <value>
                <fullName>US07 - Midsouth</fullName>
            </value>
            <value>
                <fullName>US08 - East Coast</fullName>
            </value>
            <value>
                <fullName>US09 - Grand Lakes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/SAP_Integration_Error__c.field-meta.xml
<CustomField>
    <fullName>SAP_Integration_Error__c</fullName>
    <label>SAP Integration Error</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Status_Integracion__c.field-meta.xml
<CustomField>
    <fullName>Status_Integracion__c</fullName>
    <label>Status Integración SAP</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/recordTypes/Sale.recordType-meta.xml
<RecordType>
    <fullName>Sale</fullName>
    <active>true</active>
    <businessProcess>Invoice</businessProcess>
    <label>Sale</label>
</RecordType>

force-app/main/default/objects/OpportunityLineItem/fields/Comments__c.field-meta.xml
<CustomField>
    <fullName>Comments__c</fullName>
    <label>Comments</label>
    <length>30000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Order Company</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Company</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/DocRel__c.field-meta.xml
<CustomField>
    <fullName>DocRel__c</fullName>
    <label>DocRel</label>
    <length>131000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Material__c.field-meta.xml
<CustomField>
    <fullName>Material__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Material</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Opportunity Product</relationshipLabel>
    <relationshipName>Opportunity_Product</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Motivo_de_Rechazo__c.field-meta.xml
<CustomField>
    <fullName>Motivo_de_Rechazo__c</fullName>
    <label>Rejection Reason</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Safra__c.field-meta.xml
<CustomField>
    <fullName>Safra__c</fullName>
    <formula>TEXT(Opportunity.Safra__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Safra</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Waiting_Sync_To_Delete__c.field-meta.xml
<CustomField>
    <fullName>Waiting_Sync_To_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Waiting Sync To Delete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Codigo_Material_SAP__c.field-meta.xml
<CustomField>
    <fullName>Codigo_Material_SAP__c</fullName>
    <label>SAP Product ID</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Grupo_de_Vendedores__c.field-meta.xml
<CustomField>
    <fullName>Grupo_de_Vendedores__c</fullName>
    <label>Sap Seller Code</label>
    <length>3</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ModificaPedidoIntegrationS4BO.cls
/**
 * @description       :
 * @author            : Horacio Calleja
 * @group             :
 * @last modified on  : 01-17-2023
 * @last modified by  : Horacio Calleja
 **/
public class ModificaPedidoIntegrationS4BO implements IProcessingQueue {
	static public String methodToTest;

	public static void executeQueue(String queueId, String recordId, String eventName, String payload, Integer target) {
		try {
			outboundIntegration(queueId, recordId, eventName, payload);
			methodToTest = 'executeQueue_outboundIntegration';
		} catch (Exception ex) {
			system.debug('excepcion al ejecutar "outboundIntegration", catch del executeQueue.');
			QueueBO.getInstance()
				.updateQueue(queueId, eventName + ' / ' + ex.getMessage() + ' / ' + ex.getStackTraceString());
		}
	}

	@future(callout=true)
	@TestVisible
	private static void outboundIntegration(String queueId, String recordId, String eventName, String payload) {
		sapModificaPedidoS4.Z_SD_MODIFICA_PEDIDO_2 soap = new sapModificaPedidoS4.Z_SD_MODIFICA_PEDIDO_2();
		sapModificaPedidoS4.Z_SD_MODIFICA_PEDIDO_2Response_element resultado;
		sapModificaPedidoS4.BAPIRET2_TAB mensajes;

		String mens = '';

		sapModificaPedidoS4.Z_SD_MODIFICA_PEDIDO_2_element request_x = (sapModificaPedidoS4.Z_SD_MODIFICA_PEDIDO_2_element) JSON.deserialize(
			payload,
			sapModificaPedidoS4.Z_SD_MODIFICA_PEDIDO_2_element.class
		);
		sapModificaPedidoS4.ZSSD_DATA_MODIFICA_PEDIDO_IN2 IS_DATA = request_x.IS_DATA;

		soap.inputHttpHeaders_x = new Map<String, String>();
		SAPEndpoint__c endpoint = SAPEndpoint__c.getOrgDefaults();
		String encodedusernameandpassword;

		String myData = endpoint.Username__c + ':' + endpoint.Password__c;

		Blob hash = Blob.valueOf(myData);
		encodedusernameandpassword = EncodingUtil.base64Encode(hash);
		soap.timeout_x = 90000;
		soap.inputHttpHeaders_x.put('Authorization', 'Basic ' + encodedusernameandpassword);

		try {
			// resultado = soap.ZSdModificaPedido2(IS_DATA);
			resultado = soap.Z_SD_MODIFICA_PEDIDO_2(IS_DATA);

			ProcessControl.ignoredByTrigger = true;

			mensajes = resultado.ET_RETURN;

			for (Integer i = 0; i < mensajes.item.size(); i++) {
				mens += mensajes.item[i].Message + '\n';
			}
			mens = mens.abbreviate(255);
			Opportunity oppTEst;
			Boolean success = true;

			if (!JSON.serialize(resultado).contains('"Type_x":"E"')) {
				if (Test.isRunningTest()) {
					oppTEst = makeOpportunity_and_AccountForTest('Integrated');
					oppTEst.discharge_date_sap__c = System.now();
					insert oppTEst;
				} else {
					Opportunity opp = new Opportunity(
						Id = recordId,
						discharge_date_sap__c = System.now(),
						Status_Integracion__c = 'Integrated',
						Sap_Integration_Error__c = null
					);
					update opp;
					Approval.lock(opp.Id);
				}

				delete [
					SELECT Id
					FROM OpportunityLineItem
					WHERE Waiting_Sync_To_Delete__c = TRUE AND OpportunityId = :recordId
				];

				if (resultado.ET_REL_POS.item != null) {
					Set<OpportunityLineItem> items = new Set<OpportunityLineItem>();
					for (sapModificaPedidoS4.ZSSD_POS_SF_SAP i : resultado.ET_REL_POS.item) {
						if (Test.isRunningTest()) {
							items.add(makeOpportunityLineItemForTest(i.POSNR, oppTEst));
						} else {
							items.add(
								new OpportunityLineItem(
									Id = i.ZZPOSSF,
									Posicion_Relativa_Consign__c = String.isNotBlank(i.POSNR) ? i.POSNR : null
								)
							);
						}
					}
					List<OpportunityLineItem> targetItems = new List<OpportunityLineItem>();
					targetItems.addAll(items);
					upsert targetItems;
				}
			} else {
				if (Test.isRunningTest()) {
					Opportunity opp = makeOpportunity_and_AccountForTest('Integration Error');
					insert opp;
				} else {
					update new Opportunity(
						Id = recordId,
						Status_Integracion__c = 'Integration Error',
						Sap_Integration_Error__c = mens
					);
				}
			}

			if (Test.isRunningTest()) {
				QueueBO.getInstance().insertQueueConfirmForTest(eventName + ' - ' + mens + '\n' + JSON.serialize(resultado));
			} else {
				string xmlResult = eventName + ' - ' + mens + '\n' + JSON.serialize(resultado);
				// if(xmlResult.contains( '"Type_x":"E"' )){
				//     update new Opportunity(
				//         Id = recordId,
				//         discharge_date_sap__c = System.now(),
				//         Sap_Integration_Status__c = 'Integration Error',
				//         Sap_Integration_Error__c = mens.abbreviate(255)
				//     );
				// }
				QueueBO.getInstance().updateQueueConfirm(queueId, xmlResult);
			}
		} catch (Exception ex) {
			ProcessControl.ignoredByTrigger = true;
			System.debug(ex.getMessage());
			String error = ex.getMessage().abbreviate(255);
			update new Opportunity(
				Id = recordId,
				Status_Integracion__c = 'Integration Error',
				Sap_Integration_Error__c = error
			);
			QueueBO.getInstance()
				.updateQueue(queueId, eventName + ' / ' + ex.getMessage() + ' / ' + ex.getStackTraceString());
		}
	}

	public static Map<Id, String> setCentroCO(Opportunity o) {
		Map<Id, String> materialCostOrder = new Map<Id, String>();
		Set<Id> productIds = new Set<Id>();
		for (OpportunityLineItem item : o.OpportunityLineItems) {
			productIds.add(item.Product2Id);
		}
		String company = '01US';
		if (o.Company__c == 'B&B') {
			company = '02US';
		}

		Map<Id, String> productFamilyById = new Map<Id, String>();
		for (Product2 theProduct : [SELECT Family FROM Product2 WHERE Id IN :productIds]) {
			productFamilyById.put(theProduct.Id, theProduct.Family);
		}

		for (Centro_de_CO__c costOrder : [
			SELECT Orden__c, Product_Family__c
			FROM Centro_de_CO__c
			WHERE
				Sociedad__c = :company
				AND Brand__c = :o.Marca__c
				AND Campania__c = :o.Safra__c
				AND Product_Family__c IN :productFamilyById.values()
		]) {
			for (String productId : productFamilyById.keySet()) {
				if (productFamilyById.get(productId) == costOrder.Product_Family__c) {
					materialCostOrder.put(productId, costOrder.Orden__c);
				}
			}
		}

		return materialCostOrder;
	}

	public static String outboundRequestUpdate(Opportunity o) {
		String step = 'Inicio';
		String empresa; //'U001';
		// sapModificaPedidoS4.ZSdModificaPedido2_element request = new sapModificaPedidoS4.ZSdModificaPedido2_element();
		sapModificaPedidoS4.Z_SD_MODIFICA_PEDIDO_2_element request = new sapModificaPedidoS4.Z_SD_MODIFICA_PEDIDO_2_element();
		// Get CentroCO
		Map<Id, String> materialCostOrder = new Map<Id, String>();
		materialCostOrder = setCentroCO(o);

		//Cabecera
		// request.IS_DATA = new sapModificaPedidoS4.ZssdDataModificaPedidoIn2();
		request.IS_DATA = new sapModificaPedidoS4.ZSSD_DATA_MODIFICA_PEDIDO_IN2();

		// request.IS_DATA.Vbeln = o.Nro_Pedido_SAP__c;
		request.IS_DATA.VBELN = o.Nro_Pedido_SAP__c;

		request.IS_DATA.ZTERM = o.Condicion_de_Pago__c.substring(0, 4);

		if (o.Incoterm_1__c != null)
			request.IS_DATA.INCO1 = o.Incoterm_1__c.substring(0, 3);
		if (o.Incoterm_2__c != null)
			request.IS_DATA.INCO2 = o.Incoterm_2__c.trim();
		request.IS_DATA.AUGRU = o.Type.substring(0, 3); //Motivo de pedido, solo para CANJE o ESPECIE
		System.debug(request.IS_DATA.AUGRU);
		System.debug(o.Type);
		request.IS_DATA.ZTERM = o.Condicion_de_Pago__c.substring(0, 4);
		request.IS_DATA.VKBUR = 'US01';
		if (o.Sales_Office__c != null)
			request.IS_DATA.VKBUR = o.Sales_Office__c.substring(0, 4); // Oficina de Ventas
		request.IS_DATA.VKGRP = '';
		if (o.Owner.Grupo_de_Vendedores__c != null)
			request.IS_DATA.VKGRP = o.Owner.Grupo_de_Vendedores__c.substring(0, 3);

		if (request.IS_DATA.ZTERM == 'ZC04' || request.IS_DATA.ZTERM == 'ZC05')
			request.IS_DATA.VALDT = '';
		else {
			request.IS_DATA.VALDT = String.valueOf(o.CloseDate).substring(0, 10);
		}

		//request.IS_DATA.Augru = ''; //o.Type == 'Booking' ? '' : o.Type;

		// Textos
		request.IS_DATA.TEXTOS = new sapModificaPedidoS4.ZSSD_TEXTOS_TAB3();
		request.IS_DATA.TEXTOS.item = new List<sapModificaPedidoS4.ZSSD_TEXTOS3>();

		sapModificaPedidoS4.ZSSD_TEXTOS3 headerNote = new sapModificaPedidoS4.ZSSD_TEXTOS3();
		if (o.Contact_of_Shipping__c != null) {
			if (o.Contact_of_Shipping__r.Name != null) {
				headerNote.POSNR = '000000';
				headerNote.TEXT_ID = '0006';
				headerNote.LANGU = 'E';
				headerNote.TEXT_LINE = o.Contact_of_Shipping__r.Name;
			}
		}

		if (String.isNotBlank(headerNote.TEXT_LINE))
			request.IS_DATA.TEXTOS.item.add(headerNote);

		// request.IS_DATA.Posiciones = new sapModificaPedidoS4.ZttsdDataModifPedidoPos2();
		request.IS_DATA.POSICIONES = new sapModificaPedidoS4.ZTTSD_DATA_MODIF_PEDIDO_POS2();
		// request.IS_DATA.Posiciones.item = new List<sapModificaPedidoS4.ZssdDataModifPedidoPos2>();
		request.IS_DATA.POSICIONES.item = new List<sapModificaPedidoS4.ZSSD_DATA_MODIF_PEDIDO_POS2>();

		for (OpportunityLineItem oppLi : o.OpportunityLineItems) {
			if (oppLi.Motivo_de_rechazo__c != null || oppLi.DocRel__c != null) {
				continue;
			}
			if (!oppLi.Waiting_Sync_To_Delete__c) {
				sapModificaPedidoS4.ZSSD_TEXTOS3 itemNote = new sapModificaPedidoS4.ZSSD_TEXTOS3();

				if (String.isNotBlank(oppLi.Posicion_Relativa_Consign__c)) {
					itemNote.POSNR = oppLi.Posicion_Relativa_Consign__c;
				} else {
					itemNote.POSNR = '000000';
					itemNote.ZZPOSSF = oppLi.Id;
				}

				itemNote.TEXT_ID = 'Z001';
				itemNote.LANGU = 'E';
				itemNote.TEXT_LINE = oppLi.Comments__c;

				if (String.isNotBlank(itemNote.TEXT_LINE))
					request.IS_DATA.TEXTOS.item.add(itemNote);
			}
			sapModificaPedidoS4.ZSSD_DATA_MODIF_PEDIDO_POS2 itemPos = new sapModificaPedidoS4.ZSSD_DATA_MODIF_PEDIDO_POS2();

			if (String.isNotBlank(oppLi.Posicion_Relativa_Consign__c)) {
				itemPos.POSNR = oppLi.Posicion_Relativa_Consign__c;
				if (oppLi.Waiting_Sync_To_Delete__c) {
					itemPos.UPDATEFLAG = 'D';
				}
			} else {
				itemPos.ZZPOSSF = oppLi.Id;
				itemPos.MATNR = oppLi.Product2.Codigo_Material_SAP__c;
				itemPos.UPDATEFLAG = 'I';
			}

			if (oppLi.material__c != null && o.Type == 'Z35') {
				if (oppLi.Material__r.Posicion_Relativa_Consign__c != null) {
					itemPos.UEPOS = oppLi.Material__r.Posicion_Relativa_Consign__c;
				}
				itempos.ZUEPOS = oppLi.Material__c;
			} else if (oppLi.material__c != null && o.Type == 'ZX') {
				if (oppLi.Material__r.Posicion_Relativa_Consign__c != null) {
					itemPos.UEPOS = oppLi.Material__r.Posicion_Relativa_Consign__c;
				}
				itemPos.ZUEPOS = oppLi.Material__c;
			}

			if (!oppLi.Waiting_Sync_To_Delete__c) {
				itemPos.KWMENG = String.valueOf(oppLi.Quantity);
				itemPos.WERKS = 'U001';
				itemPos.LGORT = oppLi.Warehouse__c != null
					? String.valueOf(oppLi.Warehouse__c).left(oppLi.Warehouse__c.indexOf('-'))
					: null;
				if (oppLi.Centro_de_Despacho__c != null && oppLi.Centro_de_Despacho__c != '')
					itemPos.WERKS = oppLi.Centro_de_Despacho__c.substring(0, 4);

				if (oppLi.Product2.Family == 'Freight') {
					if (oppLi.Freight_Charge__c == 'Billable') {
						itemPos.PSTYV = 'Z070';
					} else if (oppLi.Freight_Charge__c == 'Non billable') {
						itemPos.PSTYV = 'Z071';
					}
				}
				//itemPos.AUFNR = '000000600004';
				//for(Centro_de_CO_Item__c centro : [Select c.Centro_de_CO__c, Centro_de_CO__r.Orden__c from Centro_de_CO_Item__c c Where c.Centro_de_CO__r.Sociedad__c = :empresa and c.Centro_de_CO__r.Campania__c = :o.safra__c And c.producto__c = :oppLi.Product2Id])
				//    itemPos.AUFNR = centro.Centro_de_CO__r.Orden__c;

				if (materialCostOrder.containsKey(oppLi.product2Id))
					itemPos.AUFNR = materialCostOrder.get(oppLi.product2Id);
				else
					itemPos.AUFNR = '';
				System.debug(oppLi.Name + ' / ' + itemPos.AUFNR);
				itemPos.CONDITIONS = new sapModificaPedidoS4.ZTTSD_DATA_MODIF_PEDIDO_COND();
				itemPos.CONDITIONS.item = new List<sapModificaPedidoS4.ZSSD_DATA_MODIFICA_PEDIDO_COND>();

				sapModificaPedidoS4.ZSSD_DATA_MODIFICA_PEDIDO_COND ICond1 = new sapModificaPedidoS4.ZSSD_DATA_MODIFICA_PEDIDO_COND();
				Decimal PR00 = 0.0;
				Double venta;
				Decimal Z100 = 0.0;

				venta = oppLi.UnitPrice;
				PR00 = Decimal.valueOf(venta);
				PR00 = PR00.divide(1, 2, System.RoundingMode.UP);

				if (venta == 0) {
					//Normalmente podria usarse en el caso de TEST SEED que sale con precio 0. En ese caso se envia un valor y su descuento.
					PR00 = oppLi.ListPrice;
					Z100 = Decimal.valueOf(1);
				}

				if (PR00 != 0) {
					ICond1.KSCHL = 'PR00';
					ICond1.WAERS = 'USD';

					// to include three decimal places in pricing in the sales orders, when the product is LB
					if (oppLi.Product2.Unidade__c == 'LB') {
						ICond1.KBETR = String.valueOf((PR00 * 10000).divide(1, 2, System.RoundingMode.HALF_EVEN));
						ICond1.KPEIN = '10000';
					} else {
						ICond1.KBETR = String.valueOf(PR00);
						ICond1.KPEIN = '1';
					}
					itemPos.CONDITIONS.item.add(ICond1);
				}

				if (Z100 != 0) {
					sapModificaPedidoS4.ZSSD_DATA_MODIFICA_PEDIDO_COND ICond2 = new sapModificaPedidoS4.ZSSD_DATA_MODIFICA_PEDIDO_COND();
					ICond2.KSCHL = 'Z100';
					ICond2.KBETR = '1000';
					ICond2.KPEIN = '1';
					ICond2.WAERS = 'USD';
					itemPos.CONDITIONS.item.add(ICond2);
				}
			}
			request.IS_DATA.Posiciones.item.add(itemPos);
		}

		return JSON.serialize(request);
	}

	private static Opportunity makeOpportunity_and_AccountForTest(String status) {
		String channel = '10';

		User DSM = [
			SELECT Id, Name, Sap_Sales_Office__c
			FROM User
			WHERE Sap_Sales_Office__c != NULL AND IsActive = TRUE
			LIMIT 1
		];

		Account acc = new Account(Name = 'Test', OwnerId = DSM.Id);
		insert acc;

		Opportunity opp = new Opportunity(
			Status_Integracion__c = status,
			AccountId = acc.Id,
			Ship_To__c = acc.Id,
			StageName = 'Approved',
			Name = 'oppTEst',
			CloseDate = System.today(),
			Probability = 1.1
		);
		return opp;
	}

	private static OpportunityLineItem makeOpportunityLineItemForTest(String POSNR, Opportunity opp) {
		Product2 prod = new Product2(Name = 'prod1', IsActive = true);
		insert prod;

		PricebookEntry standar = new PricebookEntry(
			Pricebook2Id = Test.getStandardPricebookId(),
			UnitPrice = 1,
			IsActive = true,
			Product2Id = prod.Id
		);
		insert standar;

		OpportunityLineItem prodOpp = new OpportunityLineItem(
			OpportunityId = opp.Id,
			Quantity = 1,
			PricebookEntryId = standar.Id,
			Posicion_Relativa_Consign__c = POSNR,
			TotalPrice = 1
		);
		return prodOpp;
	}
}