force-app/main/default/objects/GPOS_Customer_Report__c/GPOS_Customer_Report__c.object-meta.xml
<CustomObject>
    <label>GPOS Customer Report</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GPOS Customer Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GPOS_Customer_Report__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GPOS Customer Reports</relationshipLabel>
    <relationshipName>GPOS_Customer_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GPOS_Customer_Report__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/GPOS_Customer_Report__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/gposDownloadFileComponentControllerTest.cls
@isTest
public class gposDownloadFileComponentControllerTest {
    @isTest
    public static void gposDownloadFileComponentControllerTest() {
        Account activeAccount = new Account();
        activeAccount.Name = 'Angel Bedetti Test';
        insert activeAccount;
        GPOS_Customer_Report__c report = new GPOS_Customer_Report__c();
        report.Account__c = activeAccount.Id;
        report.Name = 'Test';
        report.Document__c = 'urlToDownload';
        report.Type__c = 'Customer';
        insert report; 

        Test.startTest();
        List<gposDownloadFileComponentController.FileWrapper> files = gposDownloadFileComponentController.getFiles(activeAccount.Id);
        Test.stopTest();
        System.assertEquals(1, files.Size());
    }
}