force-app/main/default/objects/GPOS_Customer_Report__c/GPOS_Customer_Report__c.object-meta.xml
<CustomObject>
    <label>GPOS Customer Report</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>GPOS Customer Reports</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/GPOS_Customer_Report__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>GPOS Customer Reports</relationshipLabel>
    <relationshipName>GPOS_Customer_Reports</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/GPOS_Customer_Report__c/fields/Document__c.field-meta.xml
<CustomField>
    <fullName>Document__c</fullName>
    <label>Document</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/GPOS_Customer_Report__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer</fullName>
            </value>
            <value>
                <fullName>Internal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/gposDownloadFileComponentController.cls
public class gposDownloadFileComponentController {
    
    @AuraEnabled
    public static List<FileWrapper> getFiles(String AccountId) {
        if(AccountId == null) {
            return null;
        }
        List<GPOS_Customer_Report__c> reports = [SELECT Id, Document__c, Name, CreatedDate, Type__c 
                                                    FROM GPOS_Customer_Report__c 
                                                    WHERE Account__c =:AccountId AND Type__c = 'Customer'
                                                    ORDER BY CreatedDate];
        List<FileWrapper> results = new List<FileWrapper>();
        for(GPOS_Customer_Report__c report : reports) {
            FileWrapper wr = new FileWrapper();
            wr.Link = report.Document__c;
            wr.FileName = report.Name;
            wr.Type = report.Type__c;
            wr.CreatedDate = report.CreatedDate.date();
            results.add(wr);
        }
        return results;

        

    }
    public class FileWrapper {
        @AuraEnabled 
        public String Link;
        @AuraEnabled
        public String FileName;
        @AuraEnabled
        public String Type;
        @AuraEnabled
        public Date CreatedDate;
    }

}